### ISSUE TITLE
Manual snapshot giving strange warning

### ISSUE THREAD

**Issue by uphillbattle** [home-assistant/supervisor#2369] opened 2020-12-14 13:44 UTC
### Describe the issue

Manual snapshot does not work. Automatic snapshots work fine.

About a minute after triggering a manual snapshot, the following message is reported in the Supervisor log:
`WARNING (MainThread) [supervisor.jobs] 'SnapshotManager.do_snapshot_full' blocked from execution, system is not running`

Might be related to the earlier reported issue #2328, but that is a guess, only.

Manual snapshots were working fine (albeit with the mysterious error message reported in issue #2328) as late as in HA 0.118.4.

### Steps to reproduce

1. Manually trigger a snapshot by clicking the CREATE button on the Supervisor->Snapshots page

### Enviroment details

- **Operating System**: Debian 10
- **Supervisor version**: 2020.12.6
- **Home Assistant version**: 2020.12.0

### Supervisor logs

<details>
<summary>Supervisor logs</summary>

```
20-12-14 13:18:49 INFO (MainThread) [supervisor.snapshots] Creating new full-snapshot with slug aa03440c
20-12-14 13:18:49 INFO (MainThread) [supervisor.snapshots] Snapshotting aa03440c store Add-ons
20-12-14 13:18:49 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on core_samba
20-12-14 13:18:49 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_samba
20-12-14 13:18:49 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on core_duckdns
20-12-14 13:18:49 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_duckdns
20-12-14 13:18:49 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on core_check_config
20-12-14 13:18:49 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_check_config
20-12-14 13:18:49 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on core_configurator
20-12-14 13:18:49 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_configurator
20-12-14 13:18:49 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on core_deconz
20-12-14 13:18:52 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_deconz
20-12-14 13:18:52 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on core_mosquitto
20-12-14 13:18:52 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_mosquitto
20-12-14 13:18:52 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on a0d7b954_nodered
20-12-14 13:18:52 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon a0d7b954_nodered
20-12-14 13:18:52 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on core_dnsmasq
20-12-14 13:18:52 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_dnsmasq
20-12-14 13:18:52 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on 7be23ff5_dropbox_sync
20-12-14 13:18:52 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon 7be23ff5_dropbox_sync
20-12-14 13:18:52 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on core_nginx_proxy
20-12-14 13:18:52 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_nginx_proxy
20-12-14 13:18:52 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on a0d7b954_grafana
20-12-14 13:18:52 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon a0d7b954_grafana
20-12-14 13:18:52 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on a0d7b954_influxdb
20-12-14 13:19:49 INFO (MainThread) [supervisor.snapshots] Found 11 snapshot files
20-12-14 13:19:49 WARNING (MainThread) [supervisor.jobs] 'SnapshotManager.do_snapshot_full' blocked from execution, system is not running

```

</details>

### System Information

<details>
<summary>System Information</summary>

```
System Health

version: 2020.12.0
installation_type: Home Assistant Supervised
dev: false
hassio: true
docker: true
virtualenv: false
python_version: 3.8.6
os_name: Linux
os_version: 4.19.0-10-amd64
arch: x86_64
timezone: Europe/Oslo


logged_in: true
subscription_expiration: 8. januar 2021, 1:00
relayer_connected: true
remote_enabled: true
remote_connected: true
alexa_enabled: false
google_enabled: true
can_reach_cert_server: ok
can_reach_cloud_auth: ok
can_reach_cloud: ok


host_os: Debian GNU/Linux 10 (buster)
update_channel: stable
supervisor_version: 2020.12.6
docker_version: 19.03.13
disk_total: 884.3 GB
disk_used: 96.9 GB
healthy: true
supported: true
supervisor_api: ok
version_api: ok
installed_addons: Samba share (9.3.0), Duck DNS (1.12.4), Check Home Assistant configuration (3.6.0), File editor (5.2.0), deCONZ (6.6.0), Mosquitto broker (5.1), Node-RED (7.2.11), Dnsmasq (1.3), Dropbox Sync (1.3.0), NGINX Home Assistant SSL proxy (3.0.1), Grafana (5.3.6), InfluxDB (3.7.9), Visual Studio Code (2.9.1), AppDaemon 4 (0.3.2), JupyterLab Lite (0.3.1), OpenZWave (0.7.1)


dashboards: 2
mode: storage
views: 15
resources: 0


api_endpoint_reachable: ok

```

</details>

EDIT: Please see additional information in [this comment below](https://github.com/home-assistant/supervisor/issues/2369#issuecomment-745224898).

**Comment by nic0dk** [comment] 2020-12-14 14:25
confirmed - same problem here on HA supervised

**Comment by NicoBijl** [comment] 2020-12-14 16:39
got the same issue. 
![image](https://user-images.githubusercontent.com/1883943/102108506-511c5e80-3e33-11eb-9626-f663e14c4e74.png)

**Comment by nic0dk** [comment] 2020-12-14 22:55
well i did play a bit more around with my problem, and it seems like i was hitting an "out of diskspace" while creating the backup file.. and that end up corrupting your file and we see this message. 

try to check your supervisor log while you are making the backup, also maybe exclude "share" under Folders and "Samba share" under add-ons in "Partial snapshot" - i ended up to have 1gb of backup file instead of having 7-10gb backup file.

if you have huge db files, maybe influxdb or mariadb, clean them up before the backup or exclude them

but i still think we are having a problem with full snapshot

**Comment by uphillbattle** [comment] 2020-12-15 08:09
I do an automated snapshot every night. Works without problems. Granted, it's big - about 5.5 GB now - and takes about 2.5 hours in my case. It's the backing up of the influxdb that takes most of the time, but there are no complaints in the logs.

So, I don't think the db files or the disk size comes into it. If I were to guess, it's got something to do with the frontend, but what do I know... 

<details>
<summary>Last night's automated snapshot logs</summary>

```
20-12-15 02:00:00 INFO (MainThread) [supervisor.snapshots] Creating new full-snapshot with slug 5ee49a80
20-12-15 02:00:00 INFO (MainThread) [supervisor.snapshots] Snapshotting 5ee49a80 store Add-ons
20-12-15 02:00:00 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on core_samba
20-12-15 02:00:00 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_samba
20-12-15 02:00:00 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on core_duckdns
20-12-15 02:00:00 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_duckdns
20-12-15 02:00:00 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on core_check_config
20-12-15 02:00:00 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_check_config
20-12-15 02:00:00 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on core_configurator
20-12-15 02:00:00 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_configurator
20-12-15 02:00:00 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on core_deconz
20-12-15 02:00:02 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_deconz
20-12-15 02:00:02 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on core_mosquitto
20-12-15 02:00:02 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_mosquitto
20-12-15 02:00:02 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on a0d7b954_nodered
20-12-15 02:00:02 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon a0d7b954_nodered
20-12-15 02:00:02 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on core_dnsmasq
20-12-15 02:00:02 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_dnsmasq
20-12-15 02:00:02 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on 7be23ff5_dropbox_sync
20-12-15 02:00:02 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon 7be23ff5_dropbox_sync
20-12-15 02:00:02 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on core_nginx_proxy
20-12-15 02:00:02 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_nginx_proxy
20-12-15 02:00:02 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on a0d7b954_grafana
20-12-15 02:00:02 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon a0d7b954_grafana
20-12-15 02:00:02 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on a0d7b954_influxdb
20-12-15 02:22:59 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
20-12-15 02:53:01 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
20-12-15 03:23:04 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
20-12-15 03:53:07 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
20-12-15 04:22:21 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon a0d7b954_influxdb
20-12-15 04:22:21 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on a0d7b954_vscode
20-12-15 04:23:09 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
20-12-15 04:26:23 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon a0d7b954_vscode
20-12-15 04:26:23 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on a0d7b954_appdaemon
20-12-15 04:26:23 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon a0d7b954_appdaemon
20-12-15 04:26:23 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on a0d7b954_jupyterlablite
20-12-15 04:26:23 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon a0d7b954_jupyterlablite
20-12-15 04:26:23 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on core_zwave
20-12-15 04:26:28 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_zwave
20-12-15 04:26:28 INFO (MainThread) [supervisor.snapshots] Snapshotting 5ee49a80 store folders
20-12-15 04:26:28 INFO (SyncWorker_3) [supervisor.snapshots.snapshot] Snapshot folder ssl
20-12-15 04:26:28 INFO (SyncWorker_3) [supervisor.snapshots.snapshot] Snapshot folder ssl done
20-12-15 04:26:28 INFO (SyncWorker_7) [supervisor.snapshots.snapshot] Snapshot folder homeassistant
20-12-15 04:27:47 INFO (SyncWorker_7) [supervisor.snapshots.snapshot] Snapshot folder homeassistant done
20-12-15 04:27:47 INFO (SyncWorker_6) [supervisor.snapshots.snapshot] Snapshot folder share
20-12-15 04:27:47 INFO (SyncWorker_6) [supervisor.snapshots.snapshot] Snapshot folder share done
20-12-15 04:27:47 INFO (SyncWorker_0) [supervisor.snapshots.snapshot] Snapshot folder addons/local
20-12-15 04:27:47 INFO (SyncWorker_0) [supervisor.snapshots.snapshot] Snapshot folder addons/local done
20-12-15 04:27:47 INFO (SyncWorker_5) [supervisor.snapshots.snapshot] Snapshot folder media
20-12-15 04:27:47 INFO (SyncWorker_5) [supervisor.snapshots.snapshot] Snapshot folder media done
20-12-15 04:30:12 INFO (MainThread) [supervisor.snapshots] Crating full-snapshot with slug 5ee49a80 completed

```
</details>

<details>
<summary>This is the automation that creates the automated snapshot</summary>


```
- id: make_snapshot
  alias: Make Snapshot
  trigger:
  - platform: time
    at: '03:00:00'
  condition: []
  action:
  - service: hassio.snapshot_full
    data_template:
      name: Automated Backup {{ now().strftime('%Y-%m-%d') }}
  - service: notify.notify 
    data_template:
      message: Created backup named "Automated Backup {{ now().strftime('%Y-%m-%d') }}"

```
</details>

**Comment by nic0dk** [comment] 2020-12-15 09:40
> If I were to guess, it's got something to do with the frontend
are you using any "proxy" to access your home assistant, like the nginx proxy manager ? 
if so, then try to access it directly on its local ip:port to see if you are getting the same error.  
if you are getting the same error, also try to reboot the Host system and take the backup again from its local ip

**Comment by uphillbattle** [comment] 2020-12-15 11:18
It seems that the warning message reported in the original post, is just an empty threat. The snapshot triggered by clicking the CREATE button was actually created - albeit with the strange warning. 

<details>
<summary>Here's the full log from yesterday</summary>

```
20-12-14 13:18:49 INFO (MainThread) [supervisor.snapshots] Creating new full-snapshot with slug aa03440c
20-12-14 13:18:49 INFO (MainThread) [supervisor.snapshots] Snapshotting aa03440c store Add-ons
20-12-14 13:18:49 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on core_samba
20-12-14 13:18:49 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_samba
20-12-14 13:18:49 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on core_duckdns
20-12-14 13:18:49 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_duckdns
20-12-14 13:18:49 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on core_check_config
20-12-14 13:18:49 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_check_config
20-12-14 13:18:49 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on core_configurator
20-12-14 13:18:49 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_configurator
20-12-14 13:18:49 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on core_deconz
20-12-14 13:18:52 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_deconz
20-12-14 13:18:52 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on core_mosquitto
20-12-14 13:18:52 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_mosquitto
20-12-14 13:18:52 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on a0d7b954_nodered
20-12-14 13:18:52 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon a0d7b954_nodered
20-12-14 13:18:52 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on core_dnsmasq
20-12-14 13:18:52 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_dnsmasq
20-12-14 13:18:52 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on 7be23ff5_dropbox_sync
20-12-14 13:18:52 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon 7be23ff5_dropbox_sync
20-12-14 13:18:52 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on core_nginx_proxy
20-12-14 13:18:52 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_nginx_proxy
20-12-14 13:18:52 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on a0d7b954_grafana
20-12-14 13:18:52 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon a0d7b954_grafana
20-12-14 13:18:52 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on a0d7b954_influxdb
20-12-14 13:19:49 INFO (MainThread) [supervisor.snapshots] Found 11 snapshot files
20-12-14 13:19:49 WARNING (MainThread) [supervisor.jobs] 'SnapshotManager.do_snapshot_full' blocked from execution, system is not running
20-12-14 13:22:10 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
20-12-14 13:28:43 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
20-12-14 13:28:43 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.FREEZE
20-12-14 13:28:43 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
20-12-14 13:34:21 INFO (MainThread) [supervisor.snapshots] Found 11 snapshot files
20-12-14 13:52:12 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
20-12-14 14:22:15 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
20-12-14 14:52:17 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
20-12-14 15:22:20 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
20-12-14 15:41:28 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon a0d7b954_influxdb
20-12-14 15:41:28 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on a0d7b954_vscode
20-12-14 15:45:28 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon a0d7b954_vscode
20-12-14 15:45:28 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on a0d7b954_appdaemon
20-12-14 15:45:28 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon a0d7b954_appdaemon
20-12-14 15:45:28 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on a0d7b954_jupyterlablite
20-12-14 15:45:28 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon a0d7b954_jupyterlablite
20-12-14 15:45:28 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on core_zwave
20-12-14 15:45:33 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_zwave
20-12-14 15:45:33 INFO (MainThread) [supervisor.snapshots] Snapshotting aa03440c store folders
20-12-14 15:45:33 INFO (SyncWorker_4) [supervisor.snapshots.snapshot] Snapshot folder ssl
20-12-14 15:45:33 INFO (SyncWorker_4) [supervisor.snapshots.snapshot] Snapshot folder ssl done
20-12-14 15:45:33 INFO (SyncWorker_5) [supervisor.snapshots.snapshot] Snapshot folder homeassistant
20-12-14 15:46:54 INFO (SyncWorker_5) [supervisor.snapshots.snapshot] Snapshot folder homeassistant done
20-12-14 15:46:54 INFO (SyncWorker_1) [supervisor.snapshots.snapshot] Snapshot folder share
20-12-14 15:46:54 INFO (SyncWorker_1) [supervisor.snapshots.snapshot] Snapshot folder share done
20-12-14 15:46:54 INFO (SyncWorker_0) [supervisor.snapshots.snapshot] Snapshot folder addons/local
20-12-14 15:46:54 INFO (SyncWorker_0) [supervisor.snapshots.snapshot] Snapshot folder addons/local done
20-12-14 15:46:54 INFO (SyncWorker_7) [supervisor.snapshots.snapshot] Snapshot folder media
20-12-14 15:46:54 INFO (SyncWorker_7) [supervisor.snapshots.snapshot] Snapshot folder media done
20-12-14 15:47:01 INFO (MainThread) [supervisor.snapshots] Crating full-snapshot with slug aa03440c completed

```

So, the snapshot WAS actually created yesterday, I just didn't wait it out and assumed that one wouldn't be created due to the WARNING issued.

Further, the "proxy" comment appears to be valid. The WARNING is issued when I access HA via the Nabu Casa URL. When I access HA via `http://local_ip:port` and click the CREATE button, a snapshot is created, but WITHOUT the warning message.

**Comment by jimmyeao** [comment] 2020-12-16 11:11
Same issue here, i see this when I try and create a snapshot
`<html> <head><title>504 Gateway Time-out</title></head> <body> <center><h1>504 Gateway Time-out</h1></center> <hr><center>nginx</center> </body> </html> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page -->`

and get this in the logs 
`20-12-16 11:09:25 WARNING (MainThread) [supervisor.jobs] 'SnapshotManager.do_snapshot_full' blocked from execution, system is not running`
![image](https://user-images.githubusercontent.com/5197831/102341207-6908f500-3f8f-11eb-8a92-4de13c280ae6.png)

**Comment by dennis-bell** [comment] 2021-01-15 09:58
Also got the same problem now..
After I changed my recorder from sqlite into mariadb.
```21-01-15 09:53:48 WARNING (MainThread) [supervisor.jobs] 'SnapshotManager.do_snapshot_partial' blocked from execution, system is not running```

```21-01-15 09:55:26 WARNING (MainThread) [supervisor.jobs] 'SnapshotManager.do_snapshot_full' blocked from execution, system is not running```

Also restarts do not work anymore
``` 21-01-15 09:55:36 WARNING (MainThread) [supervisor.jobs] 'Supervisor.restart' blocked from execution, system is not running```

**Comment by mhzawadi** [comment] 2021-01-17 09:21
I have this issue

## System Health

version | 2021.1.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.7
os_name | Linux
os_version | 5.4.79-v7
arch | armv7l
timezone | Europe/London

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4890
Installed Version | 1.10.0
Stage | running
Available Repositories | 709
Installed Repositories | 7

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 5.10
-- | --
update_channel | stable
supervisor_version | 2021.01.4
docker_version | 19.03.13
disk_total | 13.9 GB
disk_used | 5.1 GB
healthy | true
supported | true
board | rpi3
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.2.0), SSH & Web Terminal (7.8.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 2
-- | --
mode | auto-gen
resources | 1

</details>

```
21-01-16 22:34:57 INFO (SyncWorker_0) [supervisor.docker.interface] Starting homeassistant
21-01-16 22:34:57 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready
21-01-16 22:37:22 INFO (SyncWorker_3) [supervisor.docker.addon] Starting Docker add-on homeassistant/armv7-addon-configurator with version 5.2.0
21-01-16 22:42:28 INFO (MainThread) [supervisor.snapshots] Found 4 snapshot files
21-01-16 22:42:34 WARNING (MainThread) [supervisor.jobs] 'SnapshotManager.do_snapshot_full' blocked from execution, system is not running
21-01-16 22:42:52 INFO (MainThread) [supervisor.snapshots] Found 4 snapshot files
21-01-16 22:43:00 INFO (MainThread) [supervisor.snapshots] Removed snapshot file 543393c1
21-01-16 22:43:03 INFO (MainThread) [supervisor.snapshots] Removed snapshot file 3652a6fd
21-01-16 22:43:47 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.STARTUP
21-01-16 22:43:47 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
21-01-16 22:43:47 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
21-01-16 22:44:14 INFO (MainThread) [supervisor.snapshots] Found 2 snapshot files
21-01-16 22:44:19 WARNING (MainThread) [supervisor.jobs] 'SnapshotManager.do_snapshot_full' blocked from execution, system is not running
21-01-16 22:47:08 INFO (MainThread) [supervisor.snapshots] Found 2 snapshot files
21-01-16 22:47:09 WARNING (MainThread) [supervisor.jobs] 'SnapshotManager.do_snapshot_full' blocked from execution, system is not running
21-01-16 22:50:38 INFO (MainThread) [supervisor.utils.gdbus] Starting dbus monitor on org.freedesktop.NetworkManager
21-01-16 22:50:38 INFO (MainThread) [supervisor.utils.gdbus] Stopping dbus monitor on org.freedesktop.NetworkManager
21-01-16 22:50:38 INFO (MainThread) [supervisor.host.network] Updating local network information
21-01-16 22:51:06 INFO (MainThread) [supervisor.snapshots] Found 2 snapshot files
21-01-16 22:51:14 WARNING (MainThread) [supervisor.jobs] 'SnapshotManager.do_snapshot_full' blocked from execution, system is not running
21-01-17 09:16:50 INFO (MainThread) [supervisor.snapshots] Found 2 snapshot files
21-01-17 09:17:03 WARNING (MainThread) [supervisor.jobs] 'SnapshotManager.do_snapshot_full' blocked from execution, system is not running
21-01-17 09:17:48 WARNING (MainThread) [supervisor.jobs] 'Supervisor.restart' blocked from execution, system is not running
21-01-17 09:18:13 ERROR (MainThread) [supervisor.utils] Can't execute wrapper while a task is in progress
```

**Comment by mikekay1** [comment] 2021-01-18 18:31
Just thought I would mention this, if you don't put in a name for the snapshot it works!

**Comment by mhzawadi** [comment] 2021-01-19 07:50
Thanks for the info @mikekay1 , but not for me
```
21-01-19 07:42:17 INFO (MainThread) [supervisor.snapshots] Found 2 snapshot files
21-01-19 07:42:19 WARNING (MainThread) [supervisor.jobs] 'SnapshotManager.do_snapshot_full' blocked from execution, system is not running
21-01-19 07:49:04 INFO (MainThread) [supervisor.snapshots] Found 2 snapshot files
21-01-19 07:49:08 WARNING (MainThread) [supervisor.jobs] 'SnapshotManager.do_snapshot_full' blocked from execution, system is not running
21-01-19 07:49:13 WARNING (MainThread) [supervisor.jobs] 'SnapshotManager.do_snapshot_full' blocked from execution, system is not running
```

**Comment by mikekay1** [comment] 2021-01-19 14:23
> Thanks for the info @mikekay1 , but not for me
> 
> ```
> 21-01-19 07:42:17 INFO (MainThread) [supervisor.snapshots] Found 2 snapshot files
> 21-01-19 07:42:19 WARNING (MainThread) [supervisor.jobs] 'SnapshotManager.do_snapshot_full' blocked from execution, system is not running
> 21-01-19 07:49:04 INFO (MainThread) [supervisor.snapshots] Found 2 snapshot files
> 21-01-19 07:49:08 WARNING (MainThread) [supervisor.jobs] 'SnapshotManager.do_snapshot_full' blocked from execution, system is not running
> 21-01-19 07:49:13 WARNING (MainThread) [supervisor.jobs] 'SnapshotManager.do_snapshot_full' blocked from execution, system is not running
> ```

damn -- was worth a shot!

**Comment by mhzawadi** [comment] 2021-01-20 07:50
I have found a workaround to the problem, if you run hass OS you can install portainer and use that to restart the hass-supervisor container and then backups work.

TO do that you need to goto settings and remove the hass-supervisor container from the hidden list.

**Comment by jerometerrier** [comment] 2021-01-24 18:11
Hello
i had this issue too.
Solve with an **_hardware_** reboot.
Did you try it ?

**Comment by jimmyeao** [comment] 2021-01-24 19:40
> Hello
> i had this issue too.
> Solve with an **hardware** reboot.
> Did you try it ?

Several times, it does not fix it. I suspect it may have something to do with how I am using ssl/let’s encrypt

**Comment by jerometerrier** [comment] 2021-01-24 21:02
> > Hello
> > i had this issue too.
> > Solve with an **hardware** reboot.
> > Did you try it ?
> 
> Several times, it does not fix it. I suspect it may have something to do with how I am using ssl/let’s encrypt

Before to reboot, i have deleted each snapshot...

**Comment by jimmyeao** [comment] 2021-01-24 22:21
I had no pre existing snapshots...

Jimmy White
________________________________

**Comment by ludeeus** [comment] 2021-02-05 13:41
Duplicate of https://github.com/home-assistant/frontend/issues/8332

**Closed by ludeeus** 2021-02-05 13:41 UTC
Labels: bug
