### ISSUE TITLE
Update from 2024.11.2 -> 2024.11.3, error 404

### ISSUE THREAD

**Issue by kzajac83** [home-assistant/supervisor#5408] opened 2024-11-11 11:19 UTC
### Describe the issue you are experiencing

Hello

Got error when try update from 2024.11.2 -> 2024.11.3, error 404.  Details in screenshot:

![Screenshot_2024-11-11-12-10-17-196_io homeassistant companion android](https://github.com/user-attachments/assets/4ff766bb-8737-40e3-bacf-fe0efc5e1761)
[logs.txt](https://github.com/user-attachments/files/17701510/logs.txt)

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

Go to settings, there is update notification. Trying update it cause appear error. 
...

### Anything in the Supervisor logs that might be useful for us?

```txt
Logs in attached
```

## System Information

version | core-2024.11.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.54-haos
arch | x86_64
timezone | Europe/Warsaw
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 5000
Installed Version | 2.0.1
Stage | running
Available Repositories | 1461
Downloaded Repositories | 12

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 13.2
-- | --
update_channel | stable
supervisor_version | supervisor-2024.11.2
agent_version | 1.6.0
docker_version | 27.2.0
disk_total | 344.5 GB
disk_used | 20.9 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | kvm
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Mosquitto broker (6.4.1), File editor (5.8.0), Node-RED (18.1.1), Terminal & SSH (9.15.0), Zigbee2MQTT (1.41.0-1), Grafana (10.1.3), SQLite Web (4.2.2), Zigbee2MQTT Edge (edge), Batmon (1.78), ESPHome (2024.10.3), Glances (0.21.1), motionEye (0.21.0), [edge] Wmbusmeters (W-MBus to MQTT) (1.17.1-29), MQTT Explorer (browser-1.0.3), Energa meter (1.0.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 5
-- | --
resources | 4
views | 3
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | October 11, 2024 at 06:59
-- | --
current_recorder_run | November 9, 2024 at 19:42
estimated_db_size | 5163.13 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

**Comment by wetty** [comment] 2024-11-11 11:21
I have the same problem

**Comment by nickjdunkley** [comment] 2024-11-11 11:21
Same

**Comment by khzd** [comment] 2024-11-11 11:22
Same here on Debian 12 , ha supervised

**Comment by steamboy23** [comment] 2024-11-11 11:22
Same

**Comment by Titou84240** [comment] 2024-11-11 11:22
Same here

**Comment by markusguenther** [comment] 2024-11-11 11:24
Same here as well :)

**Comment by Takaszi** [comment] 2024-11-11 11:25
Podpisuję się o dodaję opis 
"niepowodzenie wykonania akcji update/install. Error updating Home Assistant Supervisor: Update of Supervisor failed: Can't install [ghor.io/home-assistant/aarch64-hassio-supervisor](http://ghor.io/home-assistant/aarch64-hassio-supervisor): 2024.11.3: 500 Server Error for http+docker://localhost/v1.47/images/create?tag-2024.11.38/fromImage-gher.io%2Fhome- assistant%2Faarch64-hassio-supervisor&platform-linux%2Farm64: Internal Server Error ("toomanyrequests: retry-after: 54.001us, allowed: 44000/minute")"

**Comment by StanAnsems** [comment] 2024-11-11 11:29
Same here

**Comment by bonvga** [comment] 2024-11-11 11:41
Hello, same issue here.

**Comment by Dweinbach** [comment] 2024-11-11 12:17
another one who has had both the 404 and the 500 errors.

**Comment by metbril** [comment] 2024-11-11 12:17
Duplicate of #5405 ?!
![image](https://github.com/user-attachments/assets/f104cada-b6dd-46a6-bd58-6fa790ebaa73)

**Comment by pzakrzep** [comment] 2024-11-11 12:43
Same issue

**Comment by agners** [comment] 2024-11-11 12:49
Duplicate of #5405, so closing.

**Comment by Rob-M-F** [comment] 2024-11-11 12:49
Also seeing what appears to be the same issue this morning on Home Assistant Green. Also 2024.11.2 -> 2024.11.3

The update is also reporting that it cannot be skipped.

![image](https://github.com/user-attachments/assets/4a564f07-04a0-42ec-9730-6533a542d4a0)

**Closed by agners** 2024-11-11 12:49 UTC
Labels: bug
