### ISSUE TITLE
Can't find Docker socket.

### ISSUE THREAD

**Issue by alex1261** [home-assistant/supervisor#1563] opened 2020-03-04 11:43 UTC
**Home Assistant release with the issue:**
Supervisor 207

**Operating environment (HassOS/Generic):**
CentOS with Docker running amd64-hassio-supervisor:207

**Supervisor logs:**
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] udev.sh: executing... 
[11:40:53] INFO: Update udev informations
[cont-init.d] udev.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
20-03-04 11:40:53 CRITICAL (MainThread) [supervisor.bootstrap] Can't find Docker socket!
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

Supervisor auto upgrades to 207 but then cannot find docker socket. Have validated volume mapping and permissions are correct.

Tested forceful rollback to 206 works, but then auto upgrades to 207 and fails again with same errors.

**Comment by pvizeli** [comment] 2020-03-04 16:03
Run the installer again and it should be fix: https://github.com/home-assistant/hassio-installer

**Comment by jsb5151** [comment] 2020-03-05 04:31
I have the same issue, and a reinstall won't fix it - I am running Supervisor 208 and am getting a "Can't find Docker socket!" as well.  Running RHEL 7.7.  HA started acting up when it upgraded the Supervisor to 207.  Now it won't start at all.

**Comment by pvizeli** [comment] 2020-03-05 08:30
Make sure you OS support FHS 3.0 - https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard. The new Supervisor did not support system they are not complain with FHS 3.0

**Comment by pvizeli** [comment] 2020-03-05 08:59
However, the issue is still clear with the log: You host system does not mount the docker socket into container.

Since you run your own Host OS and not use our Host OS, you need fix it by your self and that is also the reason why the Supervisor show this error to you for helping to fix your Host.

**Comment by jsb5151** [comment] 2020-03-05 14:02
RHEL & CentOS are fully compliant with FHS 3.0, so that is not the issue.  As for the docker.sock not being mounted in the container, I can see it is properly mounted.  206 is not exhibiting this issue but 207 & 208 are; I would love to troubleshoot but the supervisor is auto-updating itself to 208.  Is there a way to stop this?  Why did it upgrade automatically without my input?

**Comment by pvizeli** [comment] 2020-03-05 14:11
I update the hassio-installer. I think the issue comes with old docker version and links. Can you rerun the installer with the latest commit? Maybe that fix it

**Comment by jsb5151** [comment] 2020-03-05 14:15
Fixed!  /var/run -> /run was the answer ;)  Thank you.

**Comment by jsb5151** [comment] 2020-03-05 14:25
For everyone's info, this is what fixed it: https://github.com/home-assistant/hassio-installer/commit/e8e04aaeaf6e8058f10ebc149569db6f3cab705e

**Comment by pvizeli** [comment] 2020-03-05 14:51
What is your docker version? It's interesting that it was not over all system an issue.

**Closed** 2020-03-17 11:36 UTC
