### ISSUE TITLE
.log files are not included into the snapshot

### ISSUE THREAD

**Issue by paulius2k** [home-assistant/supervisor#2933] opened 2021-06-03 11:51 UTC
### Describe the issue you are experiencing

.log files (e.g. `/config/home-assistant.log` and my other custom ones) in `/config/` directory are not included in the snapshot - neither manual, nor automatic.

Is this by design?
Can this be changed to include .log files?

### What is the used version of the Supervisor?

supervisor-2021.05.4

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

5.13

### What version of Home Assistant Core is installed?

core-2021.6.0

### Steps to reproduce the issue

1. Go to Supervisor-->Snapshots-->(+)Create snapshot-->Full snapshot-->Create 
2. /config/*.log files are not in the resulting snapshot.tar file

### Anything in the Supervisor logs that might be useful for us?

```txt
I cannot spot any errors regarding the snapshot process in logs.
```

**Comment by ludeeus** [comment] 2021-06-03 12:03
This is by design, you can use _any_ other names for your files.

Since this is not a bug, I'm going to close this.
For feature requests please raise those on the [forums](https://community.home-assistant.io/c/feature-requests/13), thanks :+1:

**Closed by ludeeus** 2021-06-03 12:03 UTC
