### ISSUE TITLE
Unable to update from Supervisor 2022.08.3 to 2022.08.5

### ISSUE THREAD

**Issue by DesmondDu** [home-assistant/supervisor#3841] opened 2022-09-03 03:34 UTC
### Describe the issue you are experiencing

I am getting the following error in the supervisor log when I try to update to the latest version.
<html>
<body>

2022-09-03 03:11:09 | stderr | [31m22-09-03 11:11:09 ERROR (MainThread) [supervisor.core] Update '2022.08.5' of Supervisor '2022.08.3' failed![0m
-- | -- | --
2022-09-03 03:11:09 | stderr | [32m22-09-03 11:11:09 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete[0m
2022-09-03 03:11:09 | stderr | [33m22-09-03 11:11:09 WARNING (MainThread) [supervisor.resolution.evaluations.base] Found unsupported job conditions settings. (more-info: https://www.home-assistant.io/more-info/unsupported/job_conditions)[0m
2022-09-03 03:11:09 | stderr | [33m22-09-03 11:11:09 WARNING (MainThread) [supervisor.resolution.evaluations.base] The configuration of Docker is not supported (more-info: https://www.home-assistant.io/more-info/unsupported/docker_configuration)[0m
2022-09-03 03:11:09 | stderr | [33m22-09-03 11:11:09 WARNING (MainThread) [supervisor.resolution.evaluations.docker_configuration] Docker logging driver db is not supported![0m
2022-09-03 03:11:09 | stderr | [33m22-09-03 11:11:09 WARNING (MainThread) [supervisor.resolution.evaluations.docker_configuration] Docker storage driver btrfs is not supported![0m
2022-09-03 03:11:09 | stderr | [32m22-09-03 11:11:09 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.INITIALIZE[0m
2022-09-03 03:11:09 | stderr | [33m22-09-03 11:11:09 WARNING (SyncWorker_1) [supervisor.docker.interface] Can't find homeassistant/amd64-hassio-supervisor for cleanup[0m
2022-09-03 03:11:09 | stderr | [32m22-09-03 11:11:09 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
2022-09-03 03:11:09 | stderr | [32m22-09-03 11:11:09 INFO (SyncWorker_0) [supervisor.docker.supervisor] Attaching to Supervisor homeassistant/amd64-hassio-supervisor with version 2022.08.3[0m
2022-09-03 03:11:09 | stderr | [32m22-09-03 11:11:09 INFO (MainThread) [supervisor.bootstrap] Seting up coresys for machine: qemux86-64[0m
2022-09-03 03:11:09 | stderr | [33m22-09-03 11:11:09 WARNING (MainThread) [supervisor.bootstrap] Missing SUPERVISOR_MACHINE environment variable. Fallback to deprecated extraction![0m
2022-09-03 03:11:09 | stderr | [32m22-09-03 03:11:09 INFO (MainThread) [supervisor.bootstrap] Initializing Supervisor Sentry[0m
2022-09-03 03:11:09 | stderr | [32m22-09-03 03:11:09 INFO (MainThread) [__main__] Initializing Supervisor setup[0m
2022-09-03 03:11:09 | stderr | [32m22-09-03 03:11:09 INFO (MainThread) [supervisor.bootstrap] Use the old homeassistant repository for machine extraction[0m
2022-09-03 03:11:08 | stderr | [03:11:08] INFO: [32mStarting local supervisor watchdog...[0m
2022-09-03 03:11:08 | stderr | s6-rc: info: service legacy-services successfully started

</body>
</html>

### What is the used version of the Supervisor?

supervisor-2022.08.3 

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

### What is the version of your installed operating system?

DOCKER of DS918+ 7.9.1-42218 update 5

### What version of Home Assistant Core is installed?

core-2022.8.7

### Steps to reproduce the issue

1.Attempt to update supervisor
2.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
22-09-03 03:33:58 INFO (MainThread) [supervisor.bootstrap] Initializing Supervisor Sentry
22-09-03 11:33:58 WARNING (MainThread) [supervisor.bootstrap] Missing SUPERVISOR_MACHINE environment variable. Fallback to deprecated extraction!
22-09-03 11:33:58 INFO (MainThread) [supervisor.bootstrap] Seting up coresys for machine: qemux86-64
22-09-03 11:33:58 INFO (SyncWorker_0) [supervisor.docker.supervisor] Attaching to Supervisor homeassistant/amd64-hassio-supervisor with version 2022.08.3
22-09-03 11:33:58 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
22-09-03 11:33:58 WARNING (SyncWorker_1) [supervisor.docker.interface] Can't find homeassistant/amd64-hassio-supervisor for cleanup
22-09-03 11:33:58 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.INITIALIZE
22-09-03 11:33:58 WARNING (MainThread) [supervisor.resolution.evaluations.docker_configuration] Docker storage driver btrfs is not supported!
22-09-03 11:33:58 WARNING (MainThread) [supervisor.resolution.evaluations.docker_configuration] Docker logging driver db is not supported!
22-09-03 11:33:58 WARNING (MainThread) [supervisor.resolution.evaluations.base] The configuration of Docker is not supported (more-info: https://www.home-assistant.io/more-info/unsupported/docker_configuration)
22-09-03 11:33:58 WARNING (MainThread) [supervisor.resolution.evaluations.base] Found unsupported job conditions settings. (more-info: https://www.home-assistant.io/more-info/unsupported/job_conditions)
22-09-03 11:33:58 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
22-09-03 11:33:58 ERROR (MainThread) [supervisor.core] Update '2022.08.5' of Supervisor '2022.08.3' failed!
```

**Comment by mdegat01** [comment] 2022-09-03 04:11
Based on the details and the logs you're running an unsupported supervised installation with a number of issues. Which makes it tough to say for certain what went wrong with the upgrade, could be any number of things. I would recommend starting by looking at how you have docker installed based on that log.

Going to close this as its not a bug given its on an unsupported system. Would suggest opening a thread on the [forum](https://community.home-assistant.io/) if you're unsure how to proceed. Or switching to a supported installation method.

**Closed by mdegat01** 2022-09-03 04:11 UTC
Labels: bug, unsupported
