### ISSUE TITLE
Add-on Store does not show install state

### ISSUE THREAD

**Issue by tjorim** [home-assistant/supervisor#3697] opened 2022-06-24 07:30 UTC
### Describe the issue you are experiencing

The store does not show the state of add-ons (introduced in 2022.06.0)

### What is the used version of the Supervisor?

supervisor-2022.06.1

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

8.2

### What version of Home Assistant Core is installed?

core-2022.6.7

### Steps to reproduce the issue

1. Go to Add-on Store
2. Notice no add-ons have the installed tag/color/bar

### Anything in the Supervisor logs that might be useful for us?

```txt
No
```

**Comment by tjorim** [comment] 2022-06-24 07:30
![image](https://user-images.githubusercontent.com/1294876/175485875-369d5a65-884e-47cc-8c7b-90fd4e46ddfb.png)

**Comment by mdegat01** [comment] 2022-06-24 14:41
Duplicate of https://github.com/home-assistant/frontend/issues/12993

Fixed by #3694

**Comment by tjorim** [comment] 2022-06-24 14:59
It's not a duplicate, it's different behaviour: started add-ons vs. installed add-ons not showing. Please re-open as I am on the updated supervisor with the 'fix' you mention.

**Comment by mdegat01** [comment] 2022-06-27 15:01
@tjorim You're right I misunderstood, my bad.

@ludeeus looks like this is a result of #3695 . Frontend needs that field here:
https://github.com/home-assistant/frontend/blob/f611049517269059e37c11c6a46a3fd24abe4ff7/hassio/src/addon-store/hassio-addon-repository.ts#L76

**Closed** 2022-06-27 15:46 UTC
Labels: bug
