### ISSUE TITLE
Upgrading the docker packages results in failing DNS container start

### ISSUE THREAD

**Issue by mmattel** [home-assistant/supervisor#4828] opened 2024-01-20 10:51 UTC
### Describe the issue you are experiencing

Running a Raspberry PI 4 with Bullseye 11 using HA Supervisor and everything Dockerized with compose. Flawless running for a long time.

After upgrading with `sudo apt update` and `sudo apt upgrade` where ONLY the following docker packages were upgraded:
```
sudo less /var/log/apt/history.log
Upgrade on 2024.01.19:
docker-compose-plugin:arm64 (2.21.0-1~debian.11~bullseye, 2.24.1-1~debian.11~bullseye),
docker-ce-cli:arm64 (5:24.0.7-1~debian.11~bullseye, 5:25.0.0-1~debian.11~bullseye),
docker-buildx-plugin:arm64 (0.11.2-1~debian.11~bullseye, 0.12.1-1~debian.11~bullseye),
docker-ce:arm64 (5:24.0.7-1~debian.11~bullseye, 5:25.0.0-1~debian.11~bullseye),
docker-ce-rootless-extras:arm64 (5:24.0.7-1~debian.11~bullseye, 5:25.0.0-1~debian.11~bullseye)
```
the HA supervisor was not longer working. A reboot showed that the `hassio_dns` container failed to start. Removing all HA related containers+images and redeploying them, a usual task for me, showed the same behaviour.

Digging more into the issue it turned out, that after downgrading the packages (reverting the upgrade) to the former state with:
```
sudo apt install \
> docker-compose-plugin=2.21.0-1~debian.11~bullseye \
> docker-ce-cli=5:24.0.7-1~debian.11~bullseye \
> docker-buildx-plugin=0.11.2-1~debian.11~bullseye \
> docker-ce=5:24.0.7-1~debian.11~bullseye \
> docker-ce-rootless-extras=5:24.0.7-1~debian.11~bullseye
```
things were working flawless again.

Makring them on-hold (replace hold --> unhold if the issue has been solved):
```
sudo apt-mark hold \
docker-compose-plugin \
docker-ce-cli \
docker-buildx-plugin \
docker-ce \
docker-ce-rootless-extras
```

Seen too late, related to issue: #4827

### What type of installation are you running?

Home Assistant Supervised: Version 2023.12.1

### Which operating system are you running on?

Raspberry PI 4 with Bullseye 11

### Steps to reproduce the issue

Updating the docker packages as provided by the OS to the failing versions, see above.

### Anything in the Supervisor logs that might be useful for us?

These are the logs I gathered related to the issue:

**Supervisor**
```
24-01-20 10:49:35 ERROR (SyncWorker_0) [supervisor.docker.network] Can't link container to hassio-net: 500 Server Error for http+docker://localhost/v1.44/networks/6fd0056995cf122d94aedff99317209ac3300b4e5d417f3a3d0c7a63f7f4f158/connect: Internal Server Error ("invalid endpoint settings:
no configured subnet or ip-range contain the IP address 172.30.32.5")
```

**DNS**
```
[FATAL] plugin/loop: Loop (127.0.0.1:49294 -> :53) detected for zone ".", see https://coredns.io/plugins/loop#troubleshooting. Query: "HINFO 8909671670323975647.385028216040430990."

24-01-20 10:52:27 INFO (MainThread) [supervisor.docker.dns] Starting DNS ghcr.io/home-assistant/aarch64-hassio-dns with version 2023.06.2 - 172.30.32.3

24-01-20 10:52:37 ERROR (MainThread) [supervisor.plugins.dns] Detected a DNS loop in local Network!
```

**Comment by ghtester** [comment] 2024-01-22 21:41
Thanks for opening the issue & details provided. The same issue happens on (unsupported) Ubuntu 22.04.

**Comment by gabrielhopkins** [comment] 2024-01-22 22:40
Thanks @mmattel for the write up - I would never have figured out how to revert the docker and work around the issue

**Comment by justintrann** [comment] 2024-01-23 10:08
I wish i checked Github issues sooner. I decided to reinstall my Linux Mint for this thing🥲

**Comment by amdoolittle** [comment] 2024-01-23 23:23
Thank you for that @mmattel, I just ran into this today.  I appreciate the writeup!

**Comment by mdegat01** [comment] 2024-01-24 01:25
Duplicate of #4827

**Closed by mdegat01** 2024-01-24 01:25 UTC
Labels: bug, unsupported

**Comment by bnowakow** [comment] 2024-01-24 13:42
@arboeh it's fixed with docker 25.0.1

**Comment by arboeh** [comment] 2024-01-24 14:13
> @arboeh it's fixed with docker 25.0.1

Noticed it and confirm that it works. Thanks.

**Comment by thoompje** [comment] 2024-01-25 15:05
It's working after the upgrade, but my icons are not loading under de integrations section. Also in the addon Kuma I cannot ping my gateway of my ISP anymore. So I will downgrade back again.

**Comment by mmattel** [comment] 2024-01-25 16:12
Note, at the time of writing (2024.01.25) Debial Bullseye has no updated packages:
`sudo apt-cache policy docker-ce-cli`
Still on 25.0.0

**Comment by erdosip** [comment] 2024-01-25 16:35
Isn't they just published?
```
[fazy(MoPeHOME:2)] <~> apt info docker-ce
Package: docker-ce
Version: 5:25.0.1-1~debian.11~bullseye
Priority: optional
Section: admin
Maintainer: Docker <support@docker.com>
Installed-Size: 104 MB
Depends: containerd.io (>= 1.6.24), docker-ce-cli, iptables, libseccomp2 (>= 2.3.0), libc6 (>= 2.14), libsystemd0
Recommends: apparmor, ca-certificates, docker-ce-rootless-extras, git, libltdl7, pigz, procps, xz-utils
Suggests: aufs-tools, cgroupfs-mount | cgroup-lite
Conflicts: docker (<< 1.5~), docker-engine, docker-engine-cs, docker.io, lxc-docker, lxc-docker-virtual-package
Replaces: docker-engine
Homepage: https://www.docker.com
Download-Size: 24,3 MB
```
I'm still waiting with the update, but if someone can confirm that is working, I would be glad!

**Comment by erdosip** [comment] 2024-02-02 03:10
I'm done waiting, and did the upgrade (with a snapshot of my HA VM, as usual :) ) and now it's working fine.

**Comment by mmattel** [comment] 2024-02-06 09:39
Updated today to `25.0.2` - works
