### ISSUE TITLE
Add On Store Repository Error

### ISSUE THREAD

**Issue by echellst** [home-assistant/supervisor#2899] opened 2021-05-19 02:42 UTC
### Describe the issue you are experiencing

Hello, 

After the last supervisor update (2021.04.3), I can no longer add any repositories to my Add-on store. And in fact, the Community Add repository will not load either. The only repository's I have left are theses:
![image](https://user-images.githubusercontent.com/73681025/118748041-5c2b4e80-b818-11eb-81d8-252ec52d12f4.png)

If you try to add anything else, it errors out and is listed as "Unknown". Here is the Supervisor log showing errors on startup:
21-05-19 02:22:47 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
21-05-19 02:22:47 INFO (MainThread) [supervisor.resolution.fixups.store_execute_remove] Remove invalid Store: core
21-05-19 02:22:47 ERROR (MainThread) [supervisor.store.repository] Can't remove built-in repositories!
21-05-19 02:22:47 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
21-05-19 02:22:51 INFO (MainThread) [supervisor.store.git] Cloning add-on https://github.com/home-assistant/hassio-addons-example repository
21-05-19 02:22:56 ERROR (MainThread) [supervisor.store.git] Can't clone https://github.com/home-assistant/hassio-addons-example repository: Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v --recursive --depth=1 --shallow-submodules --progress https://github.com/home-assistant/hassio-addons-example /data/addons/git/c2eea46b.
21-05-19 02:22:56 ERROR (MainThread) [supervisor.store] Can't load data from repository https://github.com/home-assistant/hassio-addons-example
21-05-19 02:22:57 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'startup' with 'before' is deprecated. Please report this to the maintainer of OpenWRT
21-05-19 02:22:57 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'startup' with 'before' is deprecated. Please report this to the maintainer of RTL_433 to MQTT Bridge
21-05-19 02:22:57 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'devices' use a deprecated format, the new format uses a list of paths only. Please report this to the maintainer of RTL_433 to MQTT Bridge
21-05-19 02:22:57 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'startup' with 'before' is deprecated. Please report this to the maintainer of IPFire
21-05-19 02:22:57 ERROR (MainThread) [supervisor.utils.json] Can't read json from /data/addons/git/a6b98bcd/fail2ban/config.json: Expecting value: line 2 column 1 (char 1)
21-05-19 02:22:57 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/git/a6b98bcd/fail2ban/config.json from repository a6b98bcd
21-05-19 02:22:57 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'startup' with 'before' is deprecated. Please report this to the maintainer of HASS AP
21-05-19 02:22:57 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of Kegbot
21-05-19 02:22:57 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'startup' with 'before' is deprecated. Please report this to the maintainer of Z-Way Server
21-05-19 02:22:57 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of Z-Way Server
21-05-19 02:22:57 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'startup' with 'before' is deprecated. Please report this to the maintainer of sendmail
21-05-19 02:22:57 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'startup' with 'before' is deprecated. Please report this to the maintainer of FFF-API
21-05-19 02:22:57 INFO (MainThread) [supervisor.store] Loading add-ons from store: 12 all - 0 new - 0 remove
21-05-19 02:22:57 INFO (MainThread) [supervisor.resolution.fixups.store_execute_remove] Remove invalid Store: core
21-05-19 02:22:57 ERROR (MainThread) [supervisor.store.repository] Can't remove built-in repositories!

Any idea as to what may have happened and how to fix it? I would like to load ESPHome, but cannot get to the repository.

Thanks!
Eric

### What is the used version of the Supervisor?

2021.04.3

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

5.13

### What version of Home Assistant Core is installed?

2021.5.4

### Steps to reproduce the issue

1. Open the Add-On Store
2. Select "Repositories" from the Hamburger menu in the top right.
3. in the "Add" space, insert "https://github.com/hassio-addons/repository"
4. Click the "ADD" button to the immediate right.
5. Wait for the error "Invalid Add-on repository!"
6. Hit close, then re-select "Repository"
7. You can now see the repository you just added (The error indicated it was invalid..) but now it appears as "Unknown"

![image](https://user-images.githubusercontent.com/73681025/118748715-7285da00-b819-11eb-90e2-7096e0feaf0b.png)

...Thanks!

### Anything in the Supervisor logs that might be useful for us?

```txt
21-05-19 02:22:47 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
21-05-19 02:22:47 INFO (MainThread) [supervisor.resolution.fixups.store_execute_remove] Remove invalid Store: core
21-05-19 02:22:47 ERROR (MainThread) [supervisor.store.repository] Can't remove built-in repositories!
21-05-19 02:22:47 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
21-05-19 02:22:51 INFO (MainThread) [supervisor.store.git] Cloning add-on https://github.com/home-assistant/hassio-addons-example repository
21-05-19 02:22:56 ERROR (MainThread) [supervisor.store.git] Can't clone https://github.com/home-assistant/hassio-addons-example repository: Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v --recursive --depth=1 --shallow-submodules --progress https://github.com/home-assistant/hassio-addons-example /data/addons/git/c2eea46b.
21-05-19 02:22:56 ERROR (MainThread) [supervisor.store] Can't load data from repository https://github.com/home-assistant/hassio-addons-example
21-05-19 02:22:57 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'startup' with 'before' is deprecated. Please report this to the maintainer of OpenWRT
21-05-19 02:22:57 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'startup' with 'before' is deprecated. Please report this to the maintainer of RTL_433 to MQTT Bridge
21-05-19 02:22:57 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'devices' use a deprecated format, the new format uses a list of paths only. Please report this to the maintainer of RTL_433 to MQTT Bridge
21-05-19 02:22:57 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'startup' with 'before' is deprecated. Please report this to the maintainer of IPFire
21-05-19 02:22:57 ERROR (MainThread) [supervisor.utils.json] Can't read json from /data/addons/git/a6b98bcd/fail2ban/config.json: Expecting value: line 2 column 1 (char 1)
21-05-19 02:22:57 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/git/a6b98bcd/fail2ban/config.json from repository a6b98bcd
21-05-19 02:22:57 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'startup' with 'before' is deprecated. Please report this to the maintainer of HASS AP
21-05-19 02:22:57 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of Kegbot
21-05-19 02:22:57 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'startup' with 'before' is deprecated. Please report this to the maintainer of Z-Way Server
21-05-19 02:22:57 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of Z-Way Server
21-05-19 02:22:57 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'startup' with 'before' is deprecated. Please report this to the maintainer of sendmail
21-05-19 02:22:57 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'startup' with 'before' is deprecated. Please report this to the maintainer of FFF-API
21-05-19 02:22:57 INFO (MainThread) [supervisor.store] Loading add-ons from store: 12 all - 0 new - 0 remove
21-05-19 02:22:57 INFO (MainThread) [supervisor.resolution.fixups.store_execute_remove] Remove invalid Store: core
21-05-19 02:22:57 ERROR (MainThread) [supervisor.store.repository] Can't remove built-in repositories!
```

**Comment by pvizeli** [comment] 2021-05-25 12:22
Duplicate of: https://github.com/home-assistant/supervisor/issues/2774

**Closed by pvizeli** 2021-05-25 12:22 UTC
Labels: bug

**Comment by jspanitz** [comment] 2021-06-11 01:55
But 2774 is already closed and this issue still exists.
