### ISSUE TITLE
CPU and RAM usage not refreshing

### ISSUE THREAD

**Issue by Tryfos** [home-assistant/supervisor#3275] opened 2021-10-30 11:50 UTC
### Describe the issue you are experiencing

After an upgrade to the latest Supervisor, CPU and RAM usage is again not shown properly. It seems that only one measurement is taken upon opening of the page and then it is not refreshed accordingly. The value shown is stuck in the initial state, so it is not “live” according to the actual CPU and RAM usage.
I had already added cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1 systemd.unified_cgroup_hierarchy=false systemd.legacy_systemd_cgroup_controller=false in the cmdline.txt of my Pi4 to disable cgroup v2 and it worked ok in previous versions. I tried to remove/add some of the above attributes in the cmdline but the situation persists. cat /proc/cgroups shows both cpu and ram as enabled. Stats are shown ok and live through Portainer. This has to do with an upgrade of Supervisor (or OS-agent?).

### What is the used version of the Supervisor?

supervisor-2021.10.6

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Debian

### What is the version of your installed operating system?

11

### What version of Home Assistant Core is installed?

core-2021.10.6

### Steps to reproduce the issue

1. Visit Supervisor UI
2. Go to System tab
3. Observe RAM/CPU usage

### Anything in the Supervisor logs that might be useful for us?

```txt
No
```

**Comment by ludeeus** [comment] 2021-10-31 13:18
They are not refreshing, they are only requested on page open, that's how it was implemented.

Closing as this is the intended behaviour, feel free to open a feature request on the forums to have that change 👍

**Closed** 2021-10-31 13:18 UTC
Labels: bug
