### ISSUE TITLE
Supervisor errors on the newly installed system

### ISSUE THREAD

**Issue by VikeDragon** [home-assistant/supervisor#3573] opened 2022-04-15 05:51 UTC
### Describe the issue you are experiencing

I had to reinstall the system and now I noticed errors that are already being issued on the newly installed system after the first login. That is, the system is in its initial state without my data from the backup. At the same time, the Supervisor version is old - 2022.4.0, although there is already 2022.4.2. The latest kernel version is 2022.4.4. How is that?
...
22-04-15 09:46:48 ERROR (MainThread) [supervisor.store.git] Can't clone https://github.com/hassio-addons/repository repository: Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v --recursive --depth=1 --shallow-submodules https://github.com/hassio-addons/repository /data/addons/git/a0d7b954
  stderr: 'Cloning into '/data/addons/git/a0d7b954'...
POST git-upload-pack (175 bytes)
POST git-upload-pack (244 bytes)
fatal: error reading section header 'shallow-info'
'.
22-04-15 09:46:48 INFO (MainThread) [supervisor.resolution.module] Create new issue IssueType.FATAL_ERROR - ContextType.STORE / a0d7b954
22-04-15 09:46:48 INFO (MainThread) [supervisor.resolution.module] Create new suggestion SuggestionType.EXECUTE_REMOVE - ContextType.STORE / a0d7b954
22-04-15 09:46:48 ERROR (MainThread) [supervisor.store] Can't load data from repository https://github.com/hassio-addons/repository
...
22-04-15 09:46:48 ERROR (MainThread) [supervisor.utils] Can't execute check_trust while a task is in progress

### What is the used version of the Supervisor?

supervisor-2022.04.0

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Debian

### What is the version of your installed operating system?

5.15.33-v8+

### What version of Home Assistant Core is installed?

core-2022.4.4

### Steps to reproduce the issue

Fresh reinstall system

### Anything in the Supervisor logs that might be useful for us?

```txt
...
22-04-15 09:46:48 ERROR (MainThread) [supervisor.store.git] Can't clone https://github.com/hassio-addons/repository repository: Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v --recursive --depth=1 --shallow-submodules https://github.com/hassio-addons/repository /data/addons/git/a0d7b954
  stderr: 'Cloning into '/data/addons/git/a0d7b954'...
POST git-upload-pack (175 bytes)
POST git-upload-pack (244 bytes)
fatal: error reading section header 'shallow-info'
'.
22-04-15 09:46:48 INFO (MainThread) [supervisor.resolution.module] Create new issue IssueType.FATAL_ERROR - ContextType.STORE / a0d7b954
22-04-15 09:46:48 INFO (MainThread) [supervisor.resolution.module] Create new suggestion SuggestionType.EXECUTE_REMOVE - ContextType.STORE / a0d7b954
22-04-15 09:46:48 ERROR (MainThread) [supervisor.store] Can't load data from repository https://github.com/hassio-addons/repository
...
22-04-15 09:46:48 ERROR (MainThread) [supervisor.utils] Can't execute check_trust while a task is in progress
```

### Additional information

The Supervisor 2022.4.0 is not updated. Is there any way to update it forcibly?

**Comment by sdotter** [comment] 2022-04-15 08:31
Same on my system (supervised)

core-2022.4.4
supervisor-2022.04.0
Debian GNU/Linux 11 (bullseye)
Docker 20.10.12

**Comment by sdotter** [comment] 2022-04-15 08:37
Same as #3575 ?

**Comment by VikeDragon** [comment] 2022-04-15 10:09
same problem in https://github.com/home-assistant/supervisor/issues/3561#issue-1200537614

**Comment by mdegat01** [comment] 2022-04-15 13:10
Duplicate of #3561

**Closed by mdegat01** 2022-04-15 13:10 UTC
Labels: bug
