### ISSUE TITLE
Docker Rate Limit Exceeded During Home Assistant Supervisor Update (500 Server Error)

### ISSUE THREAD

**Issue by cloudbr34k84** [home-assistant/supervisor#5406] opened 2024-11-11 09:00 UTC
### Describe the issue you are experiencing

Encountered a 500 Server Error when attempting to update Home Assistant Supervisor. The error message indicates that the Docker rate limit has been exceeded:
```
Error updating Home Assistant Supervisor: Update of Supervisor failed: Can't install ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3: 500 Server Error for http+docker://localhost/v1.47/images/create?tag=2024.11.3&fromImage=ghcr.io%2Fhome-assistant%2Famd64-hassio-supervisor&platform=linux%2Famd64: Internal Server Error ("toomanyrequests: retry-after: 17.225µs, allowed: 44000/minute")
```

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

Attempt to update the Home Assistant Supervisor via the UI or CLI.
Observe the 500 Server Error with a "toomanyrequests" message, indicating Docker Hub rate limits have been exceeded.

### Anything in the Supervisor logs that might be useful for us?

```txt
2024-11-11 18:47:13.954 ERROR (MainThread) [supervisor.supervisor] Update of Supervisor failed: Can't install ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3: 404 Client Error for http+docker://localhost/v1.47/images/ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3/json: Not Found ("No such image: ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3")
```
```


### System Health information

## System Information

version | core-2024.11.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.54-haos
arch | x86_64
timezone | Australia/Brisbane
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 5000
Installed Version | 2.0.1
Stage | running
Available Repositories | 1466
Downloaded Repositories | 40

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 4 July 2025 at 10:00
relayer_connected | true
relayer_region | ap-southeast-1
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | false
cloud_ice_servers_enabled | true
remote_server | ap-southeast-1-0.ui.nabu.casa
certificate_status | ready
instance_id | d85a8f57298b4d29992f380cca82e572
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 13.2
-- | --
update_channel | stable
supervisor_version | supervisor-2024.11.2
agent_version | 1.6.0
docker_version | 27.2.0
disk_total | 40.6 GB
disk_used | 30.6 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | kvm
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Node-RED (18.1.1), Mosquitto broker (6.4.1), ESPHome (2024.10.3), Glances (0.21.1), Studio Code Server (5.17.3), Home Assistant Google Drive Backup (0.112.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 7
-- | --
resources | 17
views | 70
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 10 November 2024 at 05:45
-- | --
current_recorder_run | 11 November 2024 at 10:17
estimated_db_size | 2543.34 MiB
database_engine | postgresql
database_version | 17.0

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Supervisor diagnostics

[config_entry-hassio-01JB3ARC0RV3YGF069MFX584T4.json](https://github.com/user-attachments/files/17699804/config_entry-hassio-01JB3ARC0RV3YGF069MFX584T4.json)


### Additional information

_No response_

**Comment by swingstate** [comment] 2024-11-11 09:05
can confirm this, same here tried to go from 2024.11.2 to 11.3.

**Comment by kgbvax** [comment] 2024-11-11 09:12
Saw that as well. 
Then, when it passed I get this:
Failed to perform the action update/install. Error updating Home Assistant Supervisor: Update of Supervisor failed: Can't install ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3: 404 Client Error for http+docker://localhost/v1.47/images/ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3/json: Not Found ("No such image: ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3")

**Comment by Ro22Ro22** [comment] 2024-11-11 09:17
> Saw that as well. Then, when it passed I get this: Failed to perform the action update/install. Error updating Home Assistant Supervisor: Update of Supervisor failed: Can't install ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3: 404 Client Error for http+docker://localhost/v1.47/images/ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3/json: Not Found ("No such image: ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3")

I have this same 'Image not found error too'

**Comment by harvey0100** [comment] 2024-11-11 09:19
Can confirm also getting this error.

Failed to perform the action update/install. Error updating Home Assistant Supervisor: Update of Supervisor failed: Can't install ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3: 404 Client Error for http+docker://localhost/v1.47/images/ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3/json: Not Found ("No such image: ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3")

**Comment by observer-october** [comment] 2024-11-11 09:20
Same here:
Error updating Home Assistant Supervisor: Update of Supervisor failed: Can't install ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3: 500 Server Error for http+docker://localhost/v1.47/images/create?tag=2024.11.3&fromImage=ghcr.io%2Fhome-assistant%2Famd64-hassio-supervisor&platform=linux%2Famd64: Internal Server Error ("toomanyrequests: retry-after: 173.3µs, allowed: 44000/minute")

**Comment by ABEIDO** [comment] 2024-11-11 09:21
Im getting rate limited i guess after to many tries. 

- Tested to start i manually as well with ha supervisor update but same issue.
- Tested on my HA test machine and it had an error message aswell but after ha supervisor update it worked. 
- But it didnt work on my actual HA machine and still have the issue there.

Error
> 
homeassistant.exceptions.HomeAssistantError: Error updating Home Assistant Supervisor: Update of Supervisor failed: Can't install ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3: 500 Server Error for http+docker://localhost/v1.47/images/create?tag=2024.11.3&fromImage=ghcr.io%2Fhome-assistant%2Famd64-hassio-supervisor&platform=linux%2Famd64: Internal Server Error ("toomanyrequests: retry-after: 1.249611ms, allowed: 44000/minute")

**Comment by NunoPerdigao** [comment] 2024-11-11 09:34
same
2024-11-11 09:28:47.737 ERROR (MainThread) [supervisor.docker.interface] Can't install ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3: 404 Client Error for http+docker://localhost/v1.47/images/ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3/json: Not Found ("No such image: ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3")
2024-11-11 09:28:47.738 ERROR (MainThread) [supervisor.supervisor] Update of Supervisor failed: Can't install ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3: 404 Client Error for http+docker://localhost/v1.47/images/ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3/json: Not Found ("No such image: ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3")

**Comment by TorstenHamper** [comment] 2024-11-11 09:35
+1
same error message like all above.

**Comment by billmaterial** [comment] 2024-11-11 09:37
Same here

**Comment by sdotter** [comment] 2024-11-11 09:39
Same here

`Actie update/install kon niet worden uitgevoerd. Error updating Home Assistant Supervisor: Update of Supervisor failed: Can't install ghcr.io/home-assistant/aarch64-hassio-supervisor:2024.11.3: 404 Client Error for http+docker://localhost/v1.46/images/ghcr.io/home-assistant/aarch64-hassio-supervisor:2024.11.3/json: Not Found ("No such image: ghcr.io/home-assistant/aarch64-hassio-supervisor:2024.11.3")`

**Comment by zzpenguin** [comment] 2024-11-11 09:42
Same error here

**Comment by roalvesrj** [comment] 2024-11-11 09:51
Same.

 Error updating Home Assistant Supervisor: Update of Supervisor failed: Can't install ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3: 500 Server Error for http+docker://localhost/v1.47/images/create?tag=2024.11.3&fromImage=ghcr.io%2Fhome-assistant%2Famd64-hassio-supervisor&platform=linux%2Famd64: Internal Server Error ("toomanyrequests: retry-after: 673.413µs, allowed: 44000/minute")

**Comment by EH-TimBird** [comment] 2024-11-11 09:55
Same error here too.

**Comment by qmegas** [comment] 2024-11-11 10:00
Seems like everyone have that issue.

**Comment by pctelco** [comment] 2024-11-11 10:03
> Seems like everyone have that issue.

Yes, here to.

**Comment by Eoras** [comment] 2024-11-11 10:05
Same

**Comment by kriziw** [comment] 2024-11-11 10:07
Same here

**Comment by Germi79** [comment] 2024-11-11 10:10
same

**Comment by sdotter** [comment] 2024-11-11 10:13
Ok, please stop adding "Same" etc

Just give thumbs up to first post 👍☝️
That keeps github from spamming my mailbox with "same, same, same" 😂

**Comment by wouterrutgers** [comment] 2024-11-11 10:13
Instead of commenting "same," please just give a thumbs up on the main post. This keeps the discussion focused and makes it easier to find useful comments.

**Comment by Xitee1** [comment] 2024-11-11 10:13
Same here, wanted to install an Addon, HA wanted me to update the Supervisor first which does not work.
Can we somehow just skip the update or disable automatic updates completely? It has already broke my HA (logs for addons) because I haven't updated Core to 2024.11 yet.

**Comment by mrlulu51** [comment] 2024-11-11 10:14
I tried to manually pull the supervisor update and it gave me this error:
`Error response from daemon: toomanyrequests: retry-after: 152.945µs, allowed: 44000/minute`

**Comment by nturbin** [comment] 2024-11-11 10:16
Too many attenpts @mrlulu51  Just wait and retry. But it's not usefull because the problem is not solved yet.

**Comment by 4webat** [comment] 2024-11-11 10:20
Same Error here

**Comment by Jon811** [comment] 2024-11-11 10:21
Same here:
2024-11-11 12:45:06.852 ERROR (MainThread) [supervisor.supervisor] Update of Supervisor failed: Can't install ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3: 500 Server Error for http+docker://localhost/v1.46/images/create?tag=2024.11.3&fromImage=ghcr.io%2Fhome-assistant%2Famd64-hassio-supervisor&platform=linux%2Famd64: Internal Server Error ("toomanyrequests: retry-after: 927.18µs, allowed: 44000/minute")
2024-11-11 12:45:06.852 CRITICAL (MainThread) [supervisor.core] Can't update Supervisor! This will break some Add-ons or affect future versions of Home Assistant!

**Comment by Xitee1** [comment] 2024-11-11 10:29
Why downvote literally any comment here?
I understand the annoying "same" ones that do not add anything useful to this thread but here are some normal comments in between that in my opinion should not get downvoted.
If you don't want any notifications about this issue, then just unsubscribe.

**Comment by novotechsoftware** [comment] 2024-11-11 10:31
I know there's a but but can I just reload a newer image from Home Assistant and it will work? I would say the answer is now and I have to wait but trying my luck

**Comment by adekloet** [comment] 2024-11-11 10:32
My guess is that the server(s) which has the image is overloaded, all our instances requesting the supervisor updates is causing the somehow impaired load balancing (cdn?) at the server side to rate limit on request, but just a hunge.

**Comment by GeoffMorg** [comment] 2024-11-11 10:37
I suspect the image is somehow bad. Has anyone managed to do this OK?

(On reflection, if anyone has then they probably wouldn't make it here LOL)

**Comment by ardyp87** [comment] 2024-11-11 10:46
same here!

**Comment by kgbvax** [comment] 2024-11-11 10:49
>Has anyone managed to do this OK?
If the request goes through, there is a 404, see my previous comment. 
IMHO The image is not there.

**Comment by FloSeidel** [comment] 2024-11-11 10:50
duplicate of https://github.com/home-assistant/supervisor/issues/5405 ?

**Comment by Xitee1** [comment] 2024-11-11 11:00
I managed to update the supervisor manually by spamming the docker pull command in the console until it fully went through:
`docker pull ghcr.io/home-assistant/aarch64-hassio-supervisor:2024.11.3`
After that `ha supervisor update` and I have successfully updated now.

**Comment by vacari** [comment] 2024-11-11 11:01
Same Here:

Failed to perform the action update/install. Error updating Home Assistant Supervisor: Update of Supervisor failed: Can't install ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3: 404 Client Error for http+docker://localhost/v1.47/images/ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3/json: Not Found ("No such image: ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3")

**Comment by sugar012** [comment] 2024-11-11 11:10
> docker pull ghcr.io/home-assistant/aarch64-hassio-supervisor:2024.11.3

i'm sorry but what console? do you have HA Core ? on my system i can't 
![image](https://github.com/user-attachments/assets/f430ce3a-a08d-46cb-8666-3430c0be4ebd)

**Comment by josecarre** [comment] 2024-11-11 11:11
I assume we're hitting tome rate limit in github side? it could be as seen in https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api
Let's see if in some hours the bottle neck gets cleared :)

**Comment by bernardesarthur** [comment] 2024-11-11 11:13
> I've managed to update the supervisor manually by spamming the docker pull command in the console until it fully went through:
> 
> `docker pull ghcr.io/home-assistant/aarch64-hassio-supervisor:2024.11.3`
> 
> After that run `ha supervisor update` and the update was successful.
> 
> 
> 
> Make sure to pull the correct image (architecture).
> 
> I don't know why this worked because the actual problem was a 404 but maybe it's fixed now.

I tryed to do this, but when I run docker pull I received that message: Error response from daemon: toomanyrequests: retry-after: 450.193µs, allowed: 44000/minute

**Comment by joost11111** [comment] 2024-11-11 11:16
Same
![Capture](https://github.com/user-attachments/assets/c506895d-50c0-4b8a-bd9b-a6f540bda411)

**Comment by MelchMwoan** [comment] 2024-11-11 11:22
> > I've managed to update the supervisor manually by spamming the docker pull command in the console until it fully went through:
> > `docker pull ghcr.io/home-assistant/aarch64-hassio-supervisor:2024.11.3`
> > After that run `ha supervisor update` and the update was successful.
> > Make sure to pull the correct image (architecture).
> > I don't know why this worked because the actual problem was a 404 but maybe it's fixed now.
> 
> I tryed to do this, but when I run docker pull I received that message: Error response from daemon: toomanyrequests: retry-after: 450.193µs, allowed: 44000/minute

It does work, but you need to keep spamming it. Every time it manages to get through for about half a second, download parts of the images and timeout, but those parts are kept in your systems cache. So piece by piece you will eventually end up with the entire image, and then you can just run `ha supervisor update`

Halfway it will look something like this:
![image](https://github.com/user-attachments/assets/e40f5276-6289-4b80-823c-fd262cc33bf7)


Eventually it will be a complete image:
![image](https://github.com/user-attachments/assets/fb060314-a6e1-434d-854f-0b44a7894533)

**Comment by manilx** [comment] 2024-11-11 11:25
This does not work for home assistant OS. Can't run Docker command

**Comment by erykosky** [comment] 2024-11-11 11:30
Too many users are attempting to pull the image simultaneously, causing rate limits to be exceeded. Perhaps introducing a 2-minute break between requests would help alleviate the issue and allow others to complete their downloads.

**Comment by mihaimdinca** [comment] 2024-11-11 11:47
Same error. Also present if trying a fresh install of HAOS - setup does not complete.

**Comment by hlavij** [comment] 2024-11-11 11:49
Hello,
I have the same issue. I have tried update from GUI and also from HAOS CLI, the same results:
I am running HAOS in Hyper-V.

![Screenshot 2024-11-11 124447](https://github.com/user-attachments/assets/ffa7d93a-65ab-43dc-9369-d13d07055b98)

**Comment by mikeleord** [comment] 2024-11-11 12:07
same issue
Failed to perform the action update/install. Error updating Home Assistant Supervisor: Update of Supervisor failed: Can't install ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3: 404 Client Error for http+docker://localhost/v1.47/images/ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3/json: Not Found ("No such image: ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3")

docker pull ghcr.io/home-assistant/aarch64-hassio-supervisor:2024.11.3
Error response from daemon: toomanyrequests: retry-after: 340.729µs, allowed: 44000/minute

**Comment by h-svab** [comment] 2024-11-11 12:13
Happens even during first start after a brand new OVA image based new VM.

**Comment by Xitee1** [comment] 2024-11-11 12:13
> This does not work for home assistant OS. Can't run Docker command

It does work on HA OS but you need the advanced console. I have OS myself.

**Comment by metbril** [comment] 2024-11-11 12:18
Duplicate of #5405 ?!
![image](https://github.com/user-attachments/assets/7e3cbc5d-be6b-4446-88b1-fcbd1c2b1736)

**Comment by ziceva** [comment] 2024-11-11 12:31
Spamming the _docker pull_ command seems to have better chances to succeed (it still takes many tries) with "max-concurrent-connections" set to "1" for dockerd ... Unfortunately, changing this setting is not straightforward: I just copied /etc/docker/daemon.json to a temp folder (and changed the settings as required) and then bind-mounted the temp folder back to /etc/docker/ and killed dockerd, to have the new settings activated ...

**Comment by GerryCrooked** [comment] 2024-11-11 12:35
> Spamming the _docker pull_ command seems to have better chances to succeed (it still takes many tries) with "max-concurrent-downloads" set to "1" for dockerd ... Unfortunately, changing this setting is not straightforward: I just copied /etc/docker/daemon.json to a temp folder (and changed the settings as required) and then bind-mounted the temp folder back to /etc/docker/ and killed dockerd, to have the new settings activated [and then _ha supervisor update_ and then a system reboot to have everything start again as normal ... killing dockerd is the riskiest step (data corruption-wise)]...

spamming in CLI (VM) did work as well now

**Comment by agners** [comment] 2024-11-11 12:49
Duplicate of #5405, so closing.

**Closed by agners** 2024-11-11 12:49 UTC
Labels: bug, duplicate

**Comment by mkali67** [comment] 2024-11-11 14:03
I just executed the "ha supervisor update" command without spamming Docker and... "Processing... Done. Command completed successfully." 😃
