### ISSUE TITLE
Unable to update to 2023.11.1 from 2023.10.5

### ISSUE THREAD

**Issue by pove** [home-assistant/supervisor#4670] opened 2023-11-05 19:34 UTC
### Describe the issue you are experiencing

I am unable to update to 2023.11.1 from 2023.10.5

[31m23-11-05 19:48:19 ERROR (MainThread) [supervisor.homeassistant.core] No API response in 5 minutes, assuming core has had a fatal startup error[0m
[31m23-11-05 19:48:19 CRITICAL (MainThread) [supervisor.homeassistant.core] HomeAssistant update failed -> rollback![0m
[32m23-11-05 19:48:19 INFO (MainThread) [supervisor.resolution.module] Create new issue update_rollback - core / None[0m
[32m23-11-05 19:48:19 INFO (MainThread) [supervisor.homeassistant.core] A backup of the logfile is stored in /config/home-assistant-rollback.log[0m
[32m23-11-05 19:48:19 INFO (MainThread) [supervisor.homeassistant.core] Updating Home Assistant to version 2023.10.5[0m
[32m23-11-05 19:48:19 INFO (MainThread) [supervisor.docker.interface] Updating image ghcr.io/home-assistant/raspberrypi4-64-homeassistant:2023.11.1 to ghcr.io/home-assistant/raspberrypi4-64-homeassistant:2023.10.5[0m
[32m23-11-05 19:48:19 INFO (MainThread) [supervisor.docker.interface] Downloading docker image ghcr.io/home-assistant/raspberrypi4-64-homeassistant with tag 2023.10.5.[0m

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1. Be on 2023.10.5
2. Try to update to 2023.11.1

### Anything in the Supervisor logs that might be useful for us?

```txt
[31m23-11-05 19:41:08 ERROR (MainThread) [supervisor.homeassistant.api] Error on call http://172.30.32.1:8123/api/core/state: [0m
[32m23-11-05 19:41:42 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance[0m
[32m23-11-05 19:41:42 INFO (MainThread) [supervisor.addons] Phase 'application' starting 6 add-ons[0m
[32m23-11-05 19:41:43 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on homeassistant/aarch64-addon-nginx_proxy with version 3.5.0[0m
[32m23-11-05 19:41:44 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on homeassistant/aarch64-addon-configurator with version 5.6.0[0m
[32m23-11-05 19:41:46 INFO (MainThread) [supervisor.api.middleware.security] /core/info access from core_nginx_proxy[0m
[32m23-11-05 19:41:46 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on ghcr.io/hassio-addons/appdaemon/aarch64 with version 0.14.0[0m
[32m23-11-05 19:41:48 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on zigbee2mqtt/zigbee2mqtt-aarch64 with version 1.33.2-1[0m
[32m23-11-05 19:41:50 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on ghcr.io/hassio-addons/wireguard/aarch64 with version 0.9.0[0m
[32m23-11-05 19:41:51 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on ghcr.io/esphome/esphome-hassio with version 2023.10.5[0m
[32m23-11-05 19:42:14 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize[0m
[32m23-11-05 19:42:14 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_appdaemon[0m
[32m23-11-05 19:42:14 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running[0m
[32m23-11-05 19:42:15 INFO (MainThread) [supervisor.misc.tasks] All core tasks are scheduled[0m
[32m23-11-05 19:42:15 INFO (MainThread) [supervisor.core] Supervisor is up and running[0m
[32m23-11-05 19:42:15 INFO (MainThread) [supervisor.host.info] Updating local host information[0m
[32m23-11-05 19:42:15 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json[0m
[32m23-11-05 19:42:15 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state running[0m
[32m23-11-05 19:42:15 INFO (MainThread) [supervisor.resolution.checks.base] Run check for dns_server_failed/dns_server[0m
[32m23-11-05 19:42:15 INFO (MainThread) [supervisor.resolution.checks.base] Run check for security/core[0m
[32m23-11-05 19:42:15 INFO (MainThread) [supervisor.resolution.checks.base] Run check for free_space/system[0m
[32m23-11-05 19:42:15 INFO (MainThread) [supervisor.resolution.checks.base] Run check for ipv4_connection_problem/system[0m
[32m23-11-05 19:42:15 INFO (MainThread) [supervisor.resolution.checks.base] Run check for docker_config/system[0m
[32m23-11-05 19:42:15 INFO (MainThread) [supervisor.resolution.checks.base] Run check for pwned/addon[0m
[32m23-11-05 19:42:17 INFO (MainThread) [supervisor.host.services] Updating service information[0m
[32m23-11-05 19:42:17 INFO (MainThread) [supervisor.host.network] Updating local network information[0m
[32m23-11-05 19:42:18 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information[0m
[32m23-11-05 19:42:18 INFO (MainThread) [supervisor.host.manager] Host information reload completed[0m
[32m23-11-05 19:42:18 INFO (MainThread) [supervisor.resolution.checks.base] Run check for no_current_backup/system[0m
[32m23-11-05 19:42:18 INFO (MainThread) [supervisor.resolution.module] Create new suggestion create_full_backup - system / None[0m
[32m23-11-05 19:42:18 INFO (MainThread) [supervisor.resolution.module] Create new issue no_current_backup - system / None[0m
[32m23-11-05 19:42:18 INFO (MainThread) [supervisor.resolution.checks.base] Run check for multiple_data_disks/system[0m
[32m23-11-05 19:42:18 INFO (MainThread) [supervisor.resolution.checks.base] Run check for dns_server_ipv6_error/dns_server[0m
[32m23-11-05 19:42:18 INFO (MainThread) [supervisor.resolution.checks.base] Run check for trust/supervisor[0m
[32m23-11-05 19:42:18 INFO (MainThread) [supervisor.resolution.check] System checks complete[0m
[32m23-11-05 19:42:18 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state running[0m
[32m23-11-05 19:42:19 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete[0m
[32m23-11-05 19:42:19 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state running[0m
[32m23-11-05 19:42:19 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete[0m
[32m23-11-05 19:42:53 INFO (MainThread) [supervisor.homeassistant.core] Updating Home Assistant to version 2023.11.1[0m
[32m23-11-05 19:42:53 INFO (MainThread) [supervisor.docker.interface] Updating image ghcr.io/home-assistant/raspberrypi4-64-homeassistant:2023.10.5 to ghcr.io/home-assistant/raspberrypi4-64-homeassistant:2023.11.1[0m
[32m23-11-05 19:42:53 INFO (MainThread) [supervisor.docker.interface] Downloading docker image ghcr.io/home-assistant/raspberrypi4-64-homeassistant with tag 2023.11.1.[0m
[32m23-11-05 19:42:56 INFO (SyncWorker_6) [supervisor.docker.manager] Stopping homeassistant application[0m
[32m23-11-05 19:42:56 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API error: Cannot proxy websocket message of unsupported type: 8[0m
[32m23-11-05 19:42:56 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API connection is closed[0m
[32m23-11-05 19:43:15 INFO (SyncWorker_6) [supervisor.docker.manager] Cleaning homeassistant application[0m
[32m23-11-05 19:43:16 INFO (MainThread) [supervisor.homeassistant.module] Update pulse/client.config: /data/tmp/homeassistant_pulse[0m
[32m23-11-05 19:43:16 INFO (MainThread) [supervisor.docker.homeassistant] Starting Home Assistant ghcr.io/home-assistant/raspberrypi4-64-homeassistant with version 2023.11.1[0m
[32m23-11-05 19:43:16 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready[0m
[32m23-11-05 19:43:24 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state running[0m
[32m23-11-05 19:43:25 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete[0m
[32m23-11-05 19:43:28 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json[0m
[32m23-11-05 19:43:28 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/music-assistant/home-assistant-addon repository[0m
[32m23-11-05 19:43:28 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/zigbee2mqtt/hassio-zigbee2mqtt repository[0m
[32m23-11-05 19:43:28 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository[0m
[32m23-11-05 19:43:29 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/esphome/home-assistant-addon repository[0m
[32m23-11-05 19:43:29 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository[0m
[32m23-11-05 19:43:32 INFO (MainThread) [supervisor.store] Loading add-ons from store: 76 all - 0 new - 0 remove[0m
[32m23-11-05 19:43:32 INFO (MainThread) [supervisor.store] Loading add-ons from store: 76 all - 0 new - 0 remove[0m

[31m23-11-05 19:48:19 ERROR (MainThread) [supervisor.homeassistant.core] No API response in 5 minutes, assuming core has had a fatal startup error[0m
[31m23-11-05 19:48:19 CRITICAL (MainThread) [supervisor.homeassistant.core] HomeAssistant update failed -> rollback![0m
[32m23-11-05 19:48:19 INFO (MainThread) [supervisor.resolution.module] Create new issue update_rollback - core / None[0m
[32m23-11-05 19:48:19 INFO (MainThread) [supervisor.homeassistant.core] A backup of the logfile is stored in /config/home-assistant-rollback.log[0m
[32m23-11-05 19:48:19 INFO (MainThread) [supervisor.homeassistant.core] Updating Home Assistant to version 2023.10.5[0m
[32m23-11-05 19:48:19 INFO (MainThread) [supervisor.docker.interface] Updating image ghcr.io/home-assistant/raspberrypi4-64-homeassistant:2023.11.1 to ghcr.io/home-assistant/raspberrypi4-64-homeassistant:2023.10.5[0m
[32m23-11-05 19:48:19 INFO (MainThread) [supervisor.docker.interface] Downloading docker image ghcr.io/home-assistant/raspberrypi4-64-homeassistant with tag 2023.10.5.[0m
[32m23-11-05 19:48:21 INFO (SyncWorker_1) [supervisor.docker.manager] Stopping homeassistant application[0m
[32m23-11-05 19:48:25 INFO (SyncWorker_1) [supervisor.docker.manager] Cleaning homeassistant application[0m
[32m23-11-05 19:48:25 INFO (MainThread) [supervisor.homeassistant.module] Update pulse/client.config: /data/tmp/homeassistant_pulse[0m
[32m23-11-05 19:48:26 INFO (MainThread) [supervisor.docker.homeassistant] Starting Home Assistant ghcr.io/home-assistant/raspberrypi4-64-homeassistant with version 2023.10.5[0m
[32m23-11-05 19:48:26 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready[0m
[32m23-11-05 19:48:34 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state running[0m
[32m23-11-05 19:48:34 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete[0m
[32m23-11-05 19:48:38 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json[0m
[32m23-11-05 19:48:38 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/music-assistant/home-assistant-addon repository[0m
[32m23-11-05 19:48:38 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/zigbee2mqtt/hassio-zigbee2mqtt repository[0m
[32m23-11-05 19:48:38 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository[0m
[32m23-11-05 19:48:38 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/esphome/home-assistant-addon repository[0m
[32m23-11-05 19:48:38 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository[0m
[32m23-11-05 19:48:41 INFO (MainThread) [supervisor.store] Loading add-ons from store: 76 all - 0 new - 0 remove[0m
[32m23-11-05 19:48:41 INFO (MainThread) [supervisor.store] Loading add-ons from store: 76 all - 0 new - 0 remove[0m
[31m23-11-05 19:49:57 ERROR (MainThread) [supervisor.homeassistant.api] Error on call http://172.30.32.1:8123/api/core/state: [0m
[31m23-11-05 19:49:57 ERROR (MainThread) [supervisor.homeassistant.api] Error on call http://172.30.32.1:8123/api/core/state: [0m
[31m23-11-05 19:50:18 ERROR (MainThread) [supervisor.homeassistant.api] Error on call http://172.30.32.1:8123/api/core/state: [0m
[31m23-11-05 19:50:33 ERROR (MainThread) [supervisor.homeassistant.api] Error on call http://172.30.32.1:8123/api/core/state: [0m
[31m23-11-05 19:50:33 ERROR (MainThread) [supervisor.homeassistant.api] Error on call http://172.30.32.1:8123/api/core/state: [0m

[31m23-11-05 19:53:31 ERROR (MainThread) [supervisor.homeassistant.core] No API response in 5 minutes, assuming core has had a fatal startup error[0m


[32m23-11-05 20:05:09 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize[0m
[32m23-11-05 20:05:09 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_appdaemon[0m
[32m23-11-05 20:05:09 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running[0m

[32m23-11-05 20:09:10 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
```

## System Information

version | core-2023.10.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.5
os_name | Linux
os_version | 6.1.21-v8
arch | aarch64
timezone | Europe/Madrid
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4782
Installed Version | 1.33.0
Stage | running
Available Repositories | 1324
Downloaded Repositories | 16

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | May 4, 2024 at 02:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | false
remote_connected | false
alexa_enabled | false
google_enabled | false
remote_server | eu-central-1-14.ui.nabu.casa
certificate_status | ready
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.1
-- | --
update_channel | stable
supervisor_version | supervisor-2023.10.1
agent_version | 1.6.0
docker_version | 24.0.6
disk_total | 458.4 GB
disk_used | 49.7 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Samba share (10.0.2), NGINX Home Assistant SSL proxy (3.5.0), AdGuard Home (4.8.17), Let's Encrypt (4.12.9), Advanced SSH & Web Terminal (15.1.0), File editor (5.6.0), Mosquitto broker (6.3.1), Network UPS Tools (0.12.2), AppDaemon (0.14.0), Zigbee2MQTT (1.33.2-1), InfluxDB (4.8.0), Grafana (9.1.1), Glances (0.19.4), WireGuard (0.9.0), VLC (0.2.0), ESPHome (2023.10.5), Music Assistant BETA (2.0.0b74)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 7
views | 13
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | October 15, 2023 at 16:20
-- | --
current_recorder_run | November 5, 2023 at 19:48
estimated_db_size | 1224.39 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Supervisor diagnostics

https://go.wetransfer.com/t-QaW2yeZWPV

(Cannot drag&drop from phone)

**Comment by agners** [comment] 2023-11-06 10:09
Duplicate of https://github.com/home-assistant/supervisor/issues/4655.

**Closed by agners** 2023-11-06 10:09 UTC
Labels: bug
