### ISSUE TITLE
system is not healthy due failure during setup

### ISSUE THREAD

**Issue by xdia88** [home-assistant/supervisor#3929] opened 2022-10-06 14:50 UTC
### The problem

I can't update. Or restore to one off my backup. 

Logger: homeassistant.components.websocket_api.http.connection
Source: components/hassio/update.py:301
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 16:44:04 (1 occurrences)
Last logged: 16:44:04

[140031695759168] Error updating Home Assistant Core 'HomeAssistantCore.update' blocked from execution, system is not healthy
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 299, in async_install
    await async_update_core(self.hass, version=version, backup=backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 45, in _wrapper
    raise HassioAPIError(data["message"])
homeassistant.components.hassio.handler.HassioAPIError: 'HomeAssistantCore.update' blocked from execution, system is not healthy

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 200, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1738, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1775, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 676, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 931, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 713, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 152, in async_install
    await entity.async_install_with_progress(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 411, in async_install_with_progress
    await self.async_install(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 301, in async_install
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Error updating Home Assistant Core 'HomeAssistantCore.update' blocked from execution, system is not healthy

### What version of Home Assistant Core has the issue?

Home Assistant 2022.9.7

### What was the last working version of Home Assistant Core?

2022.9.6

### What type of installation are you running?

Home Assistant OS

### Additional information

I have tried from ssh to do a repair and rebuild. but no luck...

i really don't wanna reinstall home assistant. 
anyone got any idea what to do?

**Comment by pvizeli** [comment] 2022-10-06 15:55
Use `ha res info` - it should show you the issue which you have to fix

**Comment by xdia88** [comment] 2022-10-06 18:46
![ha res info](https://user-images.githubusercontent.com/52383185/194393460-f86fd7f9-3456-4ac9-a3c6-3359d5c3594d.jpg)
Here is my ha res info.. looks fine. only unhealty is setup :S 
and all my addons look like this now?
![ha addons](https://user-images.githubusercontent.com/52383185/194393692-90f9a565-de75-4ffd-9342-b0d64c741322.jpg)
i have been running home assistant on this gigabyte brix over 2 years and never any problems

**Comment by mdegat01** [comment] 2022-10-06 21:21
Hm not ideal. What's errors are in your supervisor log around its startup? You should be able to see them by doing `ha supervisor logs`. If its been a while since supervisor's last restart can trigger it by doing `ha supervisor restart` and then looking at the logs.

**Comment by xdia88** [comment] 2022-10-07 05:57
When i try to run supervisor log my home assistant just crash

**Comment by pvizeli** [comment] 2022-10-07 07:54
Sounds a bit like out of memory issues

**Comment by xdia88** [comment] 2022-10-07 08:06
hmm my home assistant got 12gb ddr3 ram and home assistant only use 800mb right now

**Comment by xdia88** [comment] 2022-10-07 09:03
Yes, that's probably the only thing to do :(

**Comment by mdegat01** [comment] 2022-10-10 13:58
@ilkanaev that isn't the same issue at all. You have a list of reasons your system is unsupported including that you are running supervised on an unsupported OS (raspbian). And you are unhealthy for a totally different reason, you're running container orchestration software alongside supervisor:
> 22-10-10 15:08:51 ERROR (MainThread) [supervisor.resolution.evaluations.container] Found image in unhealthy image list 'portainer/portainer-ce' on the host
> 22-10-10 15:08:51 WARNING (MainThread) [supervisor.resolution.evaluations.base] Found unsupported images: {'portainer/portainer-ce'} (more-info: https://www.home-assistant.io/more-info/unsupported/software)

You should either switch to HAOS or a supported supervised installation or reach out on the forum for help.

**Comment by ilkanaev** [comment] 2022-10-10 14:41
@mdegat01 thank you very much for quick response! after removing portainer, both update and restore well working.
the only strange is that portainer was running from the begining of installation (for at least one year), but only now i faced this issue.
anyway thank you!

**Comment by MartinKuhl** [comment] 2022-10-10 15:36
for me docker is listed as unhealthy, but is Home Assistant not based on docker. So how that can be unhealthy?

**Comment by mdegat01** [comment] 2022-10-10 15:57
@MartinKuhl Home Assistant is based on docker, it uses it internally. If you are seeing `docker` as the unhealthy reason then you have one of the issues listed [here](https://www.home-assistant.io/more-info/unhealthy/docker).

Note that if the system is unhealthy it is supposed to block updates, addon installs and other things. That's not a bug that's how its supposed to work. This issue is specifically about why the system is unhealthy. In the OP's case that was because setup had failed due to reasons outside of their control (a corrupt file system it appears in this case).

If you are seeing another reason for unhealthy (like docker) then you should make a different issue with the details of your system.

**Comment by MartinKuhl** [comment] 2022-10-10 16:48
@mdegat01 is there any way to restore an older backup to revert any changes in the last days/weeks?
Cause of the unhealthy status, I am not allowed to do so and to setup a complete new Pi can not be the solution.

**Comment by MartinKuhl** [comment] 2022-10-10 18:23
I removed portainer but the health status remain as unhealthly. I have some other docker containers running but this was not mentioned before as a hard problem for the supervisor update.

**Comment by GRClark** [comment] 2022-10-10 22:11
I too am now having this issue after updating Supervisor whereas on 9.x never had any errors.  I had Portainer installed but have since removed container and image but problem persists.  I have other Docker containers/images that are not running - would I need to completely remove them? 

The info here says to restart supervisor.  Does that mean restarting HA itself under settings > system or should I be restarting the supervisor container (I'm running HA in Docker environment). 
https://www.home-assistant.io/more-info/unsupported/software/

Also is there a way to downgrade supervisor back to 9.x as a short term fix?

**Comment by shirou93** [comment] 2022-10-11 05:52
Maybe add checbox to ignore unhealthy state? I using multiple dockers containers on portainer knowing risc.

**Comment by viktak** [comment] 2022-10-11 06:24
Same issue here, trying to update 2022.10.2 -> 2022.10.3. Yesterday I updated the supervisor...

**Comment by kfulko** [comment] 2022-10-11 09:14
Portainer does the problem, removing this container fixes the system status to healthy.

**Comment by viktak** [comment] 2022-10-11 10:26
I agree, @kfulko . I have been using Portainer for years as a monitoring/diagnosing tool and have never had a problem with it.

Is there a situation where it might conflict with HA?

**Comment by viktak** [comment] 2022-10-11 11:20
I just tries removing portainer: Stopped it, removed the container and removed the image. HA still won't update with the same error.

**Comment by kfulko** [comment] 2022-10-11 11:25
> I just tries removing portainer: Stopped it, removed the container and removed the image. HA still won't update with the same error.

You must reboot host after remove Portainer, then works.

**Comment by viktak** [comment] 2022-10-11 12:19
yepp, just tried it, confirmed.

**Comment by shirou93** [comment] 2022-10-11 13:04
how to downgrade supervisor?

**Comment by mdegat01** [comment] 2022-10-11 15:04
> I removed portainer but the health status remain as unhealthy. I have some other docker containers running but this was not mentioned before as a hard problem for the supervisor update.

@MartinKuhl Where have you checked? It comes up all the time as the root cause for exotic configurations that break supervisor in the forum and issues here. When that keeps happening then a check is added so developers can stop wasting time digging into issues where the root cause is "user did something unsupported and it broke". That's what happened here.

> Also is there a way to downgrade supervisor back to 9.x as a short term fix?

@GRClark @shirou93 Not via HA. Supervisor only goes forward as everything else depends on it. Rolling supervisor back could break an unknown number of things, hence why supervisor must be updated before anything else. I'm sure someone has figured out a way to do it anyway on the forum though.

Closing this issue since the original user seems to have had their issue resolved and now it has become an off-topic conversation about portainer.

**Closed as completed by mdegat01** 2022-10-11 15:04 UTC

**Comment by urtziDV** [comment] 2022-10-23 19:08
Login via Putty and run `ha jobs options --ignore-conditions healthy `
The system remains unhealthy but it does not block any installation updates.

**Comment by kfulko** [comment] 2022-10-23 19:26
Another way to use Portainer with HA is to connect to the docker API from another machine with Portainer installed, there are many tutorials on the web on how to do this.
