### ISSUE TITLE
Cant update Home Assistant Core 2022.11.2

### ISSUE THREAD

**Issue by phobiccarrot** [home-assistant/supervisor#4004] opened 2022-11-15 15:14 UTC
### Describe the issue you are experiencing

Im not able to update Home Assistant Core to the latest version, im getting the following error.

Logger: homeassistant.components.websocket_api.http.connection
Source: components/hassio/update.py:305
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 9:20:46 AM (1 occurrences)
Last logged: 9:20:46 AM

[140167080234672] Error updating Home Assistant Core 'HomeAssistantCore.update' blocked from execution, no host internet connection
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 303, in async_install
    await async_update_core(self.hass, version=version, backup=backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 45, in _wrapper
    raise HassioAPIError(data["message"])
homeassistant.components.hassio.handler.HassioAPIError: 'HomeAssistantCore.update' blocked from execution, no host internet connection

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 200, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1744, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1781, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 208, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 678, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 943, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 715, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 154, in async_install
    await entity.async_install_with_progress(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 413, in async_install_with_progress
    await self.async_install(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 305, in async_install
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Error updating Home Assistant Core 'HomeAssistantCore.update' blocked from execution, no host internet connection

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Debian

### Steps to reproduce the issue

1. Click update on update Core
2.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
1. Logger: homeassistant.components.websocket_api.http.connection
Source: components/hassio/update.py:305
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 9:59:50 AM (1 occurrences)
Last logged: 9:59:50 AM

[140561284751056] Error updating Home Assistant Core 'HomeAssistantCore.update' blocked from execution, no host internet connection
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 303, in async_install
    await async_update_core(self.hass, version=version, backup=backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 45, in _wrapper
    raise HassioAPIError(data["message"])
homeassistant.components.hassio.handler.HassioAPIError: 'HomeAssistantCore.update' blocked from execution, no host internet connection

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 200, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1744, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1781, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 208, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 678, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 943, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 715, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 154, in async_install
    await entity.async_install_with_progress(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 413, in async_install_with_progress
    await self.async_install(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 305, in async_install
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Error updating Home Assistant Core 'HomeAssistantCore.update' blocked from execution, no host internet connection
```

### System Health information

I dont see that.

### Supervisor diagnostics

[config_entry-hassio-5782e352e591d87a91927cd72825d71d.json.txt](https://github.com/home-assistant/supervisor/files/10013764/config_entry-hassio-5782e352e591d87a91927cd72825d71d.json.txt)

**Comment by RobertoCravallo** [comment] 2022-11-15 16:29
It has been "installing" for 30 Minutes, so I restarted my RASPBERRY. Now it continues to "install", but I see NOTHING of my dashboard. Nearly all pages are blank or I get a "Error while loading page"!!!!

Looks like my installation was shot to heck with this update.....   :-(

**Comment by bdraco** [comment] 2022-11-15 17:56
Since its a pain to type on the console. I also put the one liner up at `https://koston.org/sup_fix.txt`

Be sure to check it before running it as its not good to blindly run code downloaded from the internet:
`curl -o - https://koston.org/sup_fix.txt`

If it matches and looks good you can run:
`curl -o - https://koston.org/sup_fix.txt | sh`

**Comment by alexruffell** [comment] 2022-11-15 18:01
@bdraco Is the code to fix @RobertoCravallo 's problem or to fix the stuck supervisor update? I have 2 systems and both can't update, one is a Raspberry PI and the other a Proxmox VM install on an i7.

**Comment by bdraco** [comment] 2022-11-15 18:07
> @bdraco Is the code to fix @RobertoCravallo 's problem or to fix the stuck supervisor update? I have 2 systems and both can't update, one is a Raspberry PI and the other a Proxmox VM install on an i7.

Its likely all the same issue

**Comment by mdegat01** [comment] 2022-11-15 18:39
@RobertoCravallo restoring a backup on the current system won't work. There was an issue with the beta version of supervisor, `2022.11.0` detailed out in #4003 . Restoring a backup can't fix supervisor since supervisor is what makes and restores backups.

There are two options to resolve this:
1. Follow bdracos instructions above to run that command
2. Reinstall the system from scratch (since that will install the latest stable version of supervisor which does not have this issue) and then restore your backup.

**Comment by mdegat01** [comment] 2022-11-15 18:43
@alexruffell your issue isn't the same as Roberto's. Based on the diagnostic data you're on supervisor version `2022.10.2` which doesn't have this issue.

Can you show me the output of the following commands?
```
ha resolution info
ha network info
```

**Comment by alexruffell** [comment] 2022-11-15 18:45
@mdegat01 The data you are referring to is likely from @phobiccarrot as I did not post any. I just ran @bdraco 's script on both my systems and problem is now gone.

**Comment by mdegat01** [comment] 2022-11-15 18:50
Sorry! My bad, ony phone and mixed up who is who. You're right I meant @phobiccarrot above not @alexruffell , glad yours is resolved.

@phobiccarrot can you share the requested info above when you get a chance?

**Comment by christophermichaelshaw** [comment] 2022-11-15 19:05
I am also encountering this issue -- I ran the command provided by @bdraco and now Supervisor starts, but recorder is refusing to start:

Logger: homeassistant.setup
Source: setup.py:255
First occurred: 11:03:51 (1 occurrences)
Last logged: 11:03:51
Setup failed for recorder: Integration failed to initialize.

I'm running split MariaDB and InfluxDB....

**Comment by FrancoLoco** [comment] 2022-11-15 19:31
I also have the issue.. restored from backups.. will try going back to my image from today and try the command above thanks

**Comment by Toggz** [comment] 2022-11-15 19:59
> Since its a pain to type on the console. I also put the one liner up at `https://koston.org/sup_fix.txt`
> 
> Be sure to check it before running it as its not good to blindly run code downloaded from the internet: `curl -o - https://koston.org/sup_fix.txt`
> 
> If it matches and looks good you can run: `curl -o - https://koston.org/sup_fix.txt | sh`

Hi,

Life saver, worked a treat. Thank you!

**Comment by RobertoCravallo** [comment] 2022-11-15 20:04
Ok, restored from back-up. A little bit of data went south, nothing important. Thanks to "Home Assistant Google Drive Backup". Note to self: Buy the guy a coffee!!!!

**Comment by jwshields** [comment] 2022-11-15 20:47
Will the shell script linked work on an installation of HassOS OVA?  
I was able to hard boot my VM a few times in ESX-i and recovered without data loss, but I'm still on 2022.11.0.  
  
Been getting really weary recently to update my installation with the amount of releases that are flowing out for Hassio overall (supervisor, core, addons, etc). Especially breaking updates like this..  
Will 2022.11.3 be released "soon?" or is there absolutely no way forward at all? (having only skimmed this thread)

**Comment by phobiccarrot** [comment] 2022-11-15 22:01
> @alexruffell your issue isn't the same as Roberto's. Based on the diagnostic data you're on supervisor version `2022.10.2` which doesn't have this issue.
> 
> Can you show me the output of the following commands?
> 
> ```
> ha resolution info
> ha network info
> ```
> 
> Also you're sharing core logs, those don't really help us diagnose this. Can you share any errors you see in the supervisor logs? It's in the same place in the UI but you have to switch to `supervisor` in the top right. Or do `ha supervisor logs` from the command line

Here is my log:
22-11-15 13:45:45 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
22-11-15 14:14:55 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
22-11-15 14:14:55 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DNS_SERVER_FAILED/ContextType.DNS_SERVER
22-11-15 14:14:55 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM
22-11-15 14:14:55 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON
22-11-15 14:14:55 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DNS_SERVER_IPV6_ERROR/ContextType.DNS_SERVER
22-11-15 14:14:55 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.IPV4_CONNECTION_PROBLEM/ContextType.SYSTEM
22-11-15 14:14:55 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE
22-11-15 14:14:55 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.SUPERVISOR
22-11-15 14:14:55 INFO (MainThread) [supervisor.resolution.check] System checks complete
22-11-15 14:14:55 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
22-11-15 14:14:55 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
22-11-15 14:14:55 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
22-11-15 14:14:55 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
22-11-15 14:15:45 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
22-11-15 14:45:45 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
22-11-15 15:14:55 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
22-11-15 15:14:55 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DNS_SERVER_FAILED/ContextType.DNS_SERVER
22-11-15 15:14:55 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM
22-11-15 15:14:55 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON
22-11-15 15:14:55 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DNS_SERVER_IPV6_ERROR/ContextType.DNS_SERVER
22-11-15 15:14:55 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.IPV4_CONNECTION_PROBLEM/ContextType.SYSTEM
22-11-15 15:14:55 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE
22-11-15 15:14:55 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.SUPERVISOR
22-11-15 15:14:55 INFO (MainThread) [supervisor.resolution.check] System checks complete
22-11-15 15:14:55 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
22-11-15 15:14:56 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
22-11-15 15:14:56 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
22-11-15 15:14:56 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
22-11-15 15:15:44 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
22-11-15 15:15:45 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/esphome/home-assistant-addon repository
22-11-15 15:15:45 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
22-11-15 15:15:45 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository
22-11-15 15:15:45 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/zigbee2mqtt/hassio-zigbee2mqtt repository
22-11-15 15:15:45 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/mrlt8/docker-wyze-bridge repository
22-11-15 15:15:45 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
22-11-15 15:15:46 INFO (MainThread) [supervisor.store] Loading add-ons from store: 73 all - 0 new - 0 remove
22-11-15 15:15:46 INFO (MainThread) [supervisor.store] Loading add-ons from store: 73 all - 0 new - 0 remove
22-11-15 15:35:44 INFO (MainThread) [supervisor.host.info] Updating local host information
22-11-15 15:35:44 INFO (MainThread) [supervisor.host.services] Updating service information
22-11-15 15:35:44 INFO (MainThread) [supervisor.host.network] Updating local network information
22-11-15 15:35:44 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information
22-11-15 15:35:44 INFO (MainThread) [supervisor.host.manager] Host information reload completed
22-11-15 15:45:45 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
22-11-15 16:14:56 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
22-11-15 16:14:56 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DNS_SERVER_FAILED/ContextType.DNS_SERVER
22-11-15 16:14:56 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM
22-11-15 16:14:56 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON
22-11-15 16:14:56 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DNS_SERVER_IPV6_ERROR/ContextType.DNS_SERVER
22-11-15 16:14:56 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.IPV4_CONNECTION_PROBLEM/ContextType.SYSTEM
22-11-15 16:14:56 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE
22-11-15 16:14:56 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.SUPERVISOR
22-11-15 16:14:56 INFO (MainThread) [supervisor.resolution.check] System checks complete
22-11-15 16:14:56 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
22-11-15 16:14:56 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
22-11-15 16:14:56 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
22-11-15 16:14:56 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
22-11-15 16:15:46 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
22-11-15 16:45:46 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token

**Comment by phobiccarrot** [comment] 2022-11-15 22:08
> Since its a pain to type on the console. I also put the one liner up at `https://koston.org/sup_fix.txt`
> 
> Be sure to check it before running it as its not good to blindly run code downloaded from the internet: `curl -o - https://koston.org/sup_fix.txt`
> 
> If it matches and looks good you can run: `curl -o - https://koston.org/sup_fix.txt | sh`

I did that, then rebooted VM.  Still same error.

**Comment by Toggz** [comment] 2022-11-15 22:14
I'm using HAOS and worked fine using the following method.......(disable protection mode)

https://github.com/home-assistant/supervisor/issues/4003#issuecomment-1315594494

**Comment by jwshields** [comment] 2022-11-16 09:22
> Since its a pain to type on the console. I also put the one liner up at `https://koston.org/sup_fix.txt`
> 
> Be sure to check it before running it as its not good to blindly run code downloaded from the internet: `curl -o - https://koston.org/sup_fix.txt`
> 
> If it matches and looks good you can run: `curl -o - https://koston.org/sup_fix.txt | sh`

Thank you for the fix. Tested on my HassOS ESX-i VM, ran the commands by hand, rebooted the machine. Took a tad longer than normal to come up, but things seem to be cooperating at the moment, and my system is reporting 2022.11.2  
Thank you for the help here!

**Comment by mdegat01** [comment] 2022-11-16 20:13
Duplicate of #4003

**Closed by mdegat01** 2022-11-16 20:13 UTC
Labels: bug

**Comment by andybjackson** [comment] 2022-11-22 17:15
The Home Assistant team should take note of this bug as it had significant real world user impact. I torched and rebuilt my system to try to resolve (losing my energy data in the process - which I know is my bad). This should get a speedy blog post, and should be avoided at all costs in future if possible.

**Comment by Psytoshgen** [comment] 2022-11-27 12:10
two installations old one raspberrypi 400 and new raspberrypi 3b both cant update. looks like websocket error. both installations are hassos, so docker solution is not my way

**Comment by laxfiend77** [comment] 2022-12-13 01:41
> Since its a pain to type on the console. I also put the one liner up at `https://koston.org/sup_fix.txt`
> 
> Be sure to check it before running it as its not good to blindly run code downloaded from the internet: `curl -o - https://koston.org/sup_fix.txt`
> 
> If it [matches](https://github.com/home-assistant/supervisor/issues/4003#issuecomment-1315590850) and looks good you can run: `curl -o - https://koston.org/sup_fix.txt | sh`

do i run this comman in the homeassistant cli?
