### ISSUE TITLE
Partial restore wipes Network storage mounted under /share

### ISSUE THREAD

**Issue by phellarv** [home-assistant/supervisor#4711] opened 2023-11-16 10:54 UTC
### Describe the issue you are experiencing

I have the Immich-addon installed.
Under /share/Immich I have mounted a remote cifs-directory from another server I have.
When I did a partial restore (including /share), the restore completely wiped the remote storage.
This is not expected behavior.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1. Take full backup with remote storage attached to a directory under /share
2. Do a partial restore including /share
3. Observe that existing files under /share/<remote-storage> is wiped

### Anything in the Supervisor logs that might be useful for us?

```txt
I do not have any logs right now.
```

### System Health information

"There are currently no repairs available"

### Supervisor diagnostics

[config_entry-hassio-6fc8ace0e1a6b3eb9eaaa3455ff54969.json.txt](https://github.com/home-assistant/supervisor/files/13376656/config_entry-hassio-6fc8ace0e1a6b3eb9eaaa3455ff54969.json.txt)

**Comment by phellarv** [comment] 2023-11-16 17:25
Forgot this:
<div class="card-header"><h3>Home Assistant Supervisor</h3>  </div>  
Host Operating System | Home Assistant OS 11.1
-- | --
Update Channel | stable
Supervisor Version | supervisor-2023.11.3
Agent Version | 1.6.0
Docker Version | 24.0.6
Disk Total | 116.7 GB
Disk Used | 40.6 GB
Healthy | true
Supported | true
Board | generic-x86-64
Supervisor API | ok
Version API | ok
Installed Add-ons | Terminal  & SSH (9.8.1), MariaDB (2.6.1), InfluxDB (4.8.0), Home Assistant  Google Drive Backup (0.111.1), ESPHome (2023.11.1), Node-RED (16.0.2),  EMQX (0.2.12), Zigbee2MQTT (1.33.2-1), Studio Code Server (5.14.2),  Prometheus Node Exporter (0.7.0), Matter Server (4.10.2), Silicon Labs  Multiprotocol (2.3.2), Whisper (1.0.0), Piper (1.4.0), openWakeWord  (1.8.2), File editor (5.7.0)

**Comment by agners** [comment] 2023-11-20 12:52
> 3. Observe that existing files under /share/ is wiped

The contents under /share are expected to be wiped, since you restore that folder. But the remote content (in your case under `/share/Immich`) should not get wiped! 

Note that earlier versions of Supervisor used to delete things in remote directories, but since you are using the latest version 2023.11.3 this should be resolved (e.g. #4653).

**Comment by phellarv** [comment] 2023-11-20 19:52
Well, I can confirm that the directory was wiped during restore. 
Have you tried to reproduce?
I will await your tests, and if you cannot reproduce, please advice on how I can proceed.

**Comment by agners** [comment] 2023-11-29 09:28
We had two safe guards in place, unmounting the share and using rm to not cross file system boundaries. Unfortunately, both safeguards failed in their own way. The first one was a race condition, so that might depend on the hardware/system if it actually appears. But I was able to reproduce on my end.

With https://github.com/home-assistant/supervisor/pull/4732 in merged, we have at least one working mitigation in place. Supervisor 2023.11.6 now on the stable channel contains that fix.

Thanks for your report!

**Closed by agners** 2023-11-29 09:28 UTC
Labels: bug
