### ISSUE TITLE
http://supervisor/host/reboot: dial tcp 172.30.32.2:80: connect: connection refused

### ISSUE THREAD

**Issue by deltabert** [home-assistant/supervisor#2687] opened 2021-03-05 10:06 UTC
### Describe the issue you are experiencing

Running Home Assistant Superviced (Docker) on Intel NUCi5. Upgraded to 2021.03 and get this error message when i want to go to Supervicor: Unable to load the panel source: /api/hassio/app/entrypoint.js.

### What is the used version of the Supervisor?

Latest version, updated after email Paulus Schouten. 2021-03-07. Can't see the version anymore...

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Other Ubuntu 20.04.2 LTS

### What is the version of your installed operating system?

Ubuntu 20.04.2 LTS

### What version of Home Assistant Core is installed?

Supervisor not accessable: Upgraded on 2021-03-07.

### Steps to reproduce the issue

1.
2.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
# Put your logs below this line

```

I try to view my snapshors in order to restore an older snapshot, but when i give the command ha snapshots:
iotstack@nuc-i5-1u1:~$ ha snapshots
Get "http://supervisor/snapshots": dial tcp 172.30.32.2:80: connect: no route to host

It looks like exactly the same problem as described here, but that issue is closed by @ludeeus : https://github.com/home-assistant/supervisor/issues/1675

I attached the Home Assistant Observer logfile:
[Home Assistant observer.txt](https://github.com/home-assistant/supervisor/files/6089792/Home.Assistant.observer.txt)

Please, any help is much appreciated.
PS, I am aware of the fact that Ubuntu is not officially supported for the Superviced version, but up until now i had no issues using Ubuntu.

**Comment by deltabert** [comment] 2021-03-05 10:25
An other obsevation:
I am missing the following items in the Left Menu: deCONZ, ZWaveJS, Terminal, AdGuard Home, VSCode...

**Comment by ludeeus** [comment] 2021-03-05 11:06
Looks like you have docker issues. However, this is on an unsupported system so closing this issue, try asking on the forums :+1:

**Closed by ludeeus** 2021-03-05 11:06 UTC
Labels: unsupported

**Comment by gretel** [comment] 2021-03-20 14:45
@ludeeus this is getting circular. the [forum](https://community.home-assistant.io/t/unable-to-load-the-panel-source-api-hassio-app-entrypoint-js/126821) has no solution for this (thread started '19 and is still going on) and i am getting the same issue using latest `hassos` just now.

instead of saying `docker` is the root cause i suggest to actually investigate the issue.

the observations done by all the other folks are same as mine. so please, don't just close issues (this has been reported at least three times seperately) and cause frustration due to lack of quality in this software and the will to improve.

**Comment by balloob** [comment] 2021-03-20 15:16
It's unsupported to run supervised on Ubuntu so we don't support it. 

Feel free to open an issue if you run Supervised on Debian and run into issues and we'll make sure it works.
