### ISSUE TITLE
IP is not updating 

### ISSUE THREAD

**Issue by rajalingamj175** [home-assistant/supervisor#4023] opened 2022-11-24 14:09 UTC
### Describe the issue you are experiencing

Unable to get IP address

```
sudo ha info
arch: amd64
channel: stable
docker: 20.10.21
features:
- journal
hassos: null
homeassistant: 2022.11.4
hostname: null
logging: info
machine: qemux86-64
operating_system: null
state: running
supervisor: 2022.11.2
supported: false
supported_arch:
- amd64
- i386
timezone: America/Los_Angeles
```

```
sudo ha host info
agent_version: null
apparmor_version: null
boot_timestamp: null
broadcast_llmnr: null
broadcast_mdns: null
chassis: null
cpe: null
deployment: null
disk_free: 479.2
disk_life_time: null
disk_total: 484.4
disk_used: 5.2
dt_synchronized: null
dt_utc: null
features:
- journal
hostname: null
kernel: null
llmnr_hostname: null
operating_system: null
startup_time: null
timezone: null
use_ntp: null

```

```
sudo ha network info
docker:
  address: 172.30.32.0/23
  dns: 172.30.32.3
  gateway: 172.30.32.1
  interface: hassio
host_internet: null
interfaces: []
supervisor_internet: true
```

```
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.5 LTS
Release:        20.04
Codename:       focal
```

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Debian

### Steps to reproduce the issue

1.Unable to get IP address
2.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
Nov 24 13:21:52 ip-10-10-25-97 NetworkManager[548]: <info>  [1669296112.7960] dhcp4 (ens5): option requested_time_offset => '1'
Nov 24 13:21:52 ip-10-10-25-97 NetworkManager[548]: <info>  [1669296112.7960] dhcp4 (ens5): option requested_wpad       => '1'
Nov 24 13:21:52 ip-10-10-25-97 NetworkManager[548]: <info>  [1669296112.7960] dhcp4 (ens5): option routers              => '10.10.24.1'
Nov 24 13:21:52 ip-10-10-25-97 NetworkManager[548]: <info>  [1669296112.7960] dhcp4 (ens5): option subnet_mask          => '255.255.252.0'
Nov 24 13:21:52 ip-10-10-25-97 NetworkManager[548]: <info>  [1669296112.7960] dhcp4 (ens5): state changed extended -> extended
Nov 24 13:21:52 ip-10-10-25-97 systemd[1]: Starting Network Manager Script Dispatcher Service...
Nov 24 13:21:52 ip-10-10-25-97 systemd[1]: Started Network Manager Script Dispatcher Service.
Nov 24 13:22:03 ip-10-10-25-97 systemd[1]: NetworkManager-dispatcher.service: Succeeded.
Nov 24 13:51:52 ip-10-10-25-97 NetworkManager[548]: <info>  [1669297912.7960] dhcp4 (ens5): option dhcp_lease_time      => '3600'
Nov 24 13:51:52 ip-10-10-25-97 NetworkManager[548]: <info>  [1669297912.7961] dhcp4 (ens5): option domain_name          => 'us-west-1.compute.internal'
Nov 24 13:51:52 ip-10-10-25-97 NetworkManager[548]: <info>  [1669297912.7961] dhcp4 (ens5): option domain_name_servers  => '10.10.12.2'
Nov 24 13:51:52 ip-10-10-25-97 NetworkManager[548]: <info>  [1669297912.7961] dhcp4 (ens5): option expiry               => '1669301512'
Nov 24 13:51:52 ip-10-10-25-97 NetworkManager[548]: <info>  [1669297912.7961] dhcp4 (ens5): option host_name            => 'ip-10-10-25-97'
Nov 24 13:51:52 ip-10-10-25-97 NetworkManager[548]: <info>  [1669297912.7961] dhcp4 (ens5): option interface_mtu        => '9001'
Nov 24 13:51:52 ip-10-10-25-97 NetworkManager[548]: <info>  [1669297912.7961] dhcp4 (ens5): option ip_address           => '10.10.25.97'
Nov 24 13:51:52 ip-10-10-25-97 NetworkManager[548]: <info>  [1669297912.7961] dhcp4 (ens5): option requested_broadcast_address => '1'
Nov 24 13:51:52 ip-10-10-25-97 NetworkManager[548]: <info>  [1669297912.7961] dhcp4 (ens5): option requested_domain_name => '1'
Nov 24 13:51:52 ip-10-10-25-97 NetworkManager[548]: <info>  [1669297912.7961] dhcp4 (ens5): option requested_domain_name_servers => '1'
Nov 24 13:51:52 ip-10-10-25-97 NetworkManager[548]: <info>  [1669297912.7961] dhcp4 (ens5): option requested_domain_search => '1'
Nov 24 13:51:52 ip-10-10-25-97 NetworkManager[548]: <info>  [1669297912.7961] dhcp4 (ens5): option requested_host_name  => '1'
Nov 24 13:51:52 ip-10-10-25-97 NetworkManager[548]: <info>  [1669297912.7961] dhcp4 (ens5): option requested_interface_mtu => '1'
Nov 24 13:51:52 ip-10-10-25-97 NetworkManager[548]: <info>  [1669297912.7961] dhcp4 (ens5): option requested_ms_classless_static_routes => '1'
Nov 24 13:51:52 ip-10-10-25-97 NetworkManager[548]: <info>  [1669297912.7962] dhcp4 (ens5): option requested_nis_domain => '1'
Nov 24 13:51:52 ip-10-10-25-97 NetworkManager[548]: <info>  [1669297912.7962] dhcp4 (ens5): option requested_nis_servers => '1'
Nov 24 13:51:52 ip-10-10-25-97 NetworkManager[548]: <info>  [1669297912.7962] dhcp4 (ens5): option requested_ntp_servers => '1'
Nov 24 13:51:52 ip-10-10-25-97 NetworkManager[548]: <info>  [1669297912.7962] dhcp4 (ens5): option requested_rfc3442_classless_static_routes => '1'
Nov 24 13:51:52 ip-10-10-25-97 NetworkManager[548]: <info>  [1669297912.7962] dhcp4 (ens5): option requested_root_path  => '1'
Nov 24 13:51:52 ip-10-10-25-97 NetworkManager[548]: <info>  [1669297912.7962] dhcp4 (ens5): option requested_routers    => '1'
Nov 24 13:51:52 ip-10-10-25-97 NetworkManager[548]: <info>  [1669297912.7962] dhcp4 (ens5): option requested_static_routes => '1'
Nov 24 13:51:52 ip-10-10-25-97 NetworkManager[548]: <info>  [1669297912.7962] dhcp4 (ens5): option requested_subnet_mask => '1'
Nov 24 13:51:52 ip-10-10-25-97 NetworkManager[548]: <info>  [1669297912.7962] dhcp4 (ens5): option requested_time_offset => '1'
Nov 24 13:51:52 ip-10-10-25-97 NetworkManager[548]: <info>  [1669297912.7962] dhcp4 (ens5): option requested_wpad       => '1'
Nov 24 13:51:52 ip-10-10-25-97 NetworkManager[548]: <info>  [1669297912.7962] dhcp4 (ens5): option routers              => '10.10.24.1'
Nov 24 13:51:52 ip-10-10-25-97 NetworkManager[548]: <info>  [1669297912.7962] dhcp4 (ens5): option subnet_mask          => '255.255.252.0'
Nov 24 13:51:52 ip-10-10-25-97 NetworkManager[548]: <info>  [1669297912.7962] dhcp4 (ens5): state changed extended -> extended
Nov 24 13:51:52 ip-10-10-25-97 systemd[1]: Starting Network Manager Script Dispatcher Service...
Nov 24 13:51:52 ip-10-10-25-97 systemd[1]: Started Network Manager Script Dispatcher Service.
Nov 24 13:52:03 ip-10-10-25-97 systemd[1]: NetworkManager-dispatcher.service: Succeeded.
Nov 24 14:07:55 ip-10-10-25-97 systemd[1]: run-docker-runtime\x2drunc-moby-13099ede3eb4a9bafcc2b90e39f34027ff7519487e24ecee42777be2920fdbdb-runc.NWGJdK.mount: Succeeded.
```

### System Health information

lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.5 LTS
Release:        20.04
Codename:       focal

**Comment by ludeeus** [comment] 2022-11-24 14:12
Duplicate of https://github.com/home-assistant/core/issues/82568

**Closed by ludeeus** 2022-11-24 14:12 UTC
Labels: unsupported
