### ISSUE TITLE
System randomly becomes non-privileged

### ISSUE THREAD

**Issue by EinSchwerd** [home-assistant/supervisor#4529] opened 2023-09-06 01:45 UTC
### Describe the issue you are experiencing

My home assistant system is occasionally becoming unprivileged.
I notice it when I try to install add-on, HA or supervisor updates. I get an error stating:
'AddonManager.update' blocked from execution, system is not healthy - privileged

To recover from this state (to make it possible to install updates) I need to restart the server running HA and on some occasions, I need to re-run the supervised installer script.

Can I provide any further information to troubleshoot this issue?

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

?

### Steps to reproduce the issue

Reproduction steps are not available. Sometimes I can install updates for months, and sometimes the system goes into a non-privileged state between multiple consecutive updates.

### Anything in the Supervisor logs that might be useful for us?

```txt
[32m23-09-06 09:16:28 INFO (MainThread) [supervisor.api.middleware.security] /os/update access from core_ssh[0m
[33m23-09-06 09:16:28 WARNING (MainThread) [supervisor.jobs] 'OSManager.update' blocked from execution, no Home Assistant OS available[0m
[32m23-09-06 09:16:45 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/update access from core_ssh[0m





[32m23-09-06 09:38:23 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m






[32m23-09-06 10:08:23 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json[0m
[32m23-09-06 10:08:24 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[32m23-09-06 10:10:08 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING[0m
[32m23-09-06 10:10:43 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DNS_SERVER_IPV6_ERROR/ContextType.DNS_SERVER[0m
[32m23-09-06 10:10:43 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.NO_CURRENT_BACKUP/ContextType.SYSTEM[0m
[32m23-09-06 10:11:53 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DNS_SERVER_FAILED/ContextType.DNS_SERVER[0m
[32m23-09-06 10:11:53 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.IPV4_CONNECTION_PROBLEM/ContextType.SYSTEM[0m
[32m23-09-06 10:11:53 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON[0m
[32m23-09-06 10:11:53 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE[0m
[32m23-09-06 10:11:53 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.SUPERVISOR[0m
[32m23-09-06 10:11:53 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DOCKER_CONFIG/ContextType.SYSTEM[0m
[32m23-09-06 10:11:53 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.MULTIPLE_DATA_DISKS/ContextType.SYSTEM[0m
[32m23-09-06 10:11:53 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM[0m
[32m23-09-06 10:11:53 INFO (MainThread) [supervisor.resolution.check] System checks complete[0m
[32m23-09-06 10:11:53 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING[0m
[32m23-09-06 10:11:53 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete[0m
[32m23-09-06 10:11:53 INFO (MainThread) [supervisor.jobs] 'ResolutionFixup.run_autofix' blocked from execution, system is not healthy - privileged[0m

[32m23-09-06 10:15:03 INFO (MainThread) [supervisor.host.info] Updating local host information[0m
[32m23-09-06 10:15:03 INFO (MainThread) [supervisor.host.services] Updating service information[0m
[32m23-09-06 10:15:03 INFO (MainThread) [supervisor.host.network] Updating local network information[0m
[32m23-09-06 10:15:03 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information[0m
[32m23-09-06 10:15:03 INFO (MainThread) [supervisor.host.manager] Host information reload completed[0m





[32m23-09-06 10:38:24 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m





[32m23-09-06 11:08:23 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/thomasmauerer/hassio-addons repository[0m
[32m23-09-06 11:08:23 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/zigbee2mqtt/hassio-zigbee2mqtt repository[0m
[32m23-09-06 11:08:23 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/esphome/home-assistant-addon repository[0m
[32m23-09-06 11:08:23 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/bachya/home-assistant-addons repository[0m
[32m23-09-06 11:08:23 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/rhasspy/hassio-addons repository[0m
[32m23-09-06 11:08:23 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository[0m
[32m23-09-06 11:08:23 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository[0m
[32m23-09-06 11:08:23 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/mihsu81/addon-theengsgw repository[0m

[32m23-09-06 11:08:24 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[32m23-09-06 11:08:25 INFO (MainThread) [supervisor.store] Loading add-ons from store: 87 all - 0 new - 0 remove[0m
[32m23-09-06 11:08:25 INFO (MainThread) [supervisor.store] Loading add-ons from store: 87 all - 0 new - 0 remove[0m
[32m23-09-06 11:11:53 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING[0m
[32m23-09-06 11:12:28 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DNS_SERVER_IPV6_ERROR/ContextType.DNS_SERVER[0m
[32m23-09-06 11:12:28 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.NO_CURRENT_BACKUP/ContextType.SYSTEM[0m

[32m23-09-06 11:13:38 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DNS_SERVER_FAILED/ContextType.DNS_SERVER[0m
[32m23-09-06 11:13:38 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.IPV4_CONNECTION_PROBLEM/ContextType.SYSTEM[0m
[32m23-09-06 11:13:38 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON[0m
[32m23-09-06 11:13:38 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE[0m
[32m23-09-06 11:13:38 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.SUPERVISOR[0m
[32m23-09-06 11:13:38 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DOCKER_CONFIG/ContextType.SYSTEM[0m
[32m23-09-06 11:13:38 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.MULTIPLE_DATA_DISKS/ContextType.SYSTEM[0m
[32m23-09-06 11:13:38 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM[0m
[32m23-09-06 11:13:38 INFO (MainThread) [supervisor.resolution.check] System checks complete[0m
[32m23-09-06 11:13:38 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING[0m
[32m23-09-06 11:13:38 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete[0m
[32m23-09-06 11:13:38 INFO (MainThread) [supervisor.jobs] 'ResolutionFixup.run_autofix' blocked from execution, system is not healthy - privileged[0m


[33m23-09-06 11:26:47 WARNING (MainThread) [supervisor.jobs] 'AddonManager.update' blocked from execution, system is not healthy - privileged[0m

[33m23-09-06 11:29:33 WARNING (MainThread) [supervisor.jobs] 'AddonManager.update' blocked from execution, system is not healthy - privileged[0m
[32m23-09-06 11:29:44 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/update access from core_ssh[0m
[32m23-09-06 11:29:51 INFO (MainThread) [supervisor.api.middleware.security] /addons access from core_ssh[0m
[32m23-09-06 11:30:33 INFO (MainThread) [supervisor.api.middleware.security] /addons access from core_ssh[0m
[32m23-09-06 11:30:38 INFO (MainThread) [supervisor.api.middleware.security] /addons/esphome/update access from core_ssh[0m
[32m23-09-06 11:30:43 INFO (MainThread) [supervisor.api.middleware.security] /addons/esp-home/update access from core_ssh[0m
[33m23-09-06 11:32:16 WARNING (MainThread) [supervisor.jobs] 'AddonManager.update' blocked from execution, system is not healthy - privileged[0m
[32m23-09-06 11:33:00 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/mihsu81/addon-theengsgw repository[0m
[32m23-09-06 11:33:00 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/thomasmauerer/hassio-addons repository[0m
[32m23-09-06 11:33:00 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/zigbee2mqtt/hassio-zigbee2mqtt repository[0m
[32m23-09-06 11:33:00 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/esphome/home-assistant-addon repository[0m
[32m23-09-06 11:33:00 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/bachya/home-assistant-addons repository[0m
[32m23-09-06 11:33:00 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/rhasspy/hassio-addons repository[0m
[32m23-09-06 11:33:00 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository[0m
[32m23-09-06 11:33:00 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository[0m
[32m23-09-06 11:33:00 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json[0m
[32m23-09-06 11:33:02 INFO (MainThread) [supervisor.store] Loading add-ons from store: 87 all - 0 new - 0 remove[0m
[32m23-09-06 11:33:02 INFO (MainThread) [supervisor.store] Loading add-ons from store: 87 all - 0 new - 0 remove[0m
```

## System Information

version | core-2023.8.4
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.4
os_name | Linux
os_version | 6.1.0-11-amd64
arch | x86_64
timezone | Australia/Sydney
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.32.1
Stage | running
Available Repositories | 1278
Downloaded Repositories | 35

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 43

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Debian GNU/Linux 12 (bookworm)
-- | --
update_channel | stable
supervisor_version | supervisor-2023.08.3
agent_version | 1.5.1
docker_version | 24.0.5
disk_total | 226.7 GB
disk_used | 22.8 GB
healthy | failed to load: Unhealthy
supported | true
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.6.0), Mosquitto broker (6.3.0), Terminal & SSH (9.7.1), TasmoAdmin (0.25.0), Samba share (10.0.2), Zigbee2MQTT (1.33.0-1), ESPHome (2023.8.2), Samba Backup (5.2.0), Studio Code Server (5.10.1), AdGuard Home (4.8.14), InfluxDB (4.7.0), ecowitt2mqtt (2023.08.0), TheengsGateway (1.8.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 22
views | 12
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 31 August 2023 at 04:05
-- | --
current_recorder_run | 5 September 2023 at 15:55
estimated_db_size | 617.60 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Supervisor diagnostics

[config_entry-hassio-7a73223a819f0cf9edd92dd4da339ecd.json(1).txt](https://github.com/home-assistant/supervisor/files/12530114/config_entry-hassio-7a73223a819f0cf9edd92dd4da339ecd.json.1.txt)

**Comment by agners** [comment] 2023-09-06 06:49
It seems that the unhealthy reason privileged can be caused when Supervisor has problems starting the hardware monitor.

Your log should have more details further up. When this happens again, can you get more log lines? You can use

```
ha host logs -t hassio_supervisor -n 10000
```

Or redirect into a file:

```
ha host logs -t hassio_supervisor -n 10000 > /config/supervisor.log
```

**Comment by aIexus** [comment] 2023-09-06 18:51
Seems like the same as #4381

**Comment by EinSchwerd** [comment] 2023-09-06 22:47
It indeed seems like #4381 as the supervisor recovered after a restart
I'll record the logs when it occurs again.

**Comment by mdegat01** [comment] 2023-09-08 15:14
This is a Supervised installation, not an HAOS one. Closing as a duplicate of #4381

**Closed by mdegat01** 2023-09-08 15:14 UTC
Labels: bug, supervised
