### ISSUE TITLE
Update ipv6 forwarding rules from add-on

### ISSUE THREAD

**Issue by GabrielePicco** [home-assistant/supervisor#1592] opened 2020-03-16 16:24 UTC
Hi,

I'm trying to create a [Wireguard client add-on](https://github.com/GabrielePicco/home-assistant-wireguard-client-addon) that require to updated some forwarding rules. On the startup of the add-on, I get the following error: 
`Setting key "net.ipv6.conf.default.forwarding": Read-only file system`.
Manually launching the container with --priviled works, but with hassio it doesn't seem possible. Is there an alternative solution? mounting a device?

Possible related issue: #201 

Thanks in advance.

**Comment by frenck** [comment] 2020-03-16 17:21
You are opening the same issue now again.

Duplicate of: #1588

**Closed by frenck** 2020-03-16 17:21 UTC

**Comment by GabrielePicco** [comment] 2020-03-16 17:36
@frenck the issue is different. 
I'm asking if anyone knows of an alternative for updating the ipv6 forwarding rules (knowing that I can't run an addon with --privileged).
Please reopen the issue, maybe someone has an alternative solution.

**Comment by frenck** [comment] 2020-03-16 19:10
I did answer your question already: you can't.

**Comment by GabrielePicco** [comment] 2020-03-16 19:20
I guess it is possible to mount a device in a similar way to what they did in #201 to overcame the issue, since the error is `Setting key "net.ipv6.conf.default.forwarding": Read-only file system`.
Don't be arrogant and reopen the issue. Maybe someone knows a solution.

**Comment by frenck** [comment] 2020-03-16 20:17
> Don't be arrogant and reopen the issue.

It is a read-only file system...

We don't provide means for it in the ecosystem.

Please don't call me out arrogant, because the answer didn't isn't what you wanted to hear. That was not called for.
