### ISSUE TITLE
Node-RED communication BLOCKED when an update(s) waiting.

### ISSUE THREAD

**Issue by Mitchell-kw-Lee** [home-assistant/supervisor#3813] opened 2022-08-20 22:54 UTC
### The problem

When update waiting, Node-RED communication blocked.
I'm telling you the problem occur when updates WAITING not by auto-update.
(do not know which update waiting exactly)
This is not recent problem but over years.
There is none of network and communication issue at all.
its Home assistant problem.
The reason why now reporting you is that no one care about old core issue
that make 24 hours system damage.

An also telling you that, 
do STOP shitty almost daily update
this is home automation operating system,
not your toy that update fun.
Do professionally open and distribute new update by monthly or quarterly.

Symptom.
- When the 'Core' update waiting, Node-RED's all TCP communication blocked.
- So node red not working. no commend out to Tasmotas and not responding to Alexa.
- After while passes with update waiting, sometime everythings working even though there is update waiting.

### What version of Home Assistant Core has the issue?

Every version within 1 year past at least. recently 22.7.x, 22.8.x

### What was the last working version of Home Assistant Core?

2022.8.6

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

let me know how to.

### Anything in the logs that might be useful for us?

```txt
let me know how to.
```

**Comment by frenck** [comment] 2022-08-21 16:38
This sounds like a Supervisor related issue, not a Core released issue. Transferred to issue to the Supervisor issue tracker.

**Comment by mdegat01** [comment] 2022-08-24 23:25
Your logs can be found [Settings -> System -> Logs](https://my.home-assistant.io/redirect/logs/). At the top you can switch between the different loggers (core, supervisor and node red). Please share any errors you see related to updates, timeouts, etc.

I have never heard anything like this before either in issues here or on the forum and I spend a lot of time in both. I also have been using Node RED myself for several users and have left HA updates pending many times, never once had this issue. It also doesn't really make any sense, the two things have no relationship to each other. So you're going to have to share some more details about your setup and what you're seeing if you want to get this resolved.

**Comment by Mitchell-kw-Lee** [comment] 2022-08-24 23:30
The reason why you guys never heard must be not deltaily care about.
Set the variable in Node RED set null when it started.
And manually set the value to anything but null. Automatically or real
manually whatever you want.
Sometime Node RED restart without clue.
And when any of update(ocre, node red, os) waiting,
Node red cannot communicate with outside (especially URL Hook).

That is you guys fault that not so professionally understand your product.

So,
STOP daily update
and fix damn bug.
It really has been 2 years or more.
So,
also stop 'i didnt know that' thing like dumb.

**Comment by mdegat01** [comment] 2022-08-24 23:48
Please provide actual steps to reproduce your issue. I have no idea how to follow this:
> Set the variable in Node RED set null when it started.
> And manually set the value to anything but null. Automatically or real
> manually whatever you want.
> Sometime Node RED restart without clue.
> And when any of update(ocre, node red, os) waiting,
> Node red cannot communicate with outside (especially URL Hook). 

A node RED export is fine if you have that. I have systems with updates pending already.

> STOP daily update

The only thing that updates daily is the dev channel. If you are on that, you might want to switch to `stable`. The dev/nightly channel is not known for being particularly stable in any product I've ever used, Home Assistant is no exception.

Also consider this a warning. Your tone is unacceptable. I'm sorry you have been facing an issue for so long but it sounds like its been in the wrong place and I've only been aware of it for a week. I'm willing to help but not if you are going to disparage the developers of this product.

**Comment by Mitchell-kw-Lee** [comment] 2022-08-25 00:15
- System update pending and variable matter is a totally different issue.
isolated one. you can forget the variable one. Just focus the communication
blacking matters only.
- Also no clue the communication block issue occurs. For now, I do not
believe I have relevant log for the situation. Will share to you later when
the situation comes.
that I get notice when Alexa is not responding(but just ack blinking or
tone acknowledges) or say 'xxx not responding ' when I voice command. Or
not automatically home electronics on and off. overnight damn. Very weird.
not automatically on or off means the system does not get a URL hook from
arduino and alexa.
- Sometimes, in the Node RED, I manually command(by the manual
button/switch that I prepared for an emergency situation), also not working
like yesterday when the OS update was waiting. So did the OS update when
the early morning was busy. Why does HA make life harder? not easier.
- Where is the menu that switches the stable channel? I do not believe
myself to choose the unstable thing but will check. (recently you guys
changed major ui things as you want without manual distribution.
didn't find the restart button and core restart button when an emergency
occured. Just an open publishing release note is not enough. when you
change operation manners suddenly, you must include a manual inside the
product not outside dozens of pages of a web page that cannot find the
exact contents of that long long text set.)
- Good point about disparagement, I do not care about your personal ego
matters since this is a really community product since it was born. Global
people made the product ecosystem, Q&A, plugin, etc. so I respect the
entire ecosystem. (I even pay for every month worth). Whether you ignore
the issue or not, it exists in the HA that people are not aware or skip or
passing that cannot know until it is facing.
- For now, no fit logs or information since it is not reproducible atm.

**Comment by Mitchell-kw-Lee** [comment] 2022-08-25 03:08
I have figured it out now that
the major two modules of the issue in Node REDs are
- 'Alexa Routine node' that is not responding by an inject node when an
update is waiting.
- 'Alexa Event node' not responding by Alexa voice command when an update
is waiting.

**Comment by mdegat01** [comment] 2022-08-25 12:45
> After while passes with update waiting, sometime everythings working even though there is update waiting.

Are you certain the issue is caused by an update pending? That doesn't really make any sense to me because the API (what Node RED and Alexa use to talk to HA) aren't affected by that. Also this comment in your initial post suggests there might be something else going on since it seems to fix itself eventually. Is there a pattern to the communication drops? Like does it happen around the same time every day? And is there anything else happening in supervisor around those times?

> Where is the menu that switches the stable channel?

You actually can't switch to `dev` channel in the UI if you're truly on that. You can switch between `stable` and `beta` from the 3 dots menu in the top right of [Settings -> System -> Updates](https://my.home-assistant.io/redirect/updates/). Or just enter this in the CLI
```
ha supervisor options --channel stable
```
> - 'Alexa Routine node' that is not responding by an inject node when an
> update is waiting.
> - 'Alexa Event node' not responding by Alexa voice command when an update
> is waiting.

I don't have either of these nodes in my Node RED addon. Can you link to the module you installed so I can look at it? Although I have to say if these are the only two nodes broken there's not going to be much I can do about it since that is a 3rd party addon within an entirely different product (node red). Are you able to reproduce it with just out of the box nodes from the addon? Like an inject node into a call service node or one of the other HA nodes for instance.

**Comment by Mitchell-kw-Lee** [comment] 2022-08-25 13:22
- Agree, weird in common sense.
but the symptoms exist. that really connected to the update pending the
problem only occurs when it is waiting.
usually only occur node red's self-restart from time to time.
if you have any way to log entirely, will set up for you.

- I'm on a stable channel. means, unnecessarily frequent updates(core, os,
node-red, others. separately)
Telling you(or suggesting whatever you take), align the release date on a
day. only monthly or quarterly. event half.
[image: image.png]

- The nodes I indicate are some examples, as I told you that the 'URL hook'
via HA to Node RED is also not working.

- Regarding reproducing, that is never reproducible when no update is
pending, so sure.
Lights and lots of things, air-conditioner, fans connected to Node RED
24/7,
so something is wrong, I noticed right away. If you stop updating, it will
be fine. Before you guys started frequent updates with your new design, it
was really long term stable. Nearly forgot HA back there in my life.
(Except the clueless node-red self-restart. When it's self-restarted, it
makes a global variable in node-red go to null(of course) that is
monitored by isolated infinite node-red logic to monitor the variable until
manually set, Alexa speaks out to set the variable in 10 seconds to
indicate null. so that i noticed and every IoT device stopped working until
its set.).

- One thing that needs to be investigated should be to check the duration
between update pending start time and the symptom update time. and both
logs at that time. do not know how to detect to notify the update pending
from Node Red or HA.
Have no idea why the update package(background downloaded?) affect to the
system.

 Have no idea whether the supervisor thing only has a single thread
structure that is missing other processes to proceed
but it happened. holding downloaded packages or memory leaks. In my memory,
there is no update pending, no problem with me. This is a very old issue.
If you use python for the update process,
you really carefully allocate and explicitly free/dealloc variables in
Python which lead to memory trouble.
I'm telling you about as a python expert. you must not believe in python
that much. Treat python like C/C++ for a stable system.

HA on RPI4 Samsung Pro Plus 128GB SDCard that A2 supports high performance
with MariaDB.
[image: image.png]

And plus,
make another update in the HACS integration/addon that auto-updates.
Why does it only require core restart? no consistency and very annoying
by frequent ZHA core module updates these days since there are my Zigbees
connected.

**Comment by mdegat01** [comment] 2022-08-25 13:50
> so something is wrong, I noticed right away. If you stop updating, it will
> be fine.

Wait. I need you to clarify what you mean by update pending.

I thought update pending meant if you went to settings you saw a notification about an update. Hence pending.

But this comment makes me think you are having this issue when you are actually *applying* an update. Like you applied an update and until it is done communication from Node RED to HA is broken.

If you mean the second one then this totally makes sense and its not an issue. HA cannot respond to API requests from Node RED while an update is actually in progress for supervisor, core, OS or Node RED itself. Communication will break while actually executing an update for any of those and return after. That's not a bug. Updates take it offline and bring it back online again when complete, that's how it works.

**Comment by Mitchell-kw-Lee** [comment] 2022-08-25 14:05
- Update pending or waiting that term is indicated when the yellow(orange?)
color icon on the menu 'Settings' has NOT been applied. so pending.

- After submitting an update on the detail popup menu to update, the
symptom disappears usually rebooted.

So that is an issue. not second. I'm not that much dumb.

**Comment by Mitchell-kw-Lee** [comment] 2022-08-28 23:52
Is this log what you want?
Seems your monthly pay service problem?

----
https://mitchell.hopto.org:8123/lovelace/default_view:0:0 Uncaught
8:48:45 AM – (ERROR) components/system_log/__init__.py - message first
occurred at August 24, 2022 at 7:34:23 AM and shows up 21 times

Script-Kitchen Light Turn Off: Already running
8:41:17 AM – (WARNING) Script - message first occurred at August 24, 2022
at 8:31:40 AM and shows up 121 times

Config entry 'Z-Wave JS' for zwave_js integration not ready yet: Failed to
connect: Cannot connect to host core-zwave-js:3000 ssl:default [Connect
call failed ('172.30.33.3', 3000)]; Retrying in background
August 28, 2022 at 11:36:45 PM – (WARNING) config_entries.py



*Error when sending ChangeReport for switch.washroom_fan_power to Alexa:
THROTTLING_EXCEPTION: Request could not be processed due to
throttling.August 28, 2022 at 9:00:30 PM – (ERROR) Amazon Alexa - message
first occurred at August 28, 2022 at 12:00:01 PM and shows up 6 times*


*Error fetching openweathermap data: Unable to contact the upstream
serverAugust 26, 2022 at 3:30:23 PM – (ERROR) OpenWeatherMap - message
first occurred at August 25, 2022 at 3:17:45 PM and shows up 2 times*
Received unexpected bridge id: 93eadbeef13
August 24, 2022 at 7:35:53 AM – (WARNING) components/hue/config_flow.py -
message first occurred at August 24, 2022 at 7:35:53 AM and shows up 5 times

The unit of sensor.openweathermap_visibility (m) does not match the unit of
already compiled statistics (km). Generation of long term statistics will
be suppressed unless the unit changes back to km. Go to
https://my.home-assistant.io/redirect/developer_statistics to fix this
August 24, 2022 at 7:35:21 AM – (WARNING) Sensor

Config entry 'M9Plus' for upnp integration not ready yet: Error connecting
to device at location: http://[::1e3b:f3ff:fe78:e0a9]:1900/rootDesc.xml,
err: ("ClientConnectorError(ConnectionKey(host='::1e3b:f3ff:fe78:e0a9',
port=1900, is_ssl=False, ssl=None, proxy=None, proxy_auth=None,
proxy_headers_hash=-2777355656432708404), OSError(101, 'Network
unreachable'))", None); Retrying in background
August 24, 2022 at 7:34:20 AM – (WARNING) config_entries.py

The 'google' option near /config/configuration.yaml:2 is deprecated, please
remove it from your configuration
August 24, 2022 at 7:34:20 AM – (WARNING) Google Calendars

The mjpeg platform for the camera integration does not support platform
setup. Please remove it from your config.
August 24, 2022 at 7:34:06 AM – (ERROR) Camera

The 'purge_interval' option near /config/configuration.yaml:120 is
deprecated, please remove it from your configuration
August 24, 2022 at 7:33:51 AM – (WARNING) Recorder

The 'base_url' option near /config/configuration.yaml:93 is deprecated,
please remove it from your configuration
August 24, 2022 at 7:33:50 AM – (WARNING) HTTP
----

**Comment by Mitchell-kw-Lee** [comment] 2022-08-28 23:56
FYI,
Here is (GMT+9) refer when you find the match log from AWS.

**Comment by Mitchell-kw-Lee** [comment] 2022-09-01 11:50
And another log of your part.

nothing fixed since the error newly occurred again.
The SENDING you logs means
each time HA keep making errors that are not working by the inherent defect.

**==
Timeout sending report to Alexa for sensor.processor_temperature
August 30, 2022 at 4:37:24 PM – (ERROR) Amazon Alexa - message first occurred at August 30, 2022 at 4:36:54 PM and shows up 5 times
Error fetching hassio data: Error on Supervisor API:
August 30, 2022 at 9:06:22 AM – (ERROR) Home Assistant Supervisor
Client error on /info request Cannot connect to host [172.30.32.2:80](http://172.30.32.2/) ssl:default [Connect call failed ('172.30.32.2', 80)]
August 30, 2022 at 9:06:22 AM – (ERROR) Home Assistant Supervisor - message first occurred at August 30, 2022 at 9:06:22 AM and shows up 4 times
==**

**Comment by Mitchell-kw-Lee** [comment] 2022-09-01 11:51
Is this log what you want?
Seems your monthly pay service problem?

----
https://mitchell.hopto.org:8123/lovelace/default_view:0:0 Uncaught
8:48:45 AM – (ERROR) components/system_log/__init__.py - message first occurred at August 24, 2022 at 7:34:23 AM and shows up 21 times

Script-Kitchen Light Turn Off: Already running
8:41:17 AM – (WARNING) Script - message first occurred at August 24, 2022 at 8:31:40 AM and shows up 121 times

Config entry 'Z-Wave JS' for zwave_js integration not ready yet: Failed to connect: Cannot connect to host core-zwave-js:3000 ssl:default [Connect call failed ('172.30.33.3', 3000)]; Retrying in background
August 28, 2022 at 11:36:45 PM – (WARNING) config_entries.py

**Error when sending ChangeReport for switch.washroom_fan_power to Alexa: THROTTLING_EXCEPTION: Request could not be processed due to throttling.
August 28, 2022 at 9:00:30 PM – (ERROR) Amazon Alexa - message first occurred at August 28, 2022 at 12:00:01 PM and shows up 6 times**

Error fetching openweathermap data: Unable to contact the upstream server
August 26, 2022 at 3:30:23 PM – (ERROR) OpenWeatherMap - message first occurred at August 25, 2022 at 3:17:45 PM and shows up 2 times

Received unexpected bridge id: 93eadbeef13
August 24, 2022 at 7:35:53 AM – (WARNING) components/hue/config_flow.py - message first occurred at August 24, 2022 at 7:35:53 AM and shows up 5 times

The unit of sensor.openweathermap_visibility (m) does not match the unit of already compiled statistics (km). Generation of long term statistics will be suppressed unless the unit changes back to km. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this
August 24, 2022 at 7:35:21 AM – (WARNING) Sensor

Config entry 'M9Plus' for upnp integration not ready yet: Error connecting to device at location: http://[::1e3b:f3ff:fe78:e0a9]:1900/rootDesc.xml, err: ("ClientConnectorError(ConnectionKey(host='::1e3b:f3ff:fe78:e0a9', port=1900, is_ssl=False, ssl=None, proxy=None, proxy_auth=None, proxy_headers_hash=-2777355656432708404), OSError(101, 'Network unreachable'))", None); Retrying in background
August 24, 2022 at 7:34:20 AM – (WARNING) config_entries.py

The 'google' option near /config/configuration.yaml:2 is deprecated, please remove it from your configuration
August 24, 2022 at 7:34:20 AM – (WARNING) Google Calendars

The mjpeg platform for the camera integration does not support platform setup. Please remove it from your config.
August 24, 2022 at 7:34:06 AM – (ERROR) Camera

The 'purge_interval' option near /config/configuration.yaml:120 is deprecated, please remove it from your configuration
August 24, 2022 at 7:33:51 AM – (WARNING) Recorder

The 'base_url' option near /config/configuration.yaml:93 is deprecated, please remove it from your configuration
August 24, 2022 at 7:33:50 AM – (WARNING) HTTP
----

**Comment by mdegat01** [comment] 2022-09-01 19:16
> Here is (GMT+9) refer when you find the match log from AWS.

I don't have any AWS logs? Not sure what you're referring to here

> Error when sending ChangeReport for switch.washroom_fan_power to Alexa: THROTTLING_EXCEPTION: Request could not be processed due to throttling.
> August 28, 2022 at 9:00:30 PM – (ERROR) Amazon Alexa - message first occurred at August 28, 2022 at 12:00:01 PM and shows up 6 times

This seems like https://github.com/home-assistant/core/issues/64860 . Which is caused by an entity changing state too quickly and hitting an Amazon limit. I don't believe its a limit we have any control over but you're welcome to create an issue specifically about that log entry in the core repository if you want to see if it can be changed.

**Comment by Mitchell-kw-Lee** [comment] 2022-09-01 21:10
First of all, I'm not talking to only you, but your team. So you can find out right person internally.
Second, regarding the AWS things, the only way to communicate with Alexa from HA is by supporting server side program(Amazon called it as the Skill).
So, now what I can link HA with Alexa is paying HA monthly service which you guys monthly service supporting Alexa connection service within your monthly pay. Means you guys have own Alexa Skill and own AWS backend(assume the Lambda function) to support Alexa for HA.
All is under HA team control.

**Comment by Mitchell-kw-Lee** [comment] 2022-09-01 21:11
refer : https://www.home-assistant.io/integrations/alexa

**Comment by Mitchell-kw-Lee** [comment] 2022-09-01 21:11
either : https://www.home-assistant.io/integrations/alexa#automatic-setup-via-home-assistant-cloud that about your monthly pay system.

**Comment by Mitchell-kw-Lee** [comment] 2022-09-01 21:38
You can find the people who run the https://nabucasa.com/.

**Comment by mdegat01** [comment] 2022-09-01 21:41
I feel like you're assuming we have way more data then we do. The entire service is privacy focused. I would guess that there are logs of the Alexa skill that the cloud folks have access to but nothing is going to be identifiable to a particular system. And there are tons of users streaming state changes to Alexa so there's really not a way to pick your traffic out.

I also have zero access to your systems logs other then what you share here. As for what you're sharing me the only relevant looking error I've seen is this:
> Error when sending ChangeReport for switch.washroom_fan_power to Alexa: THROTTLING_EXCEPTION: Request could not be processed due to throttling.
> August 28, 2022 at 9:00:30 PM – (ERROR) Amazon Alexa - message first occurred at August 28, 2022 at 12:00:01 PM and shows up 6 times

And like I said above, Amazon is rate-limiting you. You have a device that is changing too rapidly. I don't believe that limit can be changed but I honestly don't know. You're welcome to copy and paste that particular log entry into a [core issue](https://github.com/home-assistant/core/issues) and ask the maintainers of that integration.

**Comment by Mitchell-kw-Lee** [comment] 2022-09-01 21:43
How to get the detail log what you want? (I do not believe I can get the past log at this moment.)

**Comment by Mitchell-kw-Lee** [comment] 2022-09-01 21:47
And I'm not assuming 'data' you have. But AWS Account usage limit that can be resolved by AWS service ticket when only the account owner ask for.

**Comment by Mitchell-kw-Lee** [comment] 2022-09-02 00:43
By refering https://aws.amazon.com/premiumsupport/knowledge-center/lambda-troubleshoot-throttling/?nc1=h_ls
you guys ask AWS that increase concurrency limit.

**Comment by Mitchell-kw-Lee** [comment] 2022-09-02 00:47
The symptom seems that around your new update release, Alexa components make connection renew which means increase lambda usage peak temporarily also hit the concurrency limit of AWS Lambda.
So, the responsibility of the issue is purely on you guys as a pay service.

**Comment by Mitchell-kw-Lee** [comment] 2022-09-02 00:48
Best refering : https://docs.aws.amazon.com/lambda/latest/dg/invocation-scaling.html

**Comment by mdegat01** [comment] 2022-09-02 20:38
Ok. It seems like at this point this isn't a supervisor issue. If you have an issue with the cloud service you can create a ticket [here](https://www.nabucasa.com/support/). If you have an issue with the way the Alexa integration works you can create an issue or PR for that [here](https://github.com/home-assistant/core/issues). This repo is only about supervisor issues, so it appears to be in the wrong place.

I will note that I just searched core issues and I see zero reports of `THROTTLING_EXCEPTION`. So I don't actually believe that anything is systemically wrong with the way it is working otherwise there would be a lot more issues. If you have proof showing otherwise then please lay it out in an issue there. Nothing you're showing me above suggests that to me currently.

As for the cloud service limits, you're more then welcome to request an increase. That being said, there is no obligation for Nabu Casa to do so. The limits are set based on the price of the service. If you are blowing through them then you'll either need to add some throttling by exposing less entities or different entities or switch to the manual Alexa mode as documented in the Integration and pay Amazon based on usage.

**Closed by mdegat01** 2022-09-02 20:38 UTC

**Comment by Mitchell-kw-Lee** [comment] 2022-09-02 22:34
Fir of all, VERY DISAPPOINTED at your responses. 

For the record, to the all user of home assistant.
- The problem of this issue from the AWS account of the nabucasa(?) which contain the Alexa skill to link your monthly pay service with each HA pay account. not users. Your organization's obligation that you simply ignore.
- Totally do not believe your level of understanding of the own organization's technology that too low.
- This was the good chance to glimpse level of the member of the technical understanding of a core founder of the pay service. No doubt that this is an armature gathering(nabucasa? is that a starwars thing?) have no professionalism.

For the record, to you.
- This issue came from the 'core' part by transferring one who in charge or the core. But you can't/don't do the same thing to be transferred back. Why you don't have the authority? Your personal problem?
- No professionals say, 'not our obligation' or 'this is not my issue' or 'you customer find other right person yourself' on a group of paying service who taking MONEY from consumer. As for free service, also no professional do that.

And thank you to remind me that no reason to pay due to this group just doing what they feel fun by taking money from outside. Have no find any higher level of purpose.

FYI, self AWS Skill implementation if way cheaper than your monthly $6.5 pay include issuing 10 years certification.
So long.
