### ISSUE TITLE
Available space is less than 1GB! -- forever, wont stop notifying me

### ISSUE THREAD

**Issue by stevetz** [home-assistant/supervisor#2314] opened 2020-11-30 10:51 UTC
Available space is less than 1GB! -- forever, wont stop notifying me. I did have lower than 1GB space, but have corrected to be >10GB, yet I keep getting the low space notification. I can't work out if it's a supervisor issue or core?

1. had lower than 1GB storage space
2. received notification in frontend
3. Cleared some files
4. now have more than 1GB space available.
5. Still getting frequent notifications.
![asd](https://user-images.githubusercontent.com/58637329/100601357-61442200-32fa-11eb-87b2-bb91d3abf381.jpg)

### Enviroment details

- **Operating System:**: HassOS 4.17
- **Supervisor version:**: 2020.11.0
- **Home Assistant version**: 0.118.4

### Supervisor logs

<details>
<summary>Supervisor logs</summary>

```
Can provide logs if necessary, but nothing useful showing in any of the supervisor, core, host logs which seems helpful

```

</details>

**Comment by ludeeus** [comment] 2020-11-30 10:58
This is a duplicate of https://github.com/home-assistant/supervisor/issues/2256 which is fixed in the Supervisor version that is currently on the beta channel.

**Closed by ludeeus** 2020-11-30 10:58 UTC
Labels: bug
