### ISSUE TITLE
Custom repositories gone

### ISSUE THREAD

**Issue by andriej** [home-assistant/supervisor#1709] opened 2020-05-08 09:50 UTC
**Home Assistant release with the issue:**

0.109.6 / latest 221 supervisor

**Operating environment (HassOS/Generic):**

Supervised HA on Debian

**Supervisor logs:**

n/a

**Description of problem:**
After latest supervisor update, the panel with possibility to add/delete custom repositories is gone.
I'd like to delete one, I can't.
It was above search button:
![image](https://user-images.githubusercontent.com/6303489/81394312-0b234d80-9122-11ea-9f5f-d0a8cbf3346a.png)

**Comment by ludeeus** [comment] 2020-05-08 09:51
duplicate of https://github.com/home-assistant/frontend/issues/5807

**Closed by ludeeus** 2020-05-08 09:51 UTC

**Comment by andriej** [comment] 2020-05-08 09:56
Didn't see the frontend issue, thx.
