### ISSUE TITLE
Snapshot loading wrong image during on boarding restore

### ISSUE THREAD

**Issue by bschatzow** [home-assistant/supervisor#2683] opened 2021-03-04 21:35 UTC
### Describe the issue you are experiencing

Just did a new setup and tried to load the snapshot during on boarding.  The snapshot downloaded as it should after the screen came up with what to restore, all, partial and you click to proceed.  The on boarding create log on reloads.  

### What is the used version of the Supervisor?

supervisor-2021.03.4

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

5.12 when it was installing

### What version of Home Assistant Core is installed?

core-2021.3.0

### Steps to reproduce the issue

1. Burn image via etcher
2. Boot image
3. restore via onboarding
Tried the same way several times and all behaved the same.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
# Put your logs below this line
N/A
```

More confusing to a user especially that just had a system crash and is trying to get back running.

**Comment by aventu90** [comment] 2021-03-04 22:15
Same here, I can't restore my snapshot.
Ironically I reflashed my rpi4 sdcard because supervisor couldn't download anything.
'21-03-04 22:01:15 WARNING (MainThread) [supervisor.jobs] 'AddonManager.install' blocked from execution, no host internet connection'
In the end I made it worse, because:
`21-03-04 22:03:26 WARNING (MainThread) [supervisor.jobs] 'SnapshotManager.do_restore_full' blocked from execution, no host internet connection`
Flashing old versions doesn't help because it always wants to download the newest version of supervisor..

**Comment by ludeeus** [comment] 2021-03-05 09:48
> The on boarding create log on reloads.

When you open issues, include the errors.
There is nothing to go on here.

**Comment by aventu90** [comment] 2021-03-05 11:24
> 
> 
> > The on boarding create log on reloads.
> 
> When you open issues, include the errors.
> There is nothing to go on here.

In his defense, there is no error. It just didn't work. And it's tricky to get to the logs when you are stuck on the "create user or restore snapshot" screen. If his problem is related to mine, it should be resolved by now. But that's speculation.

**Comment by ludeeus** [comment] 2021-03-05 11:30
"It didn't work" does not explain _anything_, what did not work? clicking the text? upload? selecting things to restore? clicking the button? the restore? what happened?

**Comment by aventu90** [comment] 2021-03-05 11:44
> 
> 
> "It didn't work" does not explain _anything_, what did not work? clicking the text? upload? selecting things to restore? clicking the button? the restore? what happened?

I already posted the exact error message. Please look at my first post.
But here is exactly what happens visually:

1. On the first start, you click "restore/upload snapshot". The upload of the snapshot works.
2. It displays the recovery dialog where you can select what you want to restore (partially, everything, etc)
3. No matter what you select, after clicking restore, the window disappears and you are back at the user creation screen.
4. I created a new user to see how it behaves. The creation works.
5. HA was now unable to download Plug-Ins: `21-03-04 22:01:15 WARNING (MainThread) [supervisor.jobs] 'AddonManager.install' blocked from execution, no host internet connection` It definitely has (or had) internet connection because it downloaded data at the 20min setup screen.
6. HA was still unable to restore snapshots, because `21-03-04 22:03:26 WARNING (MainThread) [supervisor.jobs] 'SnapshotManager.do_restore_full' blocked from execution, no host internet connection`

A few hours later it worked again. Maybe an DNS issue? I really don't know. The problem resolved itself for me. But it might be helpful for the future.

Thank you for your time and best regards.

**Comment by ludeeus** [comment] 2021-03-05 11:48
Okey, so the host did not have internet access, which is needed during restore.

**Comment by aventu90** [comment] 2021-03-05 11:51
Yes, but only after the 20min setup. It definitely downloaded data during that time. The issue was reproducible with router restart.

**Comment by ludeeus** [comment] 2021-03-05 11:52
It does a check every 30s while the connection is down, once it's live again it should work as expected.
It does not have to be local, it can be ISP related.

**Comment by forast3r** [comment] 2021-04-21 18:56
Some very similar happened to me recently. Trying to mount an emergency backup of my existing setup due to a broken disk.
Can't we restore an existing snapshot without internet? Really?
Imagine the family drama if we can't restore the house control if the server broke and also the internet connection...

> WARNING (MainThread) [supervisor.jobs] 'SnapshotManager.do_restore_partial' blocked from execution, no supervisor internet connection

**Comment by bschatzow** [comment] 2021-04-27 08:53
My initial post is not saying it doesn't restore, it says the wrong image is being loaded. I have been testing a lot of different configurations lately and thus doing a lot of restores. What happens again is you get to the screen to create a user or upload a snapshot. If you choose snapshot it downloads the snapshot and asks you what to restore. When you click restore everything, for example, it goes back to the create user screen. Tried it many times with different versions over the last 5 months and it is always the same. The screen should go to restoring snapshot for example.

**Comment by ludeeus** [comment] 2021-04-27 09:06
If that is the case, you will have browser console logs, and supervisor logs you should paste in the issue.

**Comment by bschatzow** [comment] 2021-04-27 09:25
@ludeeus Where do I find the browser console logs and supervisor logs.  I thought ( I guess incorrectly) that when I did the snapshot restore the logs during this process where not saved.

**Comment by ludeeus** [comment] 2021-04-27 10:02
browser console depends on your browser, google "BROWSERNAME console", `ha su logs` for supervisor logs

**Comment by bschatzow** [comment] 2021-04-27 11:50
@ludeeus I believe neither is available now.  I use chrome and I know how to get to the console. Next time I'll try and capture this. I'm surprised that no one else sees this issue?

**Comment by bschatzow** [comment] 2021-04-27 15:18
@ludeeus 
What should I be seeing when doing a snapshot restore?

**Comment by ludeeus** [comment] 2021-04-27 15:19
a spinner

**Comment by bschatzow** [comment] 2021-04-27 15:27
@ludeeus I see the spinner when the image is downloading, then I get the option to restore and then when I click on it it goes back to the original screen (create user, etc)

**Comment by ludeeus** [comment] 2021-04-27 15:31
Sounds like a browser/frontend bug, can you open frontend issue for that (and fill out the template in that issue)?

**Comment by ludeeus** [comment] 2021-06-03 15:32
https://github.com/home-assistant/frontend/issues/9009

**Closed by ludeeus** 2021-06-03 15:32 UTC

**Comment by bschatzow** [comment] 2021-06-03 16:59
@ludeeus 
I opened the issue under frontend as you asked.  bramkragten marked it as supervisor.
Not sure what to do. I do not know where the issue belongs.

**Comment by ludeeus** [comment] 2021-06-03 16:59
Where it is now

**Comment by bschatzow** [comment] 2021-06-03 17:09
https://github.com/home-assistant/frontend/issues/9009

**Comment by ludeeus** [comment] 2021-06-03 17:33
Yes? That's the _exact_ same issue as i posted...

**Comment by bschatzow** [comment] 2021-06-03 17:35
@ludeeus 
Yes, But he labeled it supervisor, not front end
