### ISSUE TITLE
Supervisor on 109.2 HA have issue with hamburger menu

### ISSUE THREAD

**Issue by shirou93** [home-assistant/supervisor#1693] opened 2020-05-02 09:23 UTC
When i open supervisor i don't have hamburger menu and new menu on the bottom of the screen appear after 1-5 seconds. Android app.

![Screenshot_20200502-112108](https://user-images.githubusercontent.com/59237288/80860304-0f092880-8c67-11ea-86d0-aa65dca62775.jpg)

**Comment by ludeeus** [comment] 2020-05-02 09:29
Duplicate of https://github.com/home-assistant/frontend/issues/5702

**Closed by ludeeus** 2020-05-02 09:29 UTC
