### ISSUE TITLE
Please do not delete the repository

### ISSUE THREAD

**Issue by neroxps** [home-assistant/supervisor#2799] opened 2021-04-10 02:37 UTC
### Describe the issue you are experiencing

Because the GitHub access network in mainland China is not stable

As a result, the Supervisor fetches addons repositories sometimes fail

If the pull fails, the Supervisor will delete the repository

If the supervisor fails to fetch the repository, do not delete the repository

### What is the used version of the Supervisor?

supervisor-2021.03.9

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Debian

### What is the version of your installed operating system?

Debian GNU/Linux 10 (buster)

### What version of Home Assistant Core is installed?

core-2021.4.2

### Steps to reproduce the issue

The system runs automatically without operation

### Anything in the Supervisor logs that might be useful for us?

```txt
21-04-10 09:29:22 INFO (MainThread) [supervisor.store.git] Cloning add-on https://github.com/hassio-addons/repository repository
21-04-10 09:31:23 ERROR (MainThread) [supervisor.store.git] Can't clone https://github.com/hassio-addons/repository repository: Cmd('git') failed due to: exit code(128)
  cmdline: git clone --depth=1 --recursive --shallow-submodules -v https://github.com/hassio-addons/repository /data/addons/git/a0d7b954
  stderr: 'Cloning into '/data/addons/git/a0d7b954'...
fatal: unable to access 'https://github.com/hassio-addons/repository/': Empty reply from server
```

**Comment by Waer28** [comment] 2021-04-10 04:36
I also met the situation of consent. It would be great if it could be solved

**Comment by pvizeli** [comment] 2021-04-10 22:48
Duplicate of https://github.com/home-assistant/supervisor/issues/2774 - the issue is, you can't clone it not pull it (according your log)

**Closed by pvizeli** 2021-04-10 22:48 UTC
Labels: bug
