### ISSUE TITLE
supervisor-2021.09.6 RROR (MainThread) [asyncio] Task exception was never retrieved future

### ISSUE THREAD

**Issue by casper255** [home-assistant/supervisor#3169] opened 2021-09-29 20:12 UTC
### Describe the issue you are experiencing

Error in logs "ERROR (MainThread) [asyncio] Task exception was never retrieved future"

### What is the used version of the Supervisor?

supervisor-2021.09.6

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

6.4

### What version of Home Assistant Core is installed?

core-2021.9.7

### Steps to reproduce the issue

1.
2.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
21-09-29 21:56:39 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-88883' coro=<HomeAssistantWebSocket.async_send_command() done, defined at /usr/src/supervisor/supervisor/homeassistant/websocket.py:106> exception=TypeError('Received message 257:None is not str')>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/homeassistant/websocket.py", line 134, in async_send_command
    return await self._client.async_send_command(message)
  File "/usr/src/supervisor/supervisor/homeassistant/websocket.py", line 46, in async_send_command
    response = await self.client.receive_json()
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_ws.py", line 291, in receive_json
    data = await self.receive_str(timeout=timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_ws.py", line 276, in receive_str
    raise TypeError(f"Received message {msg.type}:{msg.data!r} is not str")
TypeError: Received message 257:None is not str
```

**Comment by ludeeus** [comment] 2021-10-08 08:05
Duplicate of https://github.com/home-assistant/supervisor/issues/3126

**Closed by ludeeus** 2021-10-08 08:05 UTC
Labels: bug
