### ISSUE TITLE
Memory usage increasing since update to lates Supervisor 22.08.5

### ISSUE THREAD

**Issue by Villa-Buenavista** [home-assistant/supervisor#3833] opened 2022-08-30 14:30 UTC
### Describe the issue you are experiencing

Memory usage was stable on my HA Blue (Odroid-N2) at around 35% and has been increasing since the last update to the mid 60s% at the moment with no end in sight.
![220830 mem usage](https://user-images.githubusercontent.com/36330943/187463488-325f452a-55c0-4a5e-a7c2-07a43efafde3.JPG)

### What is the used version of the Supervisor?

Supervisor 2022.08.5

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

Operating System 8.5

### What version of Home Assistant Core is installed?

Home Assistant 2022.8.7

### Steps to reproduce the issue

1. Update to newest Supervisor
2.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
Warnings about SAMBA but I would think unrelated:

22-08-30 14:32:39 WARNING (MainThread) [supervisor.addons.options] Option 'interface' does not exist in the schema for Samba share (core_samba)
22-08-30 14:33:51 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
22-08-30 14:37:41 WARNING (MainThread) [supervisor.addons.options] Option 'interface' does not exist in the schema for Samba share (core_samba)
22-08-30 14:42:43 WARNING (MainThread) [supervisor.addons.options] Option 'interface' does not exist in the schema for Samba share (core_samba)
22-08-30 14:47:45 WARNING (MainThread) [supervisor.addons.options] Option 'interface' does not exist in the schema for Samba share (core_samba)
22-08-30 14:52:47 WARNING (MainThread) [supervisor.addons.options] Option 'interface' does not exist in the schema for Samba share (core_samba)
22-08-30 14:57:49 WARNING (MainThread) [supervisor.addons.options] Option 'interface' does not exist in the schema for Samba share (core_samba)
22-08-30 15:01:41 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
22-08-30 15:01:41 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DNS_SERVER_FAILED/ContextType.DNS_SERVER
22-08-30 15:01:41 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.NETWORK_CONNECTION_PROBLEM/ContextType.SYSTEM
22-08-30 15:01:41 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DNS_SERVER_IPV6_ERROR/ContextType.DNS_SERVER
22-08-30 15:01:41 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE
22-08-30 15:01:41 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM
22-08-30 15:01:41 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON
22-08-30 15:01:41 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.SUPERVISOR
22-08-30 15:01:41 INFO (MainThread) [supervisor.resolution.check] System checks complete
22-08-30 15:01:41 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
22-08-30 15:01:41 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
22-08-30 15:01:41 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
22-08-30 15:01:41 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
22-08-30 15:01:49 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository
22-08-30 15:01:49 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/esphome/home-assistant-addon repository
22-08-30 15:01:49 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
22-08-30 15:01:51 INFO (MainThread) [supervisor.store] Loading add-ons from store: 66 all - 0 new - 0 remove
22-08-30 15:01:51 INFO (MainThread) [supervisor.store] Loading add-ons from store: 66 all - 0 new - 0 remove
22-08-30 15:02:51 WARNING (MainThread) [supervisor.addons.options] Option 'interface' does not exist in the schema for Samba share (core_samba)
22-08-30 15:03:51 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
22-08-30 15:07:53 WARNING (MainThread) [supervisor.addons.options] Option 'interface' does not exist in the schema for Samba share (core_samba)
22-08-30 15:08:25 INFO (MainThread) [supervisor.host.info] Updating local host information
22-08-30 15:08:26 INFO (MainThread) [supervisor.host.services] Updating service information
22-08-30 15:08:26 INFO (MainThread) [supervisor.host.network] Updating local network information
22-08-30 15:08:26 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information
22-08-30 15:08:26 INFO (MainThread) [supervisor.host.manager] Host information reload completed
22-08-30 15:12:55 WARNING (MainThread) [supervisor.addons.options] Option 'interface' does not exist in the schema for Samba share (core_samba)
22-08-30 15:17:57 WARNING (MainThread) [supervisor.addons.options] Option 'interface' does not exist in the schema for Samba share (core_samba)
22-08-30 15:22:59 WARNING (MainThread) [supervisor.addons.options] Option 'interface' does not exist in the schema for Samba share (core_samba)
22-08-30 15:28:01 WARNING (MainThread) [supervisor.addons.options] Option 'interface' does not exist in the schema for Samba share (core_samba)
22-08-30 15:33:03 WARNING (MainThread) [supervisor.addons.options] Option 'interface' does not exist in the schema for Samba share (core_samba)
22-08-30 15:33:51 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
22-08-30 15:38:05 WARNING (MainThread) [supervisor.addons.options] Option 'interface' does not exist in the schema for Samba share (core_samba)
22-08-30 15:43:07 WARNING (MainThread) [supervisor.addons.options] Option 'interface' does not exist in the schema for Samba share (core_samba)
22-08-30 15:48:09 WARNING (MainThread) [supervisor.addons.options] Option 'interface' does not exist in the schema for Samba share (core_samba)
22-08-30 15:53:11 WARNING (MainThread) [supervisor.addons.options] Option 'interface' does not exist in the schema for Samba share (core_samba)
22-08-30 15:58:13 WARNING (MainThread) [supervisor.addons.options] Option 'interface' does not exist in the schema for Samba share (core_samba)
22-08-30 15:58:38 INFO (SyncWorker_9) [supervisor.docker.interface] Restarting ghcr.io/home-assistant/odroid-n2-homeassistant
22-08-30 15:58:57 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready
22-08-30 15:59:02 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
22-08-30 15:59:02 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
22-08-30 15:59:03 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
22-08-30 15:59:03 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository
22-08-30 15:59:03 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/esphome/home-assistant-addon repository
22-08-30 15:59:03 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
22-08-30 15:59:05 INFO (MainThread) [supervisor.store] Loading add-ons from store: 66 all - 0 new - 0 remove
22-08-30 15:59:05 INFO (MainThread) [supervisor.store] Loading add-ons from store: 66 all - 0 new - 0 remove
22-08-30 15:59:07 WARNING (MainThread) [supervisor.addons.options] Option 'interface' does not exist in the schema for Samba share (core_samba)
22-08-30 15:59:32 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance
22-08-30 16:01:39 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
22-08-30 16:01:41 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
22-08-30 16:01:41 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DNS_SERVER_FAILED/ContextType.DNS_SERVER
22-08-30 16:01:41 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.NETWORK_CONNECTION_PROBLEM/ContextType.SYSTEM
22-08-30 16:01:41 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DNS_SERVER_IPV6_ERROR/ContextType.DNS_SERVER
22-08-30 16:01:41 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE
22-08-30 16:01:41 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM
22-08-30 16:01:41 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON
22-08-30 16:01:41 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.SUPERVISOR
22-08-30 16:01:41 INFO (MainThread) [supervisor.resolution.check] System checks complete
22-08-30 16:01:41 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
22-08-30 16:01:41 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
22-08-30 16:01:41 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
22-08-30 16:01:41 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
22-08-30 16:03:52 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
22-08-30 16:04:09 WARNING (MainThread) [supervisor.addons.options] Option 'interface' does not exist in the schema for Samba share (core_samba)
22-08-30 16:09:11 WARNING (MainThread) [supervisor.addons.options] Option 'interface' does not exist in the schema for Samba share (core_samba)
22-08-30 16:14:13 WARNING (MainThread) [supervisor.addons.options] Option 'interface' does not exist in the schema for Samba share (core_samba)
22-08-30 16:14:29 WARNING (MainThread) [supervisor.addons.options] Option 'interface' does not exist in the schema for Samba share (core_samba)
22-08-30 16:19:15 WARNING (MainThread) [supervisor.addons.options] Option 'interface' does not exist in the schema for Samba share (core_samba)
22-08-30 16:24:17 WARNING (MainThread) [supervisor.addons.options] Option 'interface' does not exist in the schema for Samba share (core_samba)
```

**Comment by bieniu** [comment] 2022-08-31 12:05
A similar observation here

![obraz](https://user-images.githubusercontent.com/478555/187674293-571e13f5-64db-43b6-a0f6-494e45acc529.png)

**Comment by Villa-Buenavista** [comment] 2022-09-01 13:44
Situation seems to have improved insofar that a garbage collection seems to be running now from time to time. The memory usage behaviour does not look normal to me though....

**Comment by agners** [comment] 2022-09-02 09:06
I don't really see this on my Blue test device with Home Assistant 2022.8.5, Supervisor 2022.08.6, Operating System 8.5
![image](https://user-images.githubusercontent.com/34061/188105060-d4ed453e-6fd1-44ff-a737-5aa95a7e4754.png)

So it seems to depend on configuration. As Supervisor doesn't really have a lot of configuration, probably more likely caused by Core or an Add-on.

**Comment by Villa-Buenavista** [comment] 2022-09-05 13:28
The issue persists and now goes up to almost 80% of mem used...  I am a bit concerned it might crash altogether. 
I do not have unusual add-ons running: SAMBA, Studio Code Server, Terminal & SHH, Z-Wave JS - all latest version, no betas. Any idea which one might make trouble? Or what I could check?

![220905 mem usage](https://user-images.githubusercontent.com/36330943/188460073-f5e2e06c-4e26-42f7-877e-d6f510a89f79.JPG)

**Comment by bieniu** [comment] 2022-09-05 13:34
Same here. Restarting HA does not decrease memory consumption, only restarting the host helps. Last week I updated the Supervisor and the Bitwarden addon. @Villa-Buenavista What addons are you using?

![obraz](https://user-images.githubusercontent.com/478555/188461476-699eb533-e6e6-4b51-ad92-e050153ca393.png)

**Comment by Villa-Buenavista** [comment] 2022-09-05 14:16
> Same here. Restarting HA does not decrease memory consumption, only restarting the host helps (red arrow in the chart). Last week I updated the Supervisor and the Bitwarden addon. @Villa-Buenavista I also use Studio Code Server and Z-Wave JS.
> 
> ![obraz](https://user-images.githubusercontent.com/478555/188461476-699eb533-e6e6-4b51-ad92-e050153ca393.png)

Hi,

thanks for the info! I will try to deinstall Studio Code Server und observe the result as that is not crucial. Zwave JS would be a problem as I have a few dozend Zwave devices.... I will also check if the reboot triggers the garbage collection as seems to be the case.

**Comment by Villa-Buenavista** [comment] 2022-09-05 14:19
one more thing, before deinstalling I checked the ram usage of the 4 addons. all of them were below 1% except for ZWave which claims it is using 21.4% of RAM. I do not know if that is normal - it seems high. Any ideas?

**Comment by Villa-Buenavista** [comment] 2022-09-05 18:52
After deinstall of the Studio Code server & reboot (marked) no change in behaviour. 

Memory usage of Zwave JS ist now slightly higher @ 24.5%. So it could be ZWave JS in connection with the new Supervisor. Will report tomorrow.

![220905 deinst_reboot](https://user-images.githubusercontent.com/36330943/188502197-dc31afbb-7acb-4393-97f0-c43e6db258b2.JPG)

**Comment by bieniu** [comment] 2022-09-06 09:45
I'm beginning to suspect that the Z-Wave JS is guilty, a large jump in memory consumption after restarting this add-on.

![obraz](https://user-images.githubusercontent.com/478555/188602860-3a477ef1-de25-41fa-a64d-cfb24d584ee6.png)

**Comment by agners** [comment] 2022-09-06 13:12
Quite likely, I don't use Z-Wave JS, so that would explain why I don't see it. There is also a issue in the Core repository: https://github.com/home-assistant/core/issues/77767

**Comment by agners** [comment] 2022-09-06 13:23
I am closing this as it's pretty much proven that is Z-Wave JS. Please follow the Core issue as  this is the issue the Z-Wave devs are following.

**Closed by agners** 2022-09-06 13:23 UTC
Labels: bug
