### ISSUE TITLE
Failed to get supervisor logs using advanced_logs API

### ISSUE THREAD

**Issue by Anto79-ops** [home-assistant/supervisor#5381] opened 2024-10-30 21:59 UTC
### Describe the issue you are experiencing

Hello,

I'm seeing this in my logs, not sure if its related to the new live log feature on Core 2024.11.0b0

Core 2024.11.0b0
Supervisor 2024.10.4
Operating System 13.2
Frontend 20241030.0

```
2024-10-30 15:56:04.256 ERROR (MainThread) [supervisor.api] Failed to get supervisor logs using advanced_logs API
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/api/host.py", line 188, in _get_boot_id
    return await self.sys_host.logs.get_boot_id(offset)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/host/logs.py", line 87, in get_boot_id
    raise ValueError(f"Logs only contain {len(boot_ids)} boots")
ValueError: Logs only contain 0 boots
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/api/__init__.py", line 403, in get_supervisor_logs
    return await self._api_host.advanced_logs_handler(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/host.py", line 209, in advanced_logs_handler
    params[PARAM_BOOT_ID] = await self._get_boot_id(
                            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/host.py", line 190, in _get_boot_id
    raise APIError() from err
supervisor.exceptions.APIError
```

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1. Reboot Core
2.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
shown above
```

### System Health information

no repairs

**Comment by mdegat01** [comment] 2024-11-04 20:04
duplicate of #5389

**Closed by mdegat01** 2024-11-04 20:04 UTC
Labels: bug
