### ISSUE TITLE
Error update to 2024.11.3

### ISSUE THREAD

**Issue by prourug** [home-assistant/supervisor#5409] opened 2024-11-11 11:30 UTC
### Describe the issue you are experiencing

Error update to 2024.11.3

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Debian

### Steps to reproduce the issue

1.
2.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
Rejestrator: homeassistant.components.websocket_api.http.connection
Źródło: components/websocket_api/commands.py:245
integracja: Home Assistant WebSocket API (dokumentacja, Problemy)
Pierwsze zdarzenie: 12:17:27 (1 zdarzenia)
Ostatnio zalogowany: 12:17:27

[139842779117264] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 262, in async_install
    await self.coordinator.supervisor_client.supervisor.update()
  File "/usr/local/lib/python3.12/site-packages/aiohasupervisor/supervisor.py", line 43, in update
    await self._client.post(
  File "/usr/local/lib/python3.12/site-packages/aiohasupervisor/client.py", line 173, in post
    return await self._request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohasupervisor/client.py", line 122, in _request
    raise exc_type(result.message, result.job_id)
aiohasupervisor.exceptions.SupervisorBadRequestError: Update of Supervisor failed: Can't install ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3: 500 Server Error for http+docker://localhost/v1.47/images/create?tag=2024.11.3&fromImage=ghcr.io%2Fhome-assistant%2Famd64-hassio-supervisor&platform=linux%2Famd64: Internal Server Error ("toomanyrequests: retry-after: 769.764µs, allowed: 44000/minute")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 157, in async_install
    await entity.async_install_with_progress(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 502, in async_install_with_progress
    await self.async_install(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 264, in async_install
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Error updating Home Assistant Supervisor: Update of Supervisor failed: Can't install ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3: 500 Server Error for http+docker://localhost/v1.47/images/create?tag=2024.11.3&fromImage=ghcr.io%2Fhome-assistant%2Famd64-hassio-supervisor&platform=linux%2Famd64: Internal Server Error ("toomanyrequests: retry-after: 769.764µs, allowed: 44000/minute")b wklej tutaj kod
```

### System Health information

-

### Supervisor diagnostics

-

### Additional information

-

**Comment by Briadark** [comment] 2024-11-11 11:33
duplicate of https://github.com/home-assistant/supervisor/issues/5406

**Comment by Krzysztonek** [comment] 2024-11-11 11:37
Same issue here:

![obraz](https://github.com/user-attachments/assets/513b2fd8-d258-4805-98a4-6a128c9f1ba3)

**Comment by Johnyboy1984** [comment] 2024-11-11 11:40
Logger: homeassistant.components.websocket_api.http.connection
Quelle: components/websocket_api/commands.py:245
Integration: Home Assistant WebSocket API (Dokumentation, Probleme)
Erstmals aufgetreten: 12:36:28 (2 Vorkommnisse)
Zuletzt protokolliert: 12:38:54

[546954904768] Unexpected exception
[546950629264] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 262, in async_install
    await self.coordinator.supervisor_client.supervisor.update()
  File "/usr/local/lib/python3.12/site-packages/aiohasupervisor/supervisor.py", line 43, in update
    await self._client.post(
  File "/usr/local/lib/python3.12/site-packages/aiohasupervisor/client.py", line 173, in post
    return await self._request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohasupervisor/client.py", line 122, in _request
    raise exc_type(result.message, result.job_id)
aiohasupervisor.exceptions.SupervisorBadRequestError: Update of Supervisor failed: Can't install ghcr.io/home-assistant/aarch64-hassio-supervisor:2024.11.3: 404 Client Error for http+docker://localhost/v1.47/images/ghcr.io/home-assistant/aarch64-hassio-supervisor:2024.11.3/json: Not Found ("No such image: ghcr.io/home-assistant/aarch64-hassio-supervisor:2024.11.3")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 157, in async_install
    await entity.async_install_with_progress(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 502, in async_install_with_progress
    await self.async_install(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 264, in async_install
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Error updating Home Assistant Supervisor: Update of Supervisor failed: Can't install ghcr.io/home-assistant/aarch64-hassio-supervisor:2024.11.3: 404 Client Error for http+docker://localhost/v1.47/images/ghcr.io/home-assistant/aarch64-hassio-supervisor:2024.11.3/json: Not Found ("No such image: ghcr.io/home-assistant/aarch64-hassio-supervisor:2024.11.3")

**Comment by ChrisMarriott38** [comment] 2024-11-11 11:46
Same here 
![image](https://github.com/user-attachments/assets/6ffd4126-41c8-4a7e-904c-a4c54a98da4f)

**Comment by hlavij** [comment] 2024-11-11 11:48
Hello, 
I have the same issue. I have tried update from GUI and also from HAOS CLI, the same results: 
I am running HAOS in Hyper-V. 

![Screenshot 2024-11-11 124447](https://github.com/user-attachments/assets/a3baaf6a-7822-4971-95d3-963e5f0904a8)

**Comment by Aaroneisele55** [comment] 2024-11-11 11:54
Same here on my Raspberry Pi 4 with HAOS:

![Screenshot_20241111_125259_Home Assistant](https://github.com/user-attachments/assets/1c2830b2-b8ab-46a5-bacc-144f6f516c82)

**Comment by R4zv4n3** [comment] 2024-11-11 11:54
Hello, 
I am having the same issue, tried GUI and CLI, I am running HAOS in proxmox.

![haupdate](https://github.com/user-attachments/assets/4498c12d-5fc2-4bef-8283-ea03b92d060a)

**Comment by RW-Allen** [comment] 2024-11-11 11:55
Have the same issue.  Running on an Home Assistant Green.  Tried a reboot, but issue persists.

**Comment by PantACRO4life** [comment] 2024-11-11 11:56
same issue, haos in proxmox

**Comment by nathan-swannet** [comment] 2024-11-11 11:56
Same issue here

**Comment by MaLangenfeld** [comment] 2024-11-11 12:00
same issue.
Ruuning HomeAssistant on Proxmox 8.2.2

**Comment by bushbrother** [comment] 2024-11-11 12:02
looks like rate limits hit somewhere, I get same issue

**Comment by zefixx1** [comment] 2024-11-11 12:04
same here under Proxmox-VM
![IMG_3459](https://github.com/user-attachments/assets/aac481f5-cdad-44bf-a3ee-ce5eca24b832)

**Comment by richardmx5guys** [comment] 2024-11-11 12:06
Same here. Running HAOS

**Comment by nasixi** [comment] 2024-11-11 12:11
I also have the same issue, running on HA OS standalone.

**Comment by brackman1** [comment] 2024-11-11 12:11
same problem here on supervised haos.

**Comment by cardinal808** [comment] 2024-11-11 12:15
same problem here, Running HA OS under proxmox-VM

**Comment by CVKBaca** [comment] 2024-11-11 12:15
same problem here on supervised haos
![image](https://github.com/user-attachments/assets/31cb5985-db87-40ed-ad5f-4966cfe45791)

**Comment by metbril** [comment] 2024-11-11 12:16
Duplicate of #5405 ?!

![image](https://github.com/user-attachments/assets/6ee6a7da-99d7-404e-bb9a-16d84e6deb78)

**Comment by steps56** [comment] 2024-11-11 12:19
Same Error, Update not possible.
This failing desaster never ever happened before... isn't any Update not tested before spreading it out ???
I am hardly astonished about todays desaster Update.
One step again to stopp any future updates of anything and leaving the HA setup untouched, but working ☝️.

**Comment by steps56** [comment] 2024-11-11 12:20
> Duplicate of #5405 ?!
> 
> ![image](https://private-user-images.githubusercontent.com/559346/384917617-6ee6a7da-99d7-404e-bb9a-16d84e6deb78.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMjc3MDgsIm5iZiI6MTczMTMyNzQwOCwicGF0aCI6Ii81NTkzNDYvMzg0OTE3NjE3LTZlZTZhN2RhLTk5ZDctNDA0ZS1iYjlhLTE2ZDg0ZTZkZWI3OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMVQxMjE2NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YjU3MjUyOWU0MzhkNGE0ZWQxZDE1NDgyYTY2ZDhkMjIzNTY3NGYwMjliYmNmNGE4ZmFjMjc0N2RjYTBkNDI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.SHlr077BSOUB8yipw5f38o9lIDy5CE3QJr0Wfp2n4KY)

Should be duplicated 1000 times more 😉

**Comment by Lietziboyy** [comment] 2024-11-11 12:22
same issue on haos on proxmox vm

**Comment by kylewilliams321** [comment] 2024-11-11 12:22
Same issue waiting for resolution

**Comment by moetazA** [comment] 2024-11-11 12:31
Same issue waiting for resolution

**Comment by geotibi** [comment] 2024-11-11 12:32
same for me

**Comment by livetoautomate** [comment] 2024-11-11 12:34
Same.  Problem is that the file cant be downloaded, even via browser.

{
    "errors": [
        {
            "code": "TOOMANYREQUESTS",
            "message": "retry-after: 3.874µs, allowed: 44000/minute"
        }
    ]
}

**Comment by kic883** [comment] 2024-11-11 12:38
same here 
![image](https://github.com/user-attachments/assets/dc330aa7-a297-4b65-9950-0538237c88de)

**Comment by steps56** [comment] 2024-11-11 12:45
A day, showing how important backups are.
I will block now min. the yesterday backup of my 2 HA Raspis.
So I am able to freeze a working system.
May be I will set up a update skipping.automatiln again, as I have setup in the past for the often problematic SolaX Integration 🤷🏼‍♂️.

**Comment by MikeBP13** [comment] 2024-11-11 12:47
Same error here...

**Closed** 2024-11-11 12:49 UTC
Labels: bug

**Comment by Knochenfahrer** [comment] 2024-11-11 13:17
Ebenso Updateproblem mit HA auf Ubuntu System , 
!!!!!!! Fehlermeldung:
Die Aktion update/install konnte nicht ausgeführt werden. Error updating Home Assistant Supervisor: Update of Supervisor failed: Can't install ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3: 404 Client Error for http+docker://localhost/v1.47/images/ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3/json: Not Found ("No such image: ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3

was kann man da tun ? auf neues Update warten ? Habe schon anderen DNS verwendet, supervisor repair, supervior neustart usw. bringt alles nichts

**Comment by steps56** [comment] 2024-11-11 13:53
Ich habe ab eben die Updatemöglichkeit in HA core und supervicer entzogen/deaktiviert.
Damit erstmal auf SichtvSchluss mit dem Updaterirkus.
Ich möchte ein geräuschlos im Hintergrund unauffällig und geschmeidiges bzw 2 Systeme haben und mich nicht quasi "hauptberuflich" mit ständigem HA Gedöns beschäftigen.
Läuft nun.quasi Stand heute softwaremäßig eingefroren und damit so, wie es sein soll.
