### ISSUE TITLE
Doesn't load Official addons

### ISSUE THREAD

**Issue by fir3burn** [home-assistant/supervisor#3114] opened 2021-09-09 19:41 UTC
### Describe the issue you are experiencing

When I go to the Addons Store, only the addons installed are showed. When I click on 'reload' this error appears on supervisor logs.

### What is the used version of the Supervisor?

supervisor-2021.09.0

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

6.3

### What version of Home Assistant Core is installed?

core-2021.8..8

### Steps to reproduce the issue

Click in the addon store panel

### Anything in the Supervisor logs that might be useful for us?

```txt
`
21-09-09 20:25:14 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository
21-09-09 20:25:14 ERROR (MainThread) [supervisor.jobs] Unhandled exception: Remote 'origin' has no refspec set.
You can set it as follows: 'git config --add "remote.origin.fetch +refs/heads/*:refs/heads/*"'.
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 105, in wrapper
    return await self._method(*args, **kwargs)
  File "/usr/src/supervisor/supervisor/store/git.py", line 155, in pull
    await self.sys_run_in_executor(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/git/remote.py", line 818, in fetch
    self._assert_refspec()
  File "/usr/local/lib/python3.9/site-packages/git/remote.py", line 782, in _assert_refspec
    raise AssertionError(msg % (self.name, self.name))
AssertionError: Remote 'origin' has no refspec set.
You can set it as follows: 'git config --add "remote.origin.fetch +refs/heads/*:refs/heads/*"'.
21-09-09 20:25:14 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-802' coro=<Repository.update() done, defined at /usr/src/supervisor/supervisor/store/repository.py:106> exception=JobException()>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 105, in wrapper
    return await self._method(*args, **kwargs)
  File "/usr/src/supervisor/supervisor/store/git.py", line 155, in pull
    await self.sys_run_in_executor(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/git/remote.py", line 818, in fetch
    self._assert_refspec()
  File "/usr/local/lib/python3.9/site-packages/git/remote.py", line 782, in _assert_refspec
    raise AssertionError(msg % (self.name, self.name))
AssertionError: Remote 'origin' has no refspec set.
You can set it as follows: 'git config --add "remote.origin.fetch +refs/heads/*:refs/heads/*"'.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/store/repository.py", line 110, in update
    await self.git.pull()
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 111, in wrapper
    raise JobException() from err
supervisor.exceptions.JobException
21-09-09 20:25:14 INFO (MainThread) [supervisor.store] Loading add-ons from store: 0 all - 0 new - 0 remove
21-09-09 20:25:14 INFO (MainThread) [supervisor.store] Loading add-ons from store: 0 all - 0 new - 0 remove
`
```

### Additional information

I dont know when this issue starts to happen, but from 2021.6.0 I noticed.
I have restarted core, supervisor and host and the issue continues.

From ssh in the RPI (Hassos) I can get the result from `curl -vvv https://github.com/home-assistant/addons` so the connectivity is ok.

I can update the Core whithout problems, but in this last version, I have to revert to 2021.8.8 because I have an old version of the zwave-js addon.

**Comment by ludeeus** [comment] 2021-09-09 19:51
Duplicate of https://github.com/home-assistant/supervisor/issues/3047

**Closed by ludeeus** 2021-09-09 19:51 UTC
Labels: bug
