### ISSUE TITLE
Supervisor will not start

### ISSUE THREAD

**Issue by mikepruett3** [home-assistant/supervisor#1560] opened 2020-03-04 04:35 UTC
**Home Assistant release with the issue:**
homeassistant/amd64-hassio-supervisor:207

**Operating environment (HassOS/Generic):**
Ubuntu 18.04.4 LTS

**Supervisor logs:**
$ docker logs -f hassio_supervisor
s6-mkdir: warning: unable to mkdir /var/run/s6: Permission denied

**Description of problem:**
After upgrading to v207 yesterday, when I try to restart the Supervisor Container, I get the following message:

> s6-mkdir: warning: unable to mkdir /var/run/s6: Permission denied

Restarting the Service using systemctl restart hassio-supervisor.service I get the exact same error.

**Comment by mikepruett3** [comment] 2020-03-04 04:42
Looks like I had to re-run the hassio_install.sh script, based on this [reddit post](https://www.reddit.com/r/homeassistant/comments/fd5222/linux_install_supervisor_dead_after_update/)

Might want to update the release notes for us docker users. :)

**Comment by frenck** [comment] 2020-03-04 08:08
Duplicate of #1556.


Please make sure you check if your issue was already raised before opening a new issue. Thanks! 👍

**Closed by frenck** 2020-03-04 08:08 UTC
