### ISSUE TITLE
ha core info show homeassistant: 2021.3.4

### ISSUE THREAD

**Issue by monpelaud** [home-assistant/supervisor#2801] opened 2021-04-10 11:07 UTC
### The problem

Hi,
After upgrade 2021.4.1 to 2021.4.3, ha core info show homeassistant: 2021.3.4 instead of 2021.4.3
Best regards

### What is version of Home Assistant Core has the issue?

core-2021.4.3

### What was the last working version of Home Assistant Core?

core-2021.4.1

### What type of installation are you running?

Home Assistant OS

**Comment by frenck** [comment] 2021-04-10 11:47
Transferring to the Supervisor repository, as this seems to be something on that end.

**Comment by mbo18** [comment] 2021-04-10 11:59
Duplicate of https://github.com/home-assistant/supervisor/issues/2800

**Comment by frenck** [comment] 2021-04-10 12:18
Closing as duplicate. Thanks @mbo18

**Closed by frenck** 2021-04-10 12:18 UTC
