### ISSUE TITLE
You are running an unsupported installation on Hass os 4.20 (one of last stable versions for RPI3!)

### ISSUE THREAD

**Issue by mmatloka** [home-assistant/supervisor#3185] opened 2021-10-01 16:17 UTC
### Describe the issue you are experiencing

Suddenly message "You are running an unsupported installation" started appearing. No, I can't upgrade HassOS due to existing issue from December 2020.

### What is the used version of the Supervisor?

supervisor-2021.09.6

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

4.20

### What version of Home Assistant Core is installed?

core-2021.9.7

### Steps to reproduce the issue

1. Message appeared after upgrade to supervisor-2021.09.6
2.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
no
```

### Additional information

I can't upgrade the HassOS due to existing issue ( https://github.com/home-assistant/operating-system/issues/1119 , https://www.reddit.com/r/homeassistant/comments/kf41se/ha_server_goes_awol_witout_reason/, https://community.home-assistant.io/t/hass-frontend-crashes-every-day/256616 ) . Some people find version 5.4 as last stable. Long time ago I tried to update to 5.x but it became suddenly not accessible. According to info from other people 6.x is also not stable for such RPI3 based setup - more info in linked threads & issue.

**Comment by frenck** [comment] 2021-10-01 16:19
As you put yourself, this is a duplicate of: <https://github.com/home-assistant/operating-system/issues/1119>

There is no need to open duplicate issues. Thanks 👍

**Closed by frenck** 2021-10-01 16:19 UTC
Labels: bug
