### ISSUE TITLE
Unable to remove add-on repositories

### ISSUE THREAD

**Issue by N1c093** [home-assistant/supervisor#1726] opened 2020-05-17 16:34 UTC
**Home Assistant release with the issue:** 0.109.6

**Operating environment (HassOS/Generic):** Home Assistant/Hass.io running on Raspberry 3b+

**Supervisor logs:**

```
20-05-17 15:26:48 INFO (MainThread) [supervisor.host.info] Update local host information
20-05-17 15:26:48 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/hostname1
20-05-17 15:26:49 INFO (MainThread) [supervisor.host.services] Update service information
20-05-17 15:26:49 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.systemd1.Manager.ListUnits on /org/freedesktop/systemd1
20-05-17 15:26:49 INFO (MainThread) [supervisor.host.network] Update local network DNS information
20-05-17 15:26:49 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/NetworkManager/DnsManager
20-05-17 15:26:49 INFO (MainThread) [supervisor.host.sound] Update PulseAudio information
20-05-17 15:28:25 INFO (SyncWorker_16) [supervisor.docker.interface] Clean addon_89275b70_dss_voip application
20-05-17 15:28:27 INFO (SyncWorker_16) [supervisor.docker.addon] Start Docker add-on 89275b70/armv7-addon-dss_voip with version 3.3.2
20-05-17 15:28:29 INFO (MainThread) [supervisor.api.security] /host/info access from 89275b70_dss_voip
20-05-17 16:07:38 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup
```

**Description of problem:**

Currently it's not possible to remove an add-on repositories. If you click on the bin, nothing happens. Also the log doesn't show any errors.

I tried to remove these two repositories:

![image](https://user-images.githubusercontent.com/59510296/82154187-7a104d00-986c-11ea-9bee-c52e6f4782e5.png)

**Comment by frenck** [comment] 2020-05-17 17:46
Duplicate of home-assistant/frontend#5819

**Closed by frenck** 2020-05-17 17:46 UTC
