### ISSUE TITLE
snapshot download missing filename Firefox

### ISSUE THREAD

**Issue by tofuSCHNITZEL** [home-assistant/supervisor#1784] opened 2020-06-07 16:25 UTC
**Home Assistant release with the issue:**
Home Assistant 0.110.4

**Operating environment (HassOS/Generic):**
HassOS 4.8
Supervisor Version 227

**Supervisor logs:**
n/a

**Description of problem:**
When downloading a snapshot only a file named "download" (without ending) is received by the browser. Issue occurs with Firefox 77.0.1 but not e.g. in MS Edge (chromium edition)

**Comment by ludeeus** [comment] 2020-06-07 19:27
Duplicate of https://github.com/home-assistant/frontend/issues/6088

**Closed by ludeeus** 2020-06-07 19:27 UTC
