### ISSUE TITLE
Debian 10 HA docker You are running an unsupported installation. Learn More

### ISSUE THREAD

**Issue by userosos** [home-assistant/supervisor#2000] opened 2020-09-01 13:26 UTC
You are running an unsupported installation. Learn More
![изображение](https://user-images.githubusercontent.com/22872748/91856172-dc038f80-ec6e-11ea-8fc8-e7ad1676e7ee.png)

logs supervisor:
```

20-09-01 09:42:14 INFO (MainThread) [supervisor.utils.gdbus] Connect to dbus: org.freedesktop.NetworkManager - /org/freedesktop/NetworkManager/DnsManager
20-09-01 09:42:14 INFO (MainThread) [supervisor.host.info] Update local host information
20-09-01 09:42:14 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/hostname1
20-09-01 09:42:14 INFO (MainThread) [supervisor.host.services] Update service information
20-09-01 09:42:14 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.systemd1.Manager.ListUnits on /org/freedesktop/systemd1
20-09-01 09:42:14 INFO (MainThread) [supervisor.host.network] Update local network DNS information
20-09-01 09:42:14 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/NetworkManager/DnsManager
20-09-01 09:42:14 INFO (MainThread) [supervisor.host.sound] Update PulseAudio information
Failed to load cookie file from cookie: No such file or directory
20-09-01 09:42:14 INFO (MainThread) [supervisor.host.apparmor] Load AppArmor Profiles: {'hassio-supervisor'}
20-09-01 09:42:14 INFO (MainThread) [supervisor.host.services] Reload local service hassio-apparmor.service
20-09-01 09:42:14 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.systemd1.Manager.ReloadOrRestartUnit on /org/freedesktop/systemd1
20-09-01 09:42:14 INFO (SyncWorker_0) [supervisor.docker.interface] Attach to homeassistant/amd64-hassio-dns with version 9
20-09-01 09:42:14 INFO (MainThread) [supervisor.plugins.dns] Restart CoreDNS plugin
20-09-01 09:42:14 INFO (MainThread) [supervisor.misc.forwarder] Start DNS port forwarding to 172.30.32.3
20-09-01 09:42:14 INFO (SyncWorker_0) [supervisor.docker.interface] Restart homeassistant/amd64-hassio-dns
20-09-01 09:42:19 INFO (MainThread) [supervisor.plugins.dns] Updated /etc/resolv.conf
20-09-01 09:42:19 INFO (SyncWorker_0) [supervisor.docker.interface] Attach to homeassistant/amd64-hassio-audio with version 17
20-09-01 09:42:19 INFO (SyncWorker_0) [supervisor.docker.interface] Attach to homeassistant/amd64-hassio-cli with version 25
20-09-01 09:42:19 INFO (SyncWorker_0) [supervisor.docker.interface] Attach to homeassistant/amd64-hassio-multicast with version 3
20-09-01 09:42:19 INFO (MainThread) [supervisor.plugins.multicast] Restart Multicast plugin
20-09-01 09:42:19 INFO (SyncWorker_0) [supervisor.docker.interface] Restart homeassistant/amd64-hassio-multicast
20-09-01 09:42:23 INFO (MainThread) [supervisor.updater] Fetch update data from https://version.home-assistant.io/stable.json
20-09-01 09:42:23 INFO (SyncWorker_0) [supervisor.docker.interface] Attach to homeassistant/qemux86-64-homeassistant with version 0.114.4
20-09-01 09:42:23 INFO (MainThread) [supervisor.hassos] No Home Assistant Operating System found
20-09-01 09:42:23 INFO (MainThread) [supervisor.store.git] Load add-on /data/addons/git/a0d7b954 repository
20-09-01 09:42:23 INFO (MainThread) [supervisor.store.git] Load add-on /data/addons/core repository
20-09-01 09:42:23 INFO (MainThread) [supervisor.store] Load add-ons from store: 66 all - 66 new - 0 remove
20-09-01 09:42:23 INFO (MainThread) [supervisor.addons] Found 4 installed add-ons
20-09-01 09:42:23 INFO (SyncWorker_0) [supervisor.docker.interface] Attach to homeassistant/amd64-addon-configurator with version 5.0.0
20-09-01 09:42:23 INFO (SyncWorker_2) [supervisor.docker.interface] Attach to homeassistant/amd64-addon-ssh with version 8.6.0
20-09-01 09:42:23 INFO (SyncWorker_3) [supervisor.docker.interface] Attach to hassioaddons/glances-amd64 with version 0.8.0
20-09-01 09:42:23 INFO (SyncWorker_1) [supervisor.docker.interface] Attach to hassioaddons/home-panel-amd64 with version 1.8.1
20-09-01 09:42:23 INFO (MainThread) [supervisor.snapshots] Found 8 snapshot files
20-09-01 09:42:23 INFO (MainThread) [supervisor.discovery] Load 0 messages
20-09-01 09:42:23 INFO (MainThread) [supervisor.ingress] Load 4 ingress session
20-09-01 09:42:24 INFO (MainThread) [supervisor.misc.secrets] Load Home Assistant secrets: 1
20-09-01 09:42:24 INFO (MainThread) [__main__] Run Supervisor
20-09-01 09:42:24 INFO (MainThread) [supervisor.api] Start API on 172.30.32.2
20-09-01 09:42:24 CRITICAL (MainThread) [supervisor.core] System running in a unsupported environment!
20-09-01 09:42:24 INFO (MainThread) [supervisor.addons] Phase 'AddonStartup.INITIALIZE' start 0 add-ons
20-09-01 09:42:24 INFO (MainThread) [supervisor.addons] Phase 'AddonStartup.SYSTEM' start 0 add-ons
20-09-01 09:42:24 INFO (MainThread) [supervisor.addons] Phase 'AddonStartup.SERVICES' start 2 add-ons
20-09-01 09:42:24 INFO (SyncWorker_4) [supervisor.docker.interface] Clean addon_core_ssh application
20-09-01 09:42:25 INFO (SyncWorker_4) [supervisor.docker.addon] Start Docker add-on homeassistant/amd64-addon-ssh with version 8.6.0
20-09-01 09:42:25 WARNING (SyncWorker_0) [supervisor.docker.addon] Glances run with disabled protected mode!
20-09-01 09:42:25 INFO (SyncWorker_0) [supervisor.docker.interface] Clean addon_a0d7b954_glances application
20-09-01 09:42:26 INFO (SyncWorker_0) [supervisor.docker.addon] Start Docker add-on hassioaddons/glances-amd64 with version 0.8.0
20-09-01 09:42:30 INFO (MainThread) [supervisor.api.security] /dns/info access from a0d7b954_glances
20-09-01 09:42:31 INFO (SyncWorker_4) [supervisor.docker.interface] Start homeassistant
20-09-01 09:42:31 INFO (MainThread) [supervisor.homeassistant] Wait until Home Assistant is ready
20-09-01 09:42:46 INFO (MainThread) [supervisor.homeassistant] Updated Home Assistant API token
20-09-01 09:42:52 INFO (MainThread) [supervisor.homeassistant] Detect a running Home Assistant instance
20-09-01 09:42:52 INFO (MainThread) [supervisor.addons] Phase 'AddonStartup.APPLICATION' start 2 add-ons
20-09-01 09:42:52 INFO (SyncWorker_0) [supervisor.docker.interface] Clean addon_core_configurator application
20-09-01 09:42:53 INFO (SyncWorker_0) [supervisor.docker.addon] Start Docker add-on homeassistant/amd64-addon-configurator with version 5.0.0
20-09-01 09:42:53 INFO (SyncWorker_4) [supervisor.docker.interface] Clean addon_a0d7b954_home-panel application
20-09-01 09:42:54 INFO (SyncWorker_4) [supervisor.docker.addon] Start Docker add-on hassioaddons/home-panel-amd64 with version 1.8.1
20-09-01 09:42:59 INFO (MainThread) [supervisor.api.security] /dns/info access from a0d7b954_home-panel
20-09-01 09:42:59 INFO (MainThread) [supervisor.misc.tasks] All core tasks are scheduled
20-09-01 09:42:59 INFO (MainThread) [supervisor.misc.hwmon] Started Supervisor hardware monitor
20-09-01 09:42:59 INFO (MainThread) [supervisor.core] Supervisor is up and running
20-09-01 09:42:59 INFO (MainThread) [supervisor.host.info] Update local host information
20-09-01 09:42:59 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/hostname1
20-09-01 09:43:00 INFO (MainThread) [supervisor.updater] Fetch update data from https://version.home-assistant.io/stable.json
20-09-01 09:43:00 INFO (MainThread) [supervisor.host.services] Update service information
20-09-01 09:43:00 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.systemd1.Manager.ListUnits on /org/freedesktop/systemd1
20-09-01 09:43:00 INFO (MainThread) [supervisor.host.network] Update local network DNS information
20-09-01 09:43:00 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/NetworkManager/DnsManager
20-09-01 09:43:00 INFO (MainThread) [supervisor.host.sound] Update PulseAudio information
Failed to load cookie file from cookie: No such file or directory
20-09-01 09:43:59 INFO (SyncWorker_1) [supervisor.docker.interface] Update image hassioaddons/glances-amd64:0.8.0 to hassioaddons/glances-amd64:0.9.0
20-09-01 09:43:59 INFO (SyncWorker_1) [supervisor.docker.interface] Pull image hassioaddons/glances-amd64 tag 0.9.0.
20-09-01 09:44:09 INFO (SyncWorker_1) [supervisor.docker.interface] Stop addon_a0d7b954_glances application
20-09-01 09:44:14 INFO (SyncWorker_1) [supervisor.docker.interface] Clean addon_a0d7b954_glances application
20-09-01 09:44:15 INFO (SyncWorker_4) [supervisor.docker.interface] Cleanup images: ['hassioaddons/glances-amd64:0.8.0']
20-09-01 09:44:15 INFO (MainThread) [supervisor.addons] Add-on 'a0d7b954_glances' successfully updated
20-09-01 09:44:15 WARNING (SyncWorker_3) [supervisor.docker.addon] Glances run with disabled protected mode!
20-09-01 09:44:16 INFO (SyncWorker_3) [supervisor.docker.addon] Start Docker add-on hassioaddons/glances-amd64 with version 0.9.0
20-09-01 09:44:20 INFO (MainThread) [supervisor.api.security] /dns/info access from a0d7b954_glances
20-09-01 09:45:31 INFO (MainThread) [supervisor.snapshots] Full-Snapshot 6afb83f6 start
20-09-01 09:45:31 INFO (MainThread) [supervisor.snapshots] Snapshot 6afb83f6 store Add-ons
20-09-01 09:45:31 INFO (MainThread) [supervisor.addons.addon] Build snapshot for add-on core_configurator
20-09-01 09:45:31 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_configurator
20-09-01 09:45:31 INFO (MainThread) [supervisor.addons.addon] Build snapshot for add-on core_ssh
20-09-01 09:45:31 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_ssh
20-09-01 09:45:31 INFO (MainThread) [supervisor.addons.addon] Build snapshot for add-on a0d7b954_home-panel
20-09-01 09:45:31 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon a0d7b954_home-panel
20-09-01 09:45:31 INFO (MainThread) [supervisor.addons.addon] Build snapshot for add-on a0d7b954_glances
20-09-01 09:45:31 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon a0d7b954_glances
20-09-01 09:45:31 INFO (MainThread) [supervisor.snapshots] Snapshot 6afb83f6 store folders
20-09-01 09:45:31 INFO (SyncWorker_4) [supervisor.snapshots.snapshot] Snapshot folder addons/local
20-09-01 09:45:31 INFO (SyncWorker_4) [supervisor.snapshots.snapshot] Snapshot folder addons/local done
20-09-01 09:45:31 INFO (SyncWorker_6) [supervisor.snapshots.snapshot] Snapshot folder share
20-09-01 09:45:31 INFO (SyncWorker_6) [supervisor.snapshots.snapshot] Snapshot folder share done
20-09-01 09:45:31 INFO (SyncWorker_1) [supervisor.snapshots.snapshot] Snapshot folder homeassistant
20-09-01 09:45:37 INFO (SyncWorker_1) [supervisor.snapshots.snapshot] Snapshot folder homeassistant done
20-09-01 09:45:37 INFO (SyncWorker_0) [supervisor.snapshots.snapshot] Snapshot folder ssl
20-09-01 09:45:37 INFO (SyncWorker_0) [supervisor.snapshots.snapshot] Snapshot folder ssl done
20-09-01 09:45:37 INFO (MainThread) [supervisor.snapshots] Full-Snapshot 6afb83f6 done
```

The system:
|arch|x86_64|
| --- | --- |
|chassis|desktop|
|dev|false|
|docker|true|
|docker_version|19.03.12|
|hassio|true|
|host_os|Debian GNU/Linux 10 (buster)|
|installation_type|Home Assistant Supervised|
|os_name|Linux|
|os_version|4.19.0-10-amd64|
|python_version|3.8.3|
|supervisor|235|
|version|0.114.4|
|virtualenv|false|

### Lovelace

|dashboards|1|
| --- | --- |
|mode|storage|
|resources|0|
|views|3|

dpkg --status Systemd

    dpkg --status Systemd
    Package: systemd
    Status: install ok installed
    Priority: important
    Section: admin
    Installed-Size: 13484
    Architecture: amd64
    Multi-Arch: foreign
    Version: 241-7~deb10u4
    Replaces: udev (<< 228-5)
    Depends: libacl1 (>= 2.2.23), libapparmor1 (>= 2.9.0-3+exp2), libaudit1 (>= 1:2.2.1), libcap2 (>= 1:2.10), libcryptsetup12 (>= 2:1.6.0), libgnutls30 (>= 3.6.6), libgpg-error0 (>= 1.14), libidn11 (>= 1.13), libip4tc0 (>= 1.6.0+snapshot20161117), libkmod2 (>= 5~), liblz4-1 (>= 0.0~r130), libmount1 (>= 2.30), libpam0g (>= 0.99.7.1), libseccomp2 (>= 2.3.1), libsystemd0 (= 241-7~deb10u4), util-linux (>= 2.27.1), mount (>= 2.26), adduser

dpkg --status docker-ce

    Package: docker-ce
    Status: install ok installed
    Priority: optional
    Section: admin
    Installed-Size: 104064
    Architecture: amd64
    Version: 5:19.03.12~3-0~debian-buster
    Replaces: docker-engine
    Depends: docker-ce-cli, containerd.io (>= 1.2.2-3), iptables, libseccomp2 (>= 2.3.0), libc6 (>= 2.3.2), libdevmapper1.02.1 (>= 2:1.02.97), libsystemd0

dpkg --status network-manager

    Package: network-manager
    Status: install ok installed
    Priority: optional
    Section: net
    Installed-Size: 11584
    Architecture: amd64
    Version: 1.14.6-2+deb10u1
    Depends: libaudit1 (>= 1:2.2.1), libbluetooth3 (>= 4.91), libc6 (>= 2.26), libcurl3-gnutls (>= 7.16.3), libglib2.0-0 (>= 2.43.2), libgnutls30 (>= 3.6.5), libjansson4 (>= 2.0.1), libmm-glib0 (>= 1.0.0), libndp0 (>= 1.2), libnewt0.52 (>= 0.52.20), libnm0 (= 1.14.6-2+deb10u1), libpolkit-agent-1-0 (>= 0.99), libpolkit-gobject-1-0 (>= 0.104), libpsl5 (>= 0.13.0), libreadline7 (>= 6.0), libselinux1 (>= 1.32), libsystemd0 (>= 221), libteamdctl0 (>= 1.9), libudev1 (>= 183), libuuid1 (>= 2.16), lsb-base, wpasupplicant, dbus, udev, adduser, libpam-systemd, policykit-1

dpkg --status avahi-daemon

    Package: avahi-daemon
    Status: install ok installed
    Priority: optional
    Section: net
    Installed-Size: 278
    Architecture: amd64
    Multi-Arch: foreign
    Source: avahi (0.7-4)
    Version: 0.7-4+b1
    Depends: libavahi-common3 (>= 0.6.16), libavahi-core7 (>= 0.6.24), libc6 (>= 2.27), libcap2 (>= 1:2.10), libdaemon0 (>= 0.14), libdbus-1-3 (>= 1.9.14), libexpat1 (>= 2.0.1), adduser, dbus (>= 0.60), lsb-base (>= 3.0-6), bind9-host | host

dpkg --status apparmor

    Package: apparmor
    Status: install ok installed
    Priority: optional
    Section: admin
    Installed-Size: 1833
    Architecture: amd64
    Version: 2.13.2-10
    Replaces: fcitx-data (<< 1:4.2.9.1-1ubuntu2)
    Depends: debconf, lsb-base, debconf (>= 0.5) | debconf-2.0, python3:any, libc6 (>= 2.17)

screenfetch

     _,met$$$$$gg.           user@nuc
  ,g$$$$$$$$$$$$$$$P.        OS: Debian 10 buster
,g$$P""       """Y$$.".      Kernel: x86_64 Linux 4.19.0-10-amd64

,$$P’ $$$. Uptime: 1h 53m ',$$P ,ggs. $$b: Packages: 1762
d$$' ,$P"' . $$$ Shell: bash $$P d$' , $$P CPU: Intel Pentium N3700 @ 4x 2.4GHz [48.0°C] $$: $$. - ,d$$' GPU: $$\; Y$b._ _,d$P' RAM: 1283MiB / 3869MiB Y$$. ."Y$$$$P"' $$b “-.__
Y$$ Y$$.
$$b. Y$$b.
"Y$b._ 

On the previous version, everything worked i think.
https://community.home-assistant.io/t/debian-10-ha-docker-you-are-running-an-unsupported-installation-learn-more/223592/7

**Comment by frenck** [comment] 2020-09-01 15:11
What storage and logging driver is your Docker using?

**Comment by ludeeus** [comment] 2020-09-01 15:59
It looks like the start of the log is missing, there should be an "ERROR" stating why you see that message, that error happens before what you have posted here.

Try running `docker logs hassio_supervisor` to get to them

**Comment by userosos** [comment] 2020-09-01 17:35
> 
> 
> It looks like the start of the log is missing, there should be an "ERROR" stating why you see that message, that error happens before what you have posted here.
> 
> Try running `docker logs hassio_supervisor` to get to them

I dontn now how i can do it. Sorry.
But i has the resolve - https://github.com/home-assistant/supervised-installer

Run as root (sudo su):

curl -sL https://raw.githubusercontent.com/home-assistant/supervised-installer/master/installer.sh | bash -s

And reboot.

**Comment by balloob** [comment] 2020-09-02 06:58
Alright, closing this issue then. For people finding this issue, find the cause by following [this comment by @ludeeus](https://github.com/home-assistant/supervisor/issues/2000#issuecomment-684960431)

**Closed by balloob** 2020-09-02 06:58 UTC
