### ISSUE TITLE
Unable to do any snapshots !

### ISSUE THREAD

**Issue by vincegre** [home-assistant/supervisor#2512] opened 2021-02-03 16:29 UTC
### Describe the issue

Each time I try to do a full snapshot of system, it tells me an unknown error happened and to check supervisor and in logs there is that line. Ha is running perfectly fine and everything ok out of snapshots impossible !

`21-02-03 16:21:52 WARNING (MainThread) [supervisor.jobs] 'SnapshotManager.do_snapshot_full' blocked from execution, system is not running`

### Steps to reproduce

Try to create a full snapshot in HA web interface

### Enviroment details

- **Operating System:**:  Home Assistant OS 5.11
- **Supervisor version:**: supervisor-2021.02.2
- **Home Assistant version**: core-2021.1.5

### Supervisor logs

```
21-02-03 16:21:52 WARNING (MainThread) [supervisor.jobs] 'SnapshotManager.do_snapshot_full' blocked from execution, system is not running

```

### System Information

```
Version | 2021.1.5
Installation Type | Home Assistant OS
Development | false
Supervisor | true
Docker | true
Virtual Environment | false
Python Version | 3.8.7
Operating System Family | Linux
Operating System Version | 5.4.83-v8
CPU Architecture | aarch64
Timezone | Europe/Zurich

```

**Comment by donkawechico** [comment] 2021-02-04 04:35
Seeing the same error message. 

In addition, I'm unable to restart core or supervisor after updating to 2021.1.5... getting these errors:

```
21-02-04 04:33:22 WARNING (MainThread) [supervisor.jobs] 'Supervisor.restart' blocked from execution, system is not running
21-02-04 04:33:27 ERROR (MainThread) [supervisor.utils] Can't execute restart while a task is in progress
```

**Comment by solidssss** [comment] 2021-02-04 06:45
I got the same with core-2021.2.0 & supervisor-2021.01.7
I get: WARNING (MainThread) [supervisor.jobs] 'SnapshotManager.do_snapshot_full' blocked from execution, system is not running

**Comment by vincegre** [comment] 2021-02-04 08:02
I noticed also I have a bunch of repetitive errors in log with that buggy supervisor. All these errors being about addons not even installed on my system.....

```
21-02-04 06:32:18 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'devices' use a deprecated format, the new format uses a list of paths only. Please report this to the maintainer of TellStick
21-02-04 06:32:18 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of Z-Wave JS
21-02-04 06:32:18 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of HomeMatic CCU
21-02-04 06:32:18 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of Terminal & SSH
21-02-04 06:32:18 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of OpenZWave
21-02-04 06:32:18 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of deCONZ
21-02-04 06:32:18 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'devices' use a deprecated format, the new format uses a list of paths only. Please report this to the maintainer of deCONZ
```

**Comment by vincegre** [comment] 2021-02-04 08:34
Succeeded to upgrade supervisor at `supervisor-2021.02.3` but absolutely no changes, same warnings all the time in logs and snapshots failing due to "system not running" :-1:

**Comment by ludeeus** [comment] 2021-02-04 13:18
None of what's been posted here is a bug.
Blocking snapshots (and other functions) when the system has not started is a safety measurement.

Can one of you paste the _entire_ supervisor logs, since you may have other issues that result in this?

**Comment by vincegre** [comment] 2021-02-04 13:34
> None of what's been posted here is a bug.
> Blocking snapshots (and other functions) when the system has not started is a safety measurement.

Makes sense but then it should happen only during first seconds/minutes when system starts, here we have problem all time and whatever supervisor says system is well and running as HA is fully operationnal !

> Can one of you paste the _entire_ supervisor logs, since you may have other issues that result in this?

I don't have for now access at full supervisor logs but have you seen my previous post ? about all the other error I had in supervisor logs since last supervisor updates (errors related at addon not installed in my system btw..)

**Comment by vincegre** [comment] 2021-02-04 15:48
> Yes, but none of those are bugs with the Supervisor, and does not affect this at all.

Since I updated supervisor at new version avalaible 2021.02.4 I'm nearly at same problem, snapshot looks to run fine now but archive created is not usable !
I would be happy to share full logs of Supervisor if I find out an easy way to copy/paste them in whole or download them from my HA ! (just a nightmare to copy/paste from web interface of ha :( )

**Comment by Feedy88** [comment] 2021-02-04 16:19
Running into a similar issue since todays update. First iteration of snapshot will start but only proceed until `Snapshot folder homeassistant`. Further, no progress happens.

If I try to start a new snapshot I will receive the same error message as above.

(ssh snapshot cancelled at 16:16)

See full supervisor logs below:
```21-02-04 15:50:08 INFO (SyncWorker_0) [supervisor.docker.interface] Attaching to homeassistant/armv7-hassio-observer with version 2020.10.1
21-02-04 15:50:08 INFO (SyncWorker_0) [supervisor.docker.interface] Attaching to homeassistant/armv7-hassio-multicast with version 3
21-02-04 15:50:08 INFO (MainThread) [supervisor.plugins.multicast] Starting Multicast plugin
21-02-04 15:50:08 INFO (SyncWorker_0) [supervisor.docker.interface] Cleaning hassio_multicast application
21-02-04 15:50:30 INFO (SyncWorker_0) [supervisor.docker.multicast] Starting Multicast homeassistant/armv7-hassio-multicast with version 3 - Host
21-02-04 15:50:30 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
21-02-04 15:50:31 INFO (SyncWorker_0) [supervisor.docker.interface] Attaching to homeassistant/raspberrypi4-homeassistant with version 2021.2.0
21-02-04 15:50:31 INFO (MainThread) [supervisor.homeassistant.secrets] Loaded 3 Home Assistant secrets
21-02-04 15:50:31 INFO (MainThread) [supervisor.hassos] Detect HassOS 5.10 / BootSlot A
21-02-04 15:50:32 INFO (MainThread) [supervisor.store.git] Loading add-on /data/addons/core repository
21-02-04 15:50:32 INFO (MainThread) [supervisor.store.git] Loading add-on /data/addons/git/a0d7b954 repository
21-02-04 15:50:32 INFO (MainThread) [supervisor.store.git] Loading add-on /data/addons/git/1ded40ef repository
21-02-04 15:50:33 INFO (MainThread) [supervisor.store] Loading add-ons from store: 66 all - 66 new - 0 remove
21-02-04 15:50:33 INFO (MainThread) [supervisor.addons] Found 8 installed add-ons
21-02-04 15:50:33 INFO (SyncWorker_0) [supervisor.docker.interface] Attaching to homeassistant/armv7-addon-git_pull with version 7.12
21-02-04 15:50:33 INFO (SyncWorker_3) [supervisor.docker.interface] Attaching to homeassistant/armhf-addon-deconz with version 6.3.0
21-02-04 15:50:33 INFO (SyncWorker_2) [supervisor.docker.interface] Attaching to thepicklenat0r/armv7-hassio-ngrok with version 2.1.6
21-02-04 15:50:33 INFO (SyncWorker_1) [supervisor.docker.interface] Attaching to homeassistant/armv7-addon-mosquitto with version 5.1
21-02-04 15:50:33 INFO (SyncWorker_4) [supervisor.docker.interface] Attaching to homeassistant/armv7-addon-configurator with version 5.1.0
21-02-04 15:50:33 INFO (SyncWorker_5) [supervisor.docker.interface] Attaching to hassioaddons/node-red-armv7 with version 7.2.11
21-02-04 15:50:33 INFO (SyncWorker_6) [supervisor.docker.interface] Attaching to homeassistant/armv7-addon-ssh with version 8.9.1
21-02-04 15:50:33 INFO (SyncWorker_7) [supervisor.docker.interface] Attaching to ghcr.io/hassio-addons/tasmoadmin/armv7 with version 0.14.0
21-02-04 15:50:33 INFO (MainThread) [supervisor.snapshots] Found 0 snapshot files
21-02-04 15:50:33 INFO (MainThread) [supervisor.discovery] Loaded 2 messages
21-02-04 15:50:33 INFO (MainThread) [supervisor.ingress] Loaded 6 ingress sessions
21-02-04 15:50:33 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.SETUP
21-02-04 15:50:33 INFO (MainThread) [supervisor.resolution.check] System checks complete
21-02-04 15:50:33 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.SETUP
21-02-04 15:50:33 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
21-02-04 15:50:33 INFO (MainThread) [__main__] Running Supervisor
21-02-04 15:50:33 INFO (MainThread) [supervisor.hassos] Rauc: A - marked slot kernel.0 as good
21-02-04 15:50:33 INFO (MainThread) [supervisor.addons] Phase 'AddonStartup.INITIALIZE' starting 0 add-ons
21-02-04 15:50:33 INFO (MainThread) [supervisor.addons] Phase 'AddonStartup.SYSTEM' starting 3 add-ons
21-02-04 15:50:36 INFO (SyncWorker_0) [supervisor.docker.addon] Starting Docker add-on homeassistant/armv7-addon-mosquitto with version 5.1
21-02-04 15:50:37 INFO (SyncWorker_1) [supervisor.docker.addon] Starting Docker add-on thepicklenat0r/armv7-hassio-ngrok with version 2.1.6
21-02-04 15:50:38 INFO (MainThread) [supervisor.services.modules.mqtt] Set core_mosquitto as service provider for mqtt
21-02-04 15:50:39 INFO (SyncWorker_4) [supervisor.docker.addon] Starting Docker add-on ghcr.io/hassio-addons/tasmoadmin/armv7 with version 0.14.0
21-02-04 15:50:44 INFO (MainThread) [supervisor.addons] Phase 'AddonStartup.SERVICES' starting 2 add-ons
21-02-04 15:50:46 INFO (SyncWorker_3) [supervisor.docker.addon] Starting Docker add-on homeassistant/armv7-addon-ssh with version 8.9.1
21-02-04 15:50:48 INFO (SyncWorker_5) [supervisor.docker.addon] Starting Docker add-on homeassistant/armhf-addon-deconz with version 6.3.0
21-02-04 15:50:53 INFO (MainThread) [supervisor.core] Start Home Assistant Core
21-02-04 15:50:53 INFO (SyncWorker_0) [supervisor.docker.interface] Starting homeassistant
21-02-04 15:50:54 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready
21-02-04 15:51:26 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
21-02-04 15:51:37 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance
21-02-04 15:51:37 INFO (MainThread) [supervisor.addons] Phase 'AddonStartup.APPLICATION' starting 2 add-ons
21-02-04 15:51:48 INFO (SyncWorker_5) [supervisor.docker.addon] Starting Docker add-on homeassistant/armv7-addon-configurator with version 5.1.0
21-02-04 15:51:49 INFO (SyncWorker_4) [supervisor.docker.addon] Starting Docker add-on hassioaddons/node-red-armv7 with version 7.2.11
21-02-04 15:51:51 INFO (MainThread) [supervisor.api.security] /host/info access from a0d7b954_nodered
21-02-04 15:51:54 INFO (MainThread) [supervisor.api.security] /dns/info access from a0d7b954_nodered
21-02-04 15:51:56 INFO (MainThread) [supervisor.misc.tasks] All core tasks are scheduled
21-02-04 15:51:56 INFO (MainThread) [supervisor.misc.hwmon] Started Supervisor hardware monitor
21-02-04 15:51:56 INFO (MainThread) [supervisor.core] Supervisor is up and running
21-02-04 15:51:56 INFO (MainThread) [supervisor.host.info] Updating local host information
21-02-04 15:51:56 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
21-02-04 15:51:56 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
21-02-04 15:51:56 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
21-02-04 15:51:57 INFO (MainThread) [supervisor.host.services] Updating service information
21-02-04 15:51:57 INFO (MainThread) [supervisor.host.network] Updating local network information
21-02-04 15:52:00 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information
21-02-04 15:52:00 INFO (MainThread) [supervisor.host] Host information reload completed
21-02-04 15:52:23 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
21-02-04 15:52:23 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
21-02-04 15:52:23 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
21-02-04 15:52:23 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
21-02-04 15:52:23 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
21-02-04 15:52:23 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
21-02-04 15:52:23 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
21-02-04 15:52:23 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
21-02-04 15:52:23 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
21-02-04 15:56:24 INFO (MainThread) [supervisor.api.security] /snapshots/new/full access from core_ssh
21-02-04 15:56:24 INFO (MainThread) [supervisor.snapshots] Creating new full-snapshot with slug 860c005a
21-02-04 15:56:24 INFO (MainThread) [supervisor.snapshots] Snapshotting 860c005a store Add-ons
21-02-04 15:56:24 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on core_mosquitto
21-02-04 15:56:24 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_mosquitto
21-02-04 15:56:24 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on core_ssh
21-02-04 15:56:24 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_ssh
21-02-04 15:56:24 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on core_configurator
21-02-04 15:56:24 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_configurator
21-02-04 15:56:24 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on core_deconz
21-02-04 15:56:27 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_deconz
21-02-04 15:56:27 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on 1ded40ef_ngrok
21-02-04 15:56:27 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon 1ded40ef_ngrok
21-02-04 15:56:27 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on a0d7b954_nodered
21-02-04 15:56:27 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon a0d7b954_nodered
21-02-04 15:56:27 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on core_git_pull
21-02-04 15:56:27 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_git_pull
21-02-04 15:56:27 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on a0d7b954_sonweb
21-02-04 15:56:27 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon a0d7b954_sonweb
21-02-04 15:56:27 INFO (MainThread) [supervisor.snapshots] Snapshotting 860c005a store folders
21-02-04 15:56:27 INFO (SyncWorker_4) [supervisor.snapshots.snapshot] Snapshot folder ssl
21-02-04 15:56:27 INFO (SyncWorker_4) [supervisor.snapshots.snapshot] Snapshot folder ssl done
21-02-04 15:56:27 INFO (SyncWorker_0) [supervisor.snapshots.snapshot] Snapshot folder addons/local
21-02-04 15:56:27 INFO (SyncWorker_0) [supervisor.snapshots.snapshot] Snapshot folder addons/local done
21-02-04 15:56:27 INFO (SyncWorker_5) [supervisor.snapshots.snapshot] Snapshot folder media
21-02-04 15:56:27 INFO (SyncWorker_5) [supervisor.snapshots.snapshot] Snapshot folder media done
21-02-04 15:56:27 INFO (SyncWorker_1) [supervisor.snapshots.snapshot] Snapshot folder homeassistant
21-02-04 16:16:34 INFO (MainThread) [supervisor.snapshots] Found 0 snapshot files
21-02-04 16:16:40 WARNING (MainThread) [supervisor.jobs] 'SnapshotManager.do_snapshot_full' blocked from execution, system is not running```

**Comment by ludeeus** [comment] 2021-02-05 13:34
Your previous snapshot process is not finished, when you create a snapshot the state changes to "freeze" instead of "running"
Can you post the output of `ls -la /config` ?

**Comment by Feedy88** [comment] 2021-02-05 14:28
Sure, here you go:

```drwxr-xr-x   11 root     root          4096 Feb  5 15:26 .
drwxr-xr-x    1 root     root          4096 Feb  4 17:23 ..
-rw-r--r--    1 root     root             8 Feb  4 12:13 .HA_VERSION
drwxr-xr-x    2 root     root          4096 Sep 22 20:23 .cloud
drwxr-xr-x    3 root     root          4096 Feb  5 15:24 .storage
-rw-r--r--    1 root     root          7855 Jan 31 23:09 automations.yaml
drwxr-xr-x    3 root     root          4096 Dec 14 19:08 blueprints
-rw-r--r--    1 root     root          1888 Jan 19 16:26 configuration.yaml
drwxr-xr-x    3 root     root          4096 Dec  6 23:13 custom_components
drwxr-xr-x    2 root     root          4096 Sep 22 20:23 deps
-rw-r--r--    1 root     root             0 Sep 22 20:23 groups.yaml
-rw-r--r--    1 root     root         15751 Feb  5 14:48 home-assistant.log
-rw-r--r--    1 root     root     13070336000 Feb  5 15:26 home-assistant_v2.db
drwxr-xr-x    5 root     root          4096 Jan 24 23:12 node-red
-rw-r--r--    1 root     root           113 Jan 16 20:47 notes.txt
-rw-r--r--    1 root     root           384 Jan 17 21:19 notify.yaml
drwxr-xr-x    2 root     root          4096 Dec 23 22:02 python_scripts
-rw-r--r--    1 root     root         13780 Jan 24 19:57 scenes.yaml
-rw-r--r--    1 root     root             0 Sep 22 20:23 scripts.yaml
-rw-r--r--    1 root     root           261 Jan 17 18:54 secrets.yaml
-rw-r--r--    1 root     root          3534 Jan 27 00:36 sensor.yaml
-rw-r--r--    1 root     root          1766 Oct  3 00:21 themes.yaml
drwxr-xr-x    2 root     root          4096 Sep 22 20:23 tts
drwxr-xr-x    3 root     root          4096 Jan 21 22:08 www
-rw-r--r--    1 root     root           207 Jan 15 10:56 zone.yaml```

**Comment by ludeeus** [comment] 2021-02-08 11:27
Update  Supervisor to 2021.02.5 and try again

**Comment by vincegre** [comment] 2021-02-08 11:50
> Update Supervisor to 2021.02.5 and try again

Sorry but no changes !!

`21-02-08 11:49:00 WARNING (MainThread) [supervisor.jobs] 'SnapshotManager.do_snapshot_full' blocked from execution, system is not running - CoreState.FREEZE`

And also have always all these warnings in Supervisor about some add-ons that are not even installed on my system like these:

`21-02-08 11:10:51 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of Z-Wave JS to MQTT`

**Comment by ludeeus** [comment] 2021-02-08 12:08
> Sorry but no changes !!

Actually, there is!

It has added `CoreState.FREEZE` to the message!
This is what I suspected earlier with "Your previous snapshot process is not finished, when you create a snapshot the state changes to "freeze" instead of "running""

This is a known issue in the UI, and a duplicate to <https://github.com/home-assistant/frontend/issues/8332>.
Snapshots works, but if they take too much time, the UI will try again.

**Comment by fabianpk** [comment] 2021-02-08 12:10
I have the same issue but mine says:

'SnapshotManager.do_snapshot_full' blocked from execution, system is not running - CoreState.STARTUP

The reason I want to do a snapshot is that I want to go back to a previous version since Zwave isn't working (maybe the system is stuck in startup process and it never finalizes?)
This is on 
## System Health

version | core-2021.2.1
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.7
os_name | Linux
os_version | 4.19.0-13-amd64
arch | x86_64
timezone | Europe/Stockholm

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4834
Installed Version | 1.11.0
Stage | running
Available Repositories | 778
Installed Repositories | 4

</details>

<details><summary>Hass.io</summary>

host_os | Debian GNU/Linux 10 (buster)
-- | --
update_channel | stable
supervisor_version | supervisor-2021.02.5
docker_version | 20.10.1
disk_total | 108.1 GB
disk_used | 70.5 GB
healthy | true
supported | true
supervisor_api | ok
version_api | ok
installed_addons | AppDaemon 4 (0.4.2), Mosquitto broker (5.1), Plejd (0.5.1), File editor (5.2.0), OpenZWave (0.9.0), Check Home Assistant configuration (3.6.0), Grafana (6.1.0), InfluxDB (4.0.1), Duck DNS (1.12.4), Dnsmasq (1.3), Z-Wave JS (0.1.4)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 2
views | 5
mode | storage

</details>

**Comment by fabianpk** [comment] 2021-02-08 12:22
Which addon, the snapshotmanager? Can you even disable that at startup?

**Comment by ludeeus** [comment] 2021-02-08 12:30
Since you talked about zwave, I assumed it was the OpenZWave addon you were talking about. 
If that is not the case open a separate issue since it's not the same as the rest here (which is a duplicate of the UI bug)

Closing as a duplicate to <https://github.com/home-assistant/frontend/issues/8332>

**Closed by ludeeus** 2021-02-08 12:30 UTC
Labels: bug

**Comment by vincegre** [comment] 2021-02-09 18:13
Tested again today with new version: supervisor-2021.02.6 and succeeded to build a restorable snapshot using LAN IP of my HA instance (not nabu casa URL) and could restore it successfully !
Restoring process is always as confusing as in the past and it doesn't restore network settings of supervisor (my HA instance got restored in DHCP mode for network instead of fixed IP it had before). Is it a supervisor bug to report here ?
