### ISSUE TITLE
After update of supervisor from 11.2 to 11.3 failed (see issues 5405-5409), HA "Forgets" there is an update

### ISSUE THREAD

**Issue by Dweinbach** [home-assistant/supervisor#5410] opened 2024-11-11 15:38 UTC
### Describe the issue you are experiencing

Like many people, I experienced the issues with updating from supervisor 11.2 to 11.3.

But now, HA does not even think there is a version newer than 11.2 - it says no updates available.

![image](https://github.com/user-attachments/assets/03d76733-80c9-4251-8a67-59343f5345c4)

I tried a full reboot and still does not detect that 11.3 is available.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1. experience issue 5405-5409 multiple times
2. wait an hour
3. system thinks supervisor 11.2 is the latest
...

### Anything in the Supervisor logs that might be useful for us?

```txt
I don't see anything related to not finding the update. These are the errors it got when it did find the update:
`[32m2024-11-11 06:08:53.813 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[32m2024-11-11 06:16:39.839 INFO (MainThread) [supervisor.misc.tasks] Found new Supervisor version 2024.11.3, updating[0m
[32m2024-11-11 06:16:39.840 INFO (MainThread) [supervisor.supervisor] Fetching AppArmor profile https://version.home-assistant.io/apparmor_stable.txt[0m
[32m2024-11-11 06:16:39.953 INFO (MainThread) [supervisor.host.apparmor] Adding/updating AppArmor profile: hassio-supervisor[0m
[32m2024-11-11 06:16:40.185 INFO (MainThread) [supervisor.supervisor] Update Supervisor to version 2024.11.3[0m
[32m2024-11-11 06:16:40.187 INFO (MainThread) [supervisor.docker.interface] Downloading docker image ghcr.io/home-assistant/amd64-hassio-supervisor with tag 2024.11.3.[0m
[31m2024-11-11 06:16:41.969 ERROR (MainThread) [supervisor.docker.interface] Can't install ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3: 404 Client Error for http+docker://localhost/v1.47/images/ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3/json: Not Found ("No such image: ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3")[0m
[31m2024-11-11 06:16:42.010 ERROR (MainThread) [supervisor.supervisor] Update of Supervisor failed: Can't install ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3: 404 Client Error for http+docker://localhost/v1.47/images/ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3/json: Not Found ("No such image: ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3")[0m
[32m2024-11-11 06:38:54.365 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[32m2024-11-11 06:59:49.858 INFO (MainThread) [supervisor.supervisor] Fetching AppArmor profile https://version.home-assistant.io/apparmor_stable.txt[0m
[32m2024-11-11 06:59:50.010 INFO (MainThread) [supervisor.host.apparmor] Adding/updating AppArmor profile: hassio-supervisor[0m
[32m2024-11-11 06:59:50.247 INFO (MainThread) [supervisor.supervisor] Update Supervisor to version 2024.11.3[0m
[32m2024-11-11 06:59:50.248 INFO (MainThread) [supervisor.docker.interface] Downloading docker image ghcr.io/home-assistant/amd64-hassio-supervisor with tag 2024.11.3.[0m
[31m2024-11-11 06:59:56.601 ERROR (MainThread) [supervisor.docker.interface] Can't install ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3: 404 Client Error for http+docker://localhost/v1.47/images/ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3/json: Not Found ("No such image: ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3")[0m
[31m2024-11-11 06:59:56.640 ERROR (MainThread) [supervisor.supervisor] Update of Supervisor failed: Can't install ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3: 404 Client Error for http+docker://localhost/v1.47/images/ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3/json: Not Found ("No such image: ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3")[0m
[32m2024-11-11 07:00:33.130 INFO (MainThread) [supervisor.supervisor] Fetching AppArmor profile https://version.home-assistant.io/apparmor_stable.txt[0m
[32m2024-11-11 07:00:33.247 INFO (MainThread) [supervisor.host.apparmor] Adding/updating AppArmor profile: hassio-supervisor[0m
[32m2024-11-11 07:00:33.493 INFO (MainThread) [supervisor.supervisor] Update Supervisor to version 2024.11.3[0m
[32m2024-11-11 07:00:33.494 INFO (MainThread) [supervisor.docker.interface] Downloading docker image ghcr.io/home-assistant/amd64-hassio-supervisor with tag 2024.11.3.[0m
[31m2024-11-11 07:00:34.093 ERROR (MainThread) [supervisor.docker.interface] Can't install ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3: 500 Server Error for http+docker://localhost/v1.47/images/create?tag=2024.11.3&fromImage=ghcr.io%2Fhome-assistant%2Famd64-hassio-supervisor&platform=linux%2Famd64: Internal Server Error ("toomanyrequests: retry-after: 1.290112ms, allowed: 44000/minute")[0m
[31m2024-11-11 07:00:34.120 ERROR (MainThread) [supervisor.supervisor] Update of Supervisor failed: Can't install ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3: 500 Server Error for http+docker://localhost/v1.47/images/create?tag=2024.11.3&fromImage=ghcr.io%2Fhome-assistant%2Famd64-hassio-supervisor&platform=linux%2Famd64: Internal Server Error ("toomanyrequests: retry-after: 1.290112ms, allowed: 44000/minute")[0m
`
```

### System Health information

`## System Information

version | core-2024.11.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.54-haos
arch | x86_64
timezone | America/New_York
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 5000
Installed Version | 2.0.1
Stage | running
Available Repositories | 1460
Downloaded Repositories | 8

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | August 30, 2025 at 8:00 PM
relayer_connected | true
relayer_region | us-east-1
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | true
cloud_ice_servers_enabled | true
remote_server | us-east-1-5.ui.nabu.casa
certificate_status | ready
instance_id | ba9c90057bf44c70812f64955a5a8745
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 13.2
-- | --
update_channel | stable
supervisor_version | supervisor-2024.11.2
agent_version | 1.6.0
docker_version | 27.2.0
disk_total | 28.0 GB
disk_used | 7.6 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Ring-MQTT with Video Streaming (5.7.2), Mosquitto broker (6.4.1), File editor (5.8.0), Terminal & SSH (9.15.0), Matter Server (6.6.0), Studio Code Server (5.17.3)

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 2
views | 4
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | November 6, 2024 at 6:05 PM
-- | --
current_recorder_run | November 11, 2024 at 10:16 AM
estimated_db_size | 111.06 MiB
database_engine | sqlite
database_version | 3.45.3

</details>`

**Comment by erkr** [comment] 2024-11-11 15:44
Yes and the system still is reported unhealthy, what blocks me to update core 🫣

**Comment by Segilmez06** [comment] 2024-11-11 15:52
Same error with supervised installation on my Pi 4. Tried updating and failed. The package seems available on Github.

**Comment by mib1185** [comment] 2024-11-11 16:04
duplicate of #5405

**Comment by Dweinbach** [comment] 2024-11-11 16:12
> duplicate of #5405

I'm not sure why you feel this is a duplicate of 5405 @mib1185 . This report is about HA not tdetecting an update after one has failed, not about the failure to install.

**Comment by mib1185** [comment] 2024-11-11 16:19
because the root cause seems to be the same - compare the error messages in the provided log

**Comment by erkr** [comment] 2024-11-11 16:22
The supervisor update 11.3 is withdrawn, good, but my system remains 'unhealty'. Not good.
The unhealthy state blocks me to update core

**Comment by agners** [comment] 2024-11-11 16:24
Yes, 2024.11.3 has been removed from stable, so that is why you no longer see the update. I've published some background information in the other issue, see: https://github.com/home-assistant/supervisor/issues/5405#issuecomment-2468565190.

I am closing this, since this is part of our remedy.

**Closed by agners** 2024-11-11 16:24 UTC
Labels: bug

**Comment by erkr** [comment] 2024-11-11 16:38
Thanks @agners 
I did a full reboot and the system  health is fix now 😅
