### ISSUE TITLE
Supervisor failing to backup all files in the homeassistant directory

### ISSUE THREAD

**Issue by jcwillox** [home-assistant/supervisor#1633] opened 2020-04-05 12:44 UTC
**Home Assistant release with the issue:**

0.107.7

**Operating environment (HassOS/Generic):**

Rpi3B+

**Supervisor logs:**

20-04-05 01:57:15 WARNING (SyncWorker_4) [supervisor.snapshots.snapshot] Can't snapshot folder homeassistant: [Errno 2] No such file or directory: '/data/homeassistant/home-assistant_v2.db-shm'

**Description of problem:**

Recently a couple of the users of my custom component [Auto Backup](https://github.com/jcwillox/hass-auto-backup) @bluemantwo and @reesion have had an issue where some of the files or folders in their `homeassistant` directory are not being backed up. I personally have not encountered this issue. 

The custom_component makes a request to the Hass.io API for /snapshots/full the request appears to be successful as the snapshot is taken and the backup created. However, it is missing some files, the above warning is generated only when performing a snapshot via the AutoBackup component, snapshots taken through the Web UI work correctly and are not missing any files. The warning is particularly curious, as to my knowledge, the snapshot utility actively excludes `*.db-shm` files.

I don't believe this is an issue with the custom_component as Hass.io is responsible for taking the snapshot, and there should be no way to affect which files are backed up.
The longer version of the supervisor logs can be found at the related issues 
* jcwillox/hass-auto-backup#12
* jcwillox/hass-auto-backup#8

This is very similar to #779 so I understand if this one is closed, but it does differ as they don't get the issue when using the Web UI only when snapshotting via the custom component.

**Comment by TheDK** [comment] 2020-04-14 09:06
I can confirm this issue on 0.107.7 - manual snapshot appears to be complete, auto-backup is not. I believe this to be a critical issue as if you don't continously monitor the system log for warnings you do not realize that you don't have a viable backup.

**Comment by bluemantwo** [comment] 2020-04-25 14:51
I can also confirm this issue.  0.108.8.  Manual snapshot works.  Auto-backup issues a warning when it tries to copy a .db-shm file and stops processing any further backup.  I would consider this a critical error due to lack of clear message that the backup is bad.  It fails silently which is not good for a backup procedure.

**Comment by bluemantwo** [comment] 2020-06-26 05:10
Duplicate of #779

**Comment by bluemantwo** [comment] 2020-06-26 14:47
This should be closed via #1795

**Closed** 2020-06-26 22:16 UTC
