### ISSUE TITLE
Supervisor 2022.11.1 wont install

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/supervisor#4003] opened 2022-11-15 14:39 UTC
### Describe the issue you are experiencing

and the update hangs forever:

<img width="711" alt="Scherm­afbeelding 2022-11-15 om 13 29 13" src="https://user-images.githubusercontent.com/33354141/201947366-8e88c5e9-8abc-4802-8230-b5d5ab1f50c4.png">

restarts still possible, so tried that too, but issue  remains

<img width="532" alt="Scherm­afbeelding 2022-11-15 om 15 35 49" src="https://user-images.githubusercontent.com/33354141/201946190-210a6be7-067c-4e2e-ae12-18f7c7f994af.png">

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1. click Install
2.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
22-11-15 15:34:16 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.STARTUP
22-11-15 15:34:16 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
22-11-15 15:34:16 WARNING (MainThread) [supervisor.jobs] 'StoreManager.reload' blocked from execution, supervisor needs to be updated first
22-11-15 15:34:16 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/beta.json
22-11-15 15:34:18 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
22-11-15 15:34:20 INFO (MainThread) [supervisor.homeassistant.secrets] Request secret authorized_key
22-11-15 15:36:16 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance
```

## System Information

version | core-2022.11.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.7
os_name | Linux
os_version | 5.15.67
arch | x86_64
timezone | Europe/Amsterdam
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4695
Installed Version | 1.28.3
Stage | running
Available Repositories | 1151
Downloaded Repositories | 49

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | August 31, 2023 at 02:00
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
remote_server | eu-central-1-2.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.0
-- | --
update_channel | beta
supervisor_version | supervisor-2022.11.0
agent_version | 1.3.0
docker_version | 20.10.17
disk_total | 458.4 GB
disk_used | 17.0 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | AppDaemon (0.10.0), Home Assistant Google Drive Backup (0.109.1), Log Viewer (0.14.0), MariaDB (2.5.1), Samba share (10.0.0), Studio Code Server (5.4.1), Terminal & SSH (9.6.1), phpMyAdmin (0.8.2), Mosquitto broker (6.1.3), Z-Wave JS (0.1.74), ESPHome (2022.10.2), Matter Server (0.3.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 10
-- | --
resources | 42
views | 97
mode | yaml

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | November 1, 2022 at 04:10
-- | --
current_recorder_run | November 15, 2022 at 15:34
estimated_db_size | 1605.17 MiB
database_engine | mysql
database_version | 10.6.8

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

**Comment by bdraco** [comment] 2022-11-15 15:15
If you had the 2022.11.0 beta installed I had to do this to get mine to update:

```
docker exec -it hassio_supervisor /bin/bash
pip3 install --upgrade dbus-fast
docker restart hassio_supervisor
```

Someone probably has a better way to do this so you might wait for a better fix as this one is a bit risky to do.

**Comment by Mariusthvdb** [comment] 2022-11-15 15:16
ill wait.... ;-)

I did do this though:

after writing this issue I tried to restart... wont go. Even tried the dev channel, but something blocks that too... 
nothing special in logs as far as I see
returning to beta channel, I see a new SU 2022.11.2, and OS 9.3. but still can not restart

**Comment by Mariusthvdb** [comment] 2022-11-15 15:20
now see this in the logs:
```
Logger: homeassistant.components.hassio.handler
Source: components/hassio/handler.py:42 
Integration: Home Assistant Supervisor (documentation, issues) 
First occurred: 15:49:16 (1 occurrences) 
Last logged: 15:49:16

/store return code 500
```

and 
```
Logger: homeassistant.components.hassio
Source: components/hassio/__init__.py:666 
Integration: Home Assistant Supervisor (documentation, issues) 
First occurred: 15:49:16 (1 occurrences) 
Last logged: 15:49:16

Can't read Supervisor data:
```

**Comment by raptor75** [comment] 2022-11-15 15:57
I have the same issue here, except it's from Supervisor 2022.11.0 to 2022.11.2 and same issue updatng Core from 2022.10.4 to 2022.11.2. I am using HAOS in VIrtualBox. There doesn't seem to be anything unusal in the logs I checked. Restart is not always possible. However I restarted from the Virtualbox (using ACPI shutdown then starting back up) and now I cannot take any backups because
_Creating a backup is not possible right now because the system is in startup state_

Let me know if you need me to look somewhere for further information

**Comment by tjorim** [comment] 2022-11-15 16:01
> If you had the 2022.11.0 beta installed I had to do this to get mine to update:
> 
> ```
> docker exec -it hassio_supervisor /bin/bash
> pip3 install --upgrade dbus-fast
> docker restart hassio_supervisor
> ```
> 
> Someone probably has a better way to do this so you might wait for a better fix as this one is a bit risky to do.

I lost access to HA and thus the terminal add-on after a restart, is there a way to get access to the docker command using the host CLI? Seems limited to `ha >`. Can't manually stop/start/restart core, I see the landingpage with su logs.

**Comment by Mariusthvdb** [comment] 2022-11-15 16:08
well, something has changed:

<img width="220" alt="Scherm­afbeelding 2022-11-15 om 17 07 49" src="https://user-images.githubusercontent.com/33354141/201968552-66684c65-e7c7-4c6f-a4c6-6a1a366632f0.png">

and no more SU update showing/pending/skipped

**Comment by tjorim** [comment] 2022-11-15 16:32
> If you had the 2022.11.0 beta installed I had to do this to get mine to update:
> 
> ```
> docker exec -it hassio_supervisor /bin/bash
> # pip3 install --upgrade dbus-fast
> # exit
> docker restart hassio_supervisor
> ```
> 
> Someone probably has a better way to do this so you might wait for a better fix as this one is a bit risky to do.

This kind of worked for me. Only had access to OS CLI (running in a VM).
You can use docker commands by typing `login`.
After the above commands my supervisor was back to 'normal', allowing me to update it to 2022.11.2.
My core is back up but add-ons are having issues, running `su repair` as we speak.

**Comment by mdegat01** [comment] 2022-11-15 16:33
Unfortunately you're going to need to do what bdraco suggested. Because of where this error occurs supervisor can't update itself out of this. Attempting to update gets stuck indefinitely. The alternative solution is this:
```
arch="<INSERT ARCH HERE>"
docker pull "ghcr.io/home-assistant/${arch}-hassio-supervisor:2022.11.2"
docker tag "ghcr.io/home-assistant/${arch}-hassio-supervisor:2022.11.2" "ghcr.io/home-assistant/${arch}-hassio-supervisor:latest"
docker stop hassio_supervisor && docker rm hassio_supervisor
```
Note that you need to put your system arch in `arch` if you use this. If you don't know then do a `docker image ls` and find the supervisor image name that looks like that in the list. Plug in the arch you use.

After those steps are done you don't have to start supervisor again. Observer will remake supervisor's container on the new version and you'll be past this.

This for reference is a general solution to this problem (I use essentially the same process any time I break my dev box with something 😄 ). Bdraco's works fine but is a specific solution to the particular issue at hand.

**Comment by Mariusthvdb** [comment] 2022-11-15 16:37
Hey Mike, I fear for the many users that will be confronted with this issue the next few hours, a more detailed an precise list of commands, probably in a community post, is required....

I mean, I can shell into a terminal, at port 22222, but am afraid need a bit more direction than

> find the supervisor image name that looks like that in the list. Plug in the arch you use.

as will most HAOS users.....

**Comment by raptor75** [comment] 2022-11-15 16:45
When I noticed that the system was having issues with the update I decided to take a virtualbox snapshot before I started investigating what was happening, so in theory I could implement some dangerous stuff and always go back to the snapshot. But I will wait for a proper step-by-step solution for now, unless someone needs me to try something.

**Comment by mdegat01** [comment] 2022-11-15 16:46
Nick's commands make supervisor simply work again. What actually happened [dbus-fast v1.73.0](https://pypi.org/project/dbus-fast/1.73.0/) had a change that broke supervisor. This change was reverted in dbus-fast v1.73.1 and supervisor v2022.11.1 included the new version of dbus-fast and fixed the underlying root cause (a typing issue).

So what Nick's commands do is update dbus-fast within the existing supervisor container. This means even though supervisor is still on the technically broken version it works again since the dependency that was an issue is fixed. The idea being that you then immediately update supervisor and move on. My commands get you to the next version of supervisor manually since supervisor is unable to do that for you.

Both work fine. A third option is to reinstall and restore a backup if you prefer that over any of these commands. When you reinstall it will pull the latest version of supervisor and then you can restore your backup there. That is essentially a way to manually update supervisor without any docker commands if you prefer that.

**Comment by bdraco** [comment] 2022-11-15 16:48
Here is a one liner version of what Mike pasted above
`version="2022.11.2" arch=`docker image ls | grep -- '-hassio-observer'  | awk '{print $1}' | awk -F/ '{print $3}' | awk -F- '{print $1}'` && docker pull "ghcr.io/home-assistant/${arch}-hassio-supervisor:${version}" && docker tag "ghcr.io/home-assistant/${arch}-hassio-supervisor:${version}" "ghcr.io/home-assistant/${arch}-hassio-supervisor:latest" && docker stop hassio_supervisor && docker rm hassio_supervisor`

**Comment by Mariusthvdb** [comment] 2022-11-15 16:49
hehe. And we paste that into the command_line after being logged into the host?

**Comment by raptor75** [comment] 2022-11-15 16:51
> Here is a one liner version of what Mike pasted above
> 
> ```
> version="2022.11.2" arch=`docker image ls | grep -- '-hassio-observer'  | awk '{print $1}' | awk -F/ '{print $3}' | awk -F- '{print $1}'` && docker pull "ghcr.io/home-assistant/${arch}-hassio-supervisor:${version}" && docker tag "ghcr.io/home-assistant/${arch}-hassio-supervisor:${version}" "ghcr.io/home-assistant/${arch}-hassio-supervisor:latest" && docker stop hassio_supervisor && docker rm hassio_supervisor && docker restart hassio_supervisor
> ```

will try this now thanks

**Comment by Mariusthvdb** [comment] 2022-11-15 16:52
> will try this now thanks

please report back ;-)

**Comment by sam43434** [comment] 2022-11-15 16:53
> > Here is a one liner version of what Mike pasted above
> > ```
> > version="2022.11.2" arch=`docker image ls | grep -- '-hassio-observer'  | awk '{print $1}' | awk -F/ '{print $3}' | awk -F- '{print $1}'` && docker pull "ghcr.io/home-assistant/${arch}-hassio-supervisor:${version}" && docker tag "ghcr.io/home-assistant/${arch}-hassio-supervisor:${version}" "ghcr.io/home-assistant/${arch}-hassio-supervisor:latest" && docker stop hassio_supervisor && docker rm hassio_supervisor && docker restart hassio_supervisor
> > ```
> 
> will try this now thanks

Lets go test dummy lol

**Comment by mdegat01** [comment] 2022-11-15 16:54
@Mariusthvdb did you try to restore a backup on the current system? If so then that won't work.

Backups don't really include much from supervisor except the values of its current options. It will not revert to an older version of supervisor. Also since supervisor is the one doing the restoring it won't work if supervisor doesn't work.

That's why I said the third option is a reinstall and then restore a backup. Reinstall will put you on the latest version of supervisor. At that point you should be able to restore everything else around supervisor without issue.

**Comment by raptor75** [comment] 2022-11-15 16:56
> > will try this now thanks
> 
> please report back ;-)

something is wrong, I am still on the same version of supervisor

**Comment by raptor75** [comment] 2022-11-15 16:57
version="2022.11.2" arch=`docker image ls | grep -- '-hassio-observer'  | awk '{print $1}' | awk -F/ '{print $3}' | awk -F- '{print $1}'` && docker pull "ghcr.io/home-assistant/${arch}-hassio-supervisor:${version}" && docker tag "ghcr.io/home-assistant/${arch}-hassio-supervisor:${version}" "ghcr.io/home-assistant/${arch}-hassio-supervisor:latest" && docker stop hassio_supervisor && docker rm hassio_supervisor && docker restart hassio_supervisor

**Comment by Mariusthvdb** [comment] 2022-11-15 16:58
and there is no way to install the [Community Add-on: SSH & Web Terminal](https://github.com/hassio-addons/addon-ssh) in this state, it circles endlessly on Install...

**Comment by raptor75** [comment] 2022-11-15 16:58
![image](https://user-images.githubusercontent.com/4517196/201980328-7681e800-5d58-432e-a66d-832803e20043.png)

**Comment by bdraco** [comment] 2022-11-15 16:59
Might take a few minutes for the observer to recreate the supervisor

**Comment by mdegat01** [comment] 2022-11-15 16:59
@raptor75 so I just told nick the last bit needs to be removed (`docker restart hassio_supervisor`) and its now edited out. The container would already be gone by the previous part. Which then matches what you're seeing in the output there.

It looks like it works otherwise though, I just fixed two systems that way. Can you do an `ha supervisor info`?

**Comment by raptor75** [comment] 2022-11-15 17:00
yeah it is updated I see now

**Comment by raptor75** [comment] 2022-11-15 17:00
thanks.

iI will try the core update now

**Comment by raptor75** [comment] 2022-11-15 17:09
Core update also worked! Thanks!

**Comment by sam43434** [comment] 2022-11-15 17:21
> @Mariusthvdb yea the community addons bit was more a note for anyone that already had it. If you don't have then I would expect you can't install it at the moment due to these issues. You'll have to execute those commands on the host shell instead.

is there no way to manually install a add-on?   managed to fix the Home assistant that is where i currently am,  But the other that is in another house just so happens to not have the SSH & Web Terminal add on  instead has Terminal & SSH which the command doesn't seem to work on?

**Comment by bdraco** [comment] 2022-11-15 17:28
On one system I had to to `systemctl restart hassos-supervisor` as well to get it back online

**Comment by bdraco** [comment] 2022-11-15 17:30
> is there no way to manually install a add-on? managed to fix the Home assistant that is where i currently am, But the other that is in another house just so happens to not have the SSH & Web Terminal add on instead has Terminal & SSH which the command doesn't seem to work on?

You'd have to get into the protected space to do that. If you can't access it remotely and [don't have port 22222 setup](https://developers.home-assistant.io/docs/operating-system/debugging/#home-assistant-operating-system) is to hook up a mouse and keyboard and run that one liner on the console.

**Comment by Murianwind** [comment] 2022-11-15 17:40
If HA is running on Home Assistant Blue, how can I update it?

**Comment by cogneato** [comment] 2022-11-15 17:58
@Murianwind all the same information provided here applies. You either have HA running and access to the cli through an add-on, or you connect directly with keyboard and monitor to run the commands

**Comment by sam43434** [comment] 2022-11-15 17:59
> Since its a pain to type on the console. I also put the one liner up at `https://koston.org/sup_fix.txt`
> 
> Be sure to check it before running it as its not good to blindly run code downloaded from the internet: `curl -o - https://koston.org/sup_fix.txt`
> 
> If it matches and looks good you can run: `curl -o - https://koston.org/sup_fix.txt | sh`

thanks,  That will help abit as one setup ill need to get Non tech person to run it ha

**Comment by mdegat01** [comment] 2022-11-15 18:34
@Murianwind sounds like you have an ssh addon installed and you're trying to ssh in and run it. Ssh addons run in a docker container, you aren't sshing into the host. You need to connect a monitor and keyboard to your device and run it that way as noted above.

**Comment by Jefe2** [comment] 2022-11-15 18:59
The one-liner worked well on my system.  Thanks!
<img width="217" alt="HA Version" src="https://user-images.githubusercontent.com/47016097/202002985-d1a30866-c023-4b82-93a4-e2d60b895b6f.png">

**Comment by FSHelgeland** [comment] 2022-11-15 22:55
> > If you had the 2022.11.0 beta installed I had to do this to get mine to update:
> > ```
> > docker exec -it hassio_supervisor /bin/bash
> > pip3 install --upgrade dbus-fast
> > docker restart hassio_supervisor
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Someone probably has a better way to do this so you might wait for a better fix as this one is a bit risky to do.
> 
> I lost access to HA and thus the terminal add-on after a restart, is there a way to get access to the docker command using the host CLI? Seems limited to `ha >`. Can't manually stop/start/restart core, I see the landingpage with su logs.

I got the same issue here.

**Comment by FSHelgeland** [comment] 2022-11-15 23:20
> > If you had the 2022.11.0 beta installed I had to do this to get mine to update:
> > ```
> > docker exec -it hassio_supervisor /bin/bash
> > # pip3 install --upgrade dbus-fast
> > # exit
> > docker restart hassio_supervisor
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Someone probably has a better way to do this so you might wait for a better fix as this one is a bit risky to do.
> 
> This kind of worked for me. Only had access to OS CLI (running in a VM). You can use docker commands by typing `login`. After the above commands my supervisor was back to 'normal', allowing me to update it to 2022.11.2. My core is back up but add-ons are having issues, running `su repair` as we speak since none of the images exist.

This helped a bit. I am now able to access my HA through local:8123, but I am not able to see any integrations and it is not possible to do an update of the system from 9.0

**Comment by Mariusthvdb** [comment] 2022-11-16 11:08
> That's why I said the third option is a reinstall and then restore a backup. Reinstall will put you on the latest version of supervisor. At that point you should be able to restore everything else around supervisor without issue.

Just had some comments on this option, about people losing their entire history.... 
Guess that is a serious reason to keep this option as last resort.

**Comment by legovaer** [comment] 2022-11-16 11:46
Faced exactly the same issue. Rebooted my RPI4 and it never came back online. I've been looking for that micro HDMI adapter for hours now without any success 😢 

Just restored a back-up, but then home assistant decided to execute the pending updates. So my RPI4 has gone silent again.

Now I'll try to restore a back-up from last week and hope that it won't update. Otherwise I'll have to wait until my new mini-hdmi adapter arrives.

Maybe it's worth mentioning this issue? I'm quite a technical person and I ain't too bothered ATM. But I imagine that there will be users that won't have a clue what's going on.

Thanks for already looking into it <3

**Comment by FSHelgeland** [comment] 2022-11-16 12:53
It is up running again, but it is a bit unstable. Some integrations have to be deactivated and then activated again for them to work and now and then I loose connection.

**Comment by tomg1970** [comment] 2022-11-16 14:40
I just have the problem that I have no more `terminal` on the HA system.
This is installed on a Proxmox server (VM) and there I can not copy the above command via `noVNC` purely because there is no keyboard command for copy/paste.

**Comment by TheZoker** [comment] 2022-11-16 14:43
Does anyone know how to fix this issue within a VM running inside proxmox? I can't use the addon since it won't start :/

**Comment by legovaer** [comment] 2022-11-16 14:49
Mine is also up and running again. Weird behavior I have now after the update: on the addons overview page, all my addons are blacked out. Front end thinks that theyre not running. But they are adding information to the logs.

Example: i use the mosquito MQTT addon. Hassio says its not running, but clearly all my other services are connecting to it and sending data.

**Comment by tomg1970** [comment] 2022-11-16 14:54
> Does anyone know how to fix this issue within a VM running inside proxmox? I can't use the addon since it won't start :/

Same. I can´t copy the script to noVNC

**Comment by TheZoker** [comment] 2022-11-16 15:06
> Same. I can´t copy the script to noVNC

Even then it would not work, since the access over noVNC is not on the host (as far as I know) and only on the HA CLI

**Comment by mdegat01** [comment] 2022-11-16 17:19
@TheZoker The SSH addon in the official add-on repo won't work here. That doesn't actually run on the host shell or have access to the docker cli. The one in the community add-on repo will if you disable protection mode. But you can't install either while supervisor is in this state.

> Same. I can´t copy the script to noVNC

@tomg1970 @TheZoker you don't have to copy and paste anything. That's why hosted the script to make it easy to type out, see [here](https://github.com/home-assistant/supervisor/issues/4003#issuecomment-1315673804). Just type out and run this command on the host shell:
```
curl -o - https://koston.org/sup_fix.txt | sh
```
That will download and run the script that fixes it.
> Even then it would not work, since the access over noVNC is not on the host (as far as I know) and only on the HA CLI

I'm not familiar with noVNC. But if you are looking at the GUI of the host then that is the host shell. That has not been limited to the HA CLI for many releases of HAOS now, it's a full shell. You just type `root` to login.

Even if you are on an old version of HAOS you can still get to the full root shell. I believe you type `login` at the `ha` prompt to do so. If that doesn't work let me know and I'll look it up, haven't had to do that in quite a while so I'm not certain anymore.

**Comment by sean1983** [comment] 2022-11-16 18:24
> @TheZoker The SSH addon in the official add-on repo won't work here. That doesn't actually run on the host shell or have access to the docker cli. The one in the community add-on repo will if you disable protection mode. But you can't install either while supervisor is in this state.
> 
> > Same. I can´t copy the script to noVNC
> 
> @tomg1970 @TheZoker you don't have to copy and paste anything. That's why bdraco hosted the script to make it easy to type out, see [here](https://github.com/home-assistant/supervisor/issues/4003#issuecomment-1315673804). Just type out and run this command on the host shell:
> 
> ```
> curl -o - https://koston.org/sup_fix.txt | sh
> ```
> 
> That will download and run the script that fixes it.
> 
> > Even then it would not work, since the access over noVNC is not on the host (as far as I know) and only on the HA CLI
> 
> I'm not familiar with noVNC. But if you are looking at the GUI of the HAOS then that is the host shell. That has not been limited to the HA CLI for many releases of HAOS now, it's a full shell. You just type `root` to login.
> 
> Even if you are on an old version of HAOS you can still get to the full root shell. I believe you type `login` at the `ha` prompt to do so. If that doesn't work let me know and I'll look it up, haven't had to do that in quite a while so I'm not certain anymore.

I was having the same issues and using Proxmox,   When to the HA CLI via Proxmox,   Typed Login and i was at Shell,  Ran the Curl command and script perfectly!   Thanks

**Comment by Mariusthvdb** [comment] 2022-11-16 18:25
to round this, please see the new post by Paulus
https://community.home-assistant.io/t/supervisor-november-beta-issue-impacting-users-on-home-assistant-beta-dev-channels/489895

**Comment by bschatzow** [comment] 2022-11-20 19:35
I have been following this issue on the forums after having this issue. I don't understand?  Was 2022.11.0 a beta release?  If it was, why

**Comment by tjorim** [comment] 2022-11-20 20:11
> Was 2022.11.0 a beta release?
Yes
> If it was, why wasn't it labeled as such.
Supervisor updates never get labeled as such
> If it wasn't why didn't this release update to most users?
The Home Assistant Version file is leading: https://github.com/home-assistant/version

**Comment by bschatzow** [comment] 2022-11-21 15:57
@tjorim ,
Thank you for responding. I don't understand the rational of not labeling versions so a user knows they are using a beta release verses a stable release. Core beta has a discord channel for discussing issues. Where should issues on supervisor beta be reported / discussed?

**Comment by CajuCLC** [comment] 2022-11-21 21:34
I ended up restarting my pi4 when the update was installing on the UI (the one that doesn't work). Now getting SQUASHFS errors.

**Comment by bschatzow** [comment] 2022-11-21 21:44
@CajuCLC , Mine never completed the update.  Rather than restart I saw the script command and ran it from an SSH 2222 window and it repaired my installation.  Not sure if your system is now corrupt?  Can you SSH to it?

**Comment by CajuCLC** [comment] 2022-11-21 23:29
@bschatzow Not even SSH was working for me. After restarting the pi the hass wouldn't start anymore. Some SQUASHFS and ext4-fs error when trying to restore from a backup (I ended up installing hass fresh again and now trying to restore some backup).

**Comment by CDRX2** [comment] 2022-11-22 09:11
Thanks for that one-liner, it worked perfectly and I was able to update everything!

**Comment by stevanobalabala** [comment] 2022-11-29 09:23
Hi, I'm having exact same issue.  Any solutions that work with Home Assistant OS?

**Comment by laxfiend77** [comment] 2022-12-13 13:22
Is that command supposed to be ran in the homeassistant cli?

**Comment by CDRX2** [comment] 2022-12-13 13:25
Exactly, the command us to be run in the Home Assistant CLI.

**Comment by mdegat01** [comment] 2023-01-11 21:20
closing this as the problematic beta was a while ago at this point and there's a published solution here and on the forum.

**Closed by mdegat01** 2023-01-11 21:20 UTC
Labels: bug
