### ISSUE TITLE
Unable to create ha-core container when config is in a docker subfolder

### ISSUE THREAD

**Issue by cociweb** [home-assistant/supervisor#4366] opened 2023-06-10 21:33 UTC
### Describe the issue you are experiencing

As of upgrade of supervisor from 2023.05.1 to 2023.06.X and/or ha-core 2023.06.X the ha-core does not create neither automatically (apparmor), nor `ha core start` command when the configuration files are witihin the docker default config storage (sub)folder.

This was not a problem on the previous releases 2023.05

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Debian

### Steps to reproduce the issue

1. get the root dir of docker with `docker info`. the result should say:
```
...
 Docker Root Dir: /path/to/config/of/docker
...
```
2. create a subfolder within the root of docker:
mkdir -p /path/to/config/of/docker/and/this/is/hassio
3. Install supervised with the official installer: https://github.com/home-assistant/supervised-installer. Where DATA_SHARE= is a the path of step2.
4. check the logs, where it says:
`Error: Can't create container from homeassistant: 400 Client Error for http+docker://localhost/v1.41/containers/create?name=homeassistant: Bad Request ("invalid mount config: must use either propagation mode "rslave" or "rshared" when mount source is within the daemon root, daemon root: "/path/to/config/of/docker", bind mount source: "/path/to/config/of/docker/and/this/is/hassio/share", propagation: "slave"")`

### Anything in the Supervisor logs that might be useful for us?

```txt
23-06-10 23:19:37 ERROR (SyncWorker_1) [supervisor.docker.manager] Can't create container from homeassistant: 400 Client Error for http+docker://localhost/v1.41/containers/create?name=homeassistant: Bad Request ("invalid mount config: must use either propagation mode "rslave" or "rshared" when mount source is within the daemon root, daemon root: "/path/to/config/of/docker", bind mount source: "/path/to/config/of/docker/and/this/is/hassio/share", propagation: "slave"")
23-06-10 23:22:40 INFO (MainThread) [supervisor.jobs] 'MountManager.reload' blocked from execution, mounting not supported on system
```

### System Health information

N/A - ha-core not  able to start

### Supervisor diagnostics

N/A

**Comment by ljmellor** [comment] 2023-06-11 11:19
I'm getting very similar entries in the logs of my supervised installation. The network mount section of HA settings informs me that mounting isn't supported by my operating system (Debian 11). If anyone gets to the bottom of this I'll be very happy, I can't suss it for love nor money.

`INFO (MainThread) [supervisor.jobs] 'MountManager.reload' blocked from execution, mounting not supported on system`

`Home Assistant 2023.6.1
Supervisor 2023.06.1
Frontend 20230608.0 - latest`

Debian 11 running on a Lenovo Thinkcentre Tiny M73

**Comment by cociweb** [comment] 2023-06-11 21:30
maybe the [line ](https://github.com/home-assistant/supervisor/blob/fb90e6d07e3bfa89b644b8b571b701a6561438a5/supervisor/docker/homeassistant.py#L100) modification to `propagation=PropagationMode.RSLAVE.value` could be enough. Any confirmation?

**Comment by cociweb** [comment] 2023-06-12 09:19
/media and /share mounts suffer from this. PR is attached above, it should resolve the issue and allow to start HA-Core

**Comment by cociweb** [comment] 2023-06-13 19:46
additional observation: every 15 mins I get the following log entry, but I don't know what is it related:
`23-06-13 20:49:27 INFO (MainThread) [supervisor.jobs] 'MountManager.reload' blocked from execution, mounting not supported on system`

**Comment by mdegat01** [comment] 2023-06-13 20:56
In truth, this config isn't supported. I get that the installer has a `DATA_SHARE` option but that is only supported to the extent that it causes zero issues compared to the default config. If the root cause of an issue is `DATA_SHARE=` is set to something other then default that issue should be rejected as unsupported config and a check added to let users know that.

That being said, you added a PR which fixes it. And I see no downside to making this change for supported configs. So I'm fine with making it for now. There are CI issues that need to be fixed as noted in the PR, once fixed it can be merged.

But I just want to make sure that you are aware of the situation. Supervisor will not add tests for "a supervised install with the data share folder set within the docker root folder". Nor will it add tests for a supervised install with data share set to anywhere besides the default location. So changing that option may result in unexpected breakages in future updates and most likely issues will be rejected if they do.

**Closed** 2023-06-14 21:40 UTC
Labels: bug

**Comment by cociweb** [comment] 2023-06-15 20:24
Actually, after a few try, the RSHARED option gave me better startup performance, and disappeares the https://github.com/home-assistant/supervisor/issues/4366#issuecomment-1589919598 periodical error on top of the ones which are popes up at boot-time (related to /share, /media) and prevented the deny of core and addon starts (where RSLAVE provided the solution instead of the single SLAVE). I hope, when propagation was introduced (and changed from the [default](https://docs.docker.com/storage/bind-mounts/#configure-bind-propagation) RPRIVATE to SLAVE) it was designed, and works as it. My RSLAVE is only an extension/fix for the original SLAVE and not introduce functional change/addition as RSHARE do. - But it would be worth considering.
