### ISSUE TITLE
Can not install this update. Gives server error

### ISSUE THREAD

**Issue by joost11111** [home-assistant/supervisor#5407] opened 2024-11-11 11:10 UTC
### Describe the issue you are experiencing

Can not install this update. Gives server error. See attached image

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

![Capture](https://github.com/user-attachments/assets/1318bbc2-8486-4def-820e-a5edc219d530)

### Anything in the Supervisor logs that might be useful for us?

```txt
Can not install this update. Gives server error. See attached image
```

### System Health information

Can not install this update. Gives server error. See attached image

**Comment by sanderkooger** [comment] 2024-11-11 11:12
duplicate of https://github.com/home-assistant/supervisor/issues/5406

**Comment by joost11111** [comment] 2024-11-11 11:16
Logger: homeassistant.components.websocket_api.http.connection
Bron: components/websocket_api/commands.py:245
integratie: Home Assistant WebSocket API (documentatie, problemen)
Eerst voorgekomen: 12:07:04 (3 gebeurtenissen)
Laatst gelogd: 12:13:20

[547807088208] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 262, in async_install
    await self.coordinator.supervisor_client.supervisor.update()
  File "/usr/local/lib/python3.12/site-packages/aiohasupervisor/supervisor.py", line 43, in update
    await self._client.post(
  File "/usr/local/lib/python3.12/site-packages/aiohasupervisor/client.py", line 173, in post
    return await self._request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohasupervisor/client.py", line 122, in _request
    raise exc_type(result.message, result.job_id)
aiohasupervisor.exceptions.SupervisorBadRequestError: Update of Supervisor failed: Can't install ghcr.io/home-assistant/aarch64-hassio-supervisor:2024.11.3: 404 Client Error for http+docker://localhost/v1.47/images/ghcr.io/home-assistant/aarch64-hassio-supervisor:2024.11.3/json: Not Found ("No such image: ghcr.io/home-assistant/aarch64-hassio-supervisor:2024.11.3")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 157, in async_install
    await entity.async_install_with_progress(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 502, in async_install_with_progress
    await self.async_install(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 264, in async_install
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Error updating Home Assistant Supervisor: Update of Supervisor failed: Can't install ghcr.io/home-assistant/aarch64-hassio-supervisor:2024.11.3: 404 Client Error for http+docker://localhost/v1.47/images/ghcr.io/home-assistant/aarch64-hassio-supervisor:2024.11.3/json: Not Found ("No such image: ghcr.io/home-assistant/aarch64-hassio-supervisor:2024.11.3")

**Comment by ErnestoBrandao** [comment] 2024-11-11 11:21
same for me

**Comment by heibertelf** [comment] 2024-11-11 11:55
Confirm problem
![image](https://github.com/user-attachments/assets/6ae92390-c8d5-4add-8e5e-0adec58feee0)

**Comment by metbril** [comment] 2024-11-11 12:18
Duplicate of #5405 ?!
![image](https://github.com/user-attachments/assets/ca5d8ecc-a467-4259-b56e-91af1daa9c6a)

**Comment by agners** [comment] 2024-11-11 12:49
Duplicate of #5405, so closing.

**Closed by agners** 2024-11-11 12:49 UTC
Labels: bug
