### ISSUE TITLE
Image homeassistant/amd64-addon-zwave_js:0.1.96 does not exist for addon_core_zwave_js

### ISSUE THREAD

**Issue by louisostrowski** [home-assistant/supervisor#4610] opened 2023-10-07 01:22 UTC
### The problem

Failed setup will retry error with none in error description 

### What version of Home Assistant Core has the issue?

Core-2023-10-1

### What was the last working version of Home Assistant Core?

2023-09-3

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

Zwave JS

### Diagnostics information

![IMG_3755](https://github.com/home-assistant/core/assets/48015857/96c296c2-f5c4-431f-bf29-a5f319d84a76)

**Comment by hendrix04** [comment] 2023-10-08 13:03
Do we have an RCA on this issue?

From someone who isn't familiar with how HA handles these docker add-ons, it seems like the add-on upgraded its docker dependency, but there is no process in place for HA to pull that new dependency.

Is this an issue of a lack "package lock" / package management within HA?

Is there any process in place for this?

Did the developer not follow some standard process that would have avoided this?

What do we need to do in the future to have appropriate checks the prevent this issue from happening again?

**Comment by iloveicedgreentea** [comment] 2023-10-08 17:50
I had an issue with both the js add-on and the integration after upgrading to 10.1, and random failures with some devices like a zen17. The add-on refused to start (no error) after I restarted it. It loaded the container just fine it just did not update the start status. It also added a duplicate integration with a ton of disabled entities. 

Restoring from the 9.x backup fixed my issues. 

I did not have any error regarding the docker image and it was outputting logs without being marked as started, so it seemed to be starting okay. My devices were just unavailable at that time.

**Comment by agners** [comment] 2023-10-09 06:57
Can someone who experience this issue please attach the full Supervisor logs from Settings > System > Logs, then choose Supervisor on the top right.

**Comment by FirewizzNL** [comment] 2023-10-09 07:50
> Can someone who experience this issue please attach the full Supervisor logs from Settings > System > Logs, then choose Supervisor on the top right.

[supervisor_2023-10-09T07-48-52.043Z.log](https://github.com/home-assistant/supervisor/files/12843655/supervisor_2023-10-09T07-48-52.043Z.log)

**Comment by agners** [comment] 2023-10-09 08:00
@FirewizzNL thank you very much :pray: . Unfortunately the log is a bit too short to show the crucial problems (right after the udpate).

Can you get the logs through a terminal with the following command?

```
ha host logs --identifier hassio_supervisor --lines 1000
```

**Comment by FirewizzNL** [comment] 2023-10-09 08:25
@agners That is still of no use, nothing else then that there.
But I updated more than a week ago, just stopped working yesterday, atleast then I noticed

**Comment by FirewizzNL** [comment] 2023-10-09 08:32
@agners Solved it with solution above to pull the missing docker container.
If needed I can post detailed manual to do this.

**Comment by FirewizzNL** [comment] 2023-10-09 08:38
For people who need a detailed description of a fix:

1) Install "Advanced SSH & Web Terminal" through "Add-ons" menu
2) When installed open the addon and disable the switch for "protection mode"
3) Find missing docker file by going to add-on -> Z-Wave JS and press start, it should notify you the missing file
4) Start the advanced terminal add-ons -> advanced... and click "open web-UI"
5) run "docker pull YOUR_MISSING_FILE" In my case 'homeassistant/amd64-addon-zwave_js:0.1.96'
6) restart add-on Z-wave and zwave service or reboot device.
7) Enjoy zwave again

**Comment by agners** [comment] 2023-10-09 08:39
> @agners That is still of no use, nothing else then that there. But I updated more than a week ago, just stopped working yesterday, atleast then I noticed

You can bump the line numbers even higher, if that helps. But yeah, if its more than a week, you might not have a lot of log buffer to get back to when the update happened :cry:

**Comment by FirewizzNL** [comment] 2023-10-09 08:41
@agners I think the fix is easy enough to do in this case. The problem seems to be the case that the docker container was not correctly retrieved when updated.

**Comment by agners** [comment] 2023-10-09 09:57
> The problem seems to be the case that the docker container was not correctly retrieved when updated.

How do you know?


Typically, connection errors like connection reset get properly handled. The update fails in this cases, and deleting the old images doesn't continue:

![image](https://github.com/home-assistant/supervisor/assets/34061/130a9169-981f-4dd9-81a0-915c83e6a31d)


It might be that a particular type of download error doesn't get handled correclty, but so far I am not able to reproduce the problem here :cry:  To better understand what is happening the logs from Supervisor right when this happened would be really helpful.

**Comment by FirewizzNL** [comment] 2023-10-09 10:14
I have nothing that helps I am afraid in my logs.
I checked my logs and excluded all the dns checks and not exist lines and this remains:
![image](https://github.com/home-assistant/supervisor/assets/28536443/e7e290ee-c06d-4ce5-8dd4-086b73186c29)

**Comment by agners** [comment] 2023-10-09 11:56
Hm, I see. Thanks for checking!

**Comment by cuppieinc** [comment] 2023-10-09 16:30
Just FYI. Having the same issue I reverted back to version 0.1.94 via a backup restore. Today I wanted to follow the manual steps to do the correct upgrade to 0.1.96 as described by [FirewizzNL] but after upgrading z-wave.js from within the add-on section it just updated and started correct. Seems the upgrade is working now

**Comment by KroniK907** [comment] 2023-10-09 16:55
I had this same issue. I reverted to version 0.1.93 (which was the version available to me in my backups) and then manually updated the Z-Wave JS addon back to 0.1.96. This seems to have installed 0.1.96 successfully as it is now running without error. 

It seems the issue was isolated to updating via the automatic update procedure.

**Comment by agners** [comment] 2023-10-09 16:57
@KroniK907 hm, interesting observation.

@cuppieinc @FirewizzNL and others, do you have automatic update enabled?

**Comment by cuppieinc** [comment] 2023-10-09 17:23
Yes, I have automatic updates enabled, my initial update also broke by the automatic update at October 7th

**Comment by cuppieinc** [comment] 2023-10-09 17:45
interesting. After the manual upgrade to 0.1.96 I rebooted my PI, just to make sure all was OK after a reboot, now the z-wave add-on pops up with another update to 0.1.97. Just did a manual upgrade again, all OK, z-wave is up and running

**Closed** 2023-10-11 16:22 UTC

**Comment by KroniK907** [comment] 2023-10-12 16:26
I went digging and was able to get the following from the supervisor logs:
[hassio_supervisor log with zwave-js error.txt](https://github.com/home-assistant/supervisor/files/12884880/hassio_supervisor.log.with.zwave-js.error.txt)

Hopefully this helps confirm if #4619 was the culprit. Sorry I didn't go digging for this earlier.
