### ISSUE TITLE
http://supervisor/core/check": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/supervisor#2871] opened 2021-05-11 21:05 UTC
### Describe the issue you are experiencing

the above error is displayed when checking the config from the command line

### What is the used version of the Supervisor?

supervisor-2021.04.3

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

Home Assistant OS 5.13

### What version of Home Assistant Core is installed?

core-2021.5.2

### Steps to reproduce the issue

1. login ssh root@hassio.local
2. ha core check
3. eror is displayed
...

### Anything in the Supervisor logs that might be useful for us?

```txt
21-05-11 21:04:16 INFO (MainThread) [supervisor.api.security] /network/info access from core_ssh
21-05-11 21:04:16 INFO (MainThread) [supervisor.api.security] /host/info access from core_ssh
21-05-11 21:04:16 INFO (MainThread) [supervisor.api.security] /core/info access from core_ssh
21-05-11 21:04:21 INFO (MainThread) [supervisor.api.security] /core/check access from core_ssh
21-05-11 21:04:21 INFO (SyncWorker_0) [supervisor.docker] Runing command 'python3 -m homeassistant -c /config --script check_config' on homeassistant/raspberrypi4-homeassistant
```

btw note the typo there: Runing command instead of Running command ....
### Additional information

this is final return:
```
~ $ ha core check
Processing... Done.

Post "http://supervisor/core/check": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
~ $
```

**Comment by frenck** [comment] 2021-05-11 21:41
Related to / Duplicate of home-assistant/cli#292

**Closed by frenck** 2021-05-11 21:41 UTC
Labels: bug
