### ISSUE TITLE
Latest version points to dev instead of latest.

### ISSUE THREAD

**Issue by mariushosting** [home-assistant/supervisor#3940] opened 2022-10-11 12:55 UTC
### Describe the issue you are experiencing

Installed version
2022.10.dev0702
Latest version
2022.10.0

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1.
2.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
everything works like a charm
```

### System Health information

health

### Additional information

No additional info

**Comment by frenck** [comment] 2022-10-11 13:00
I'm not sure what the issue is you are trying to raise? Could you maybe explain it in a different way?

**Comment by mariushosting** [comment] 2022-10-11 13:10
> I'm not sure what the issue is you are trying to raise? Could you maybe explain it in a different way?

when I'm downloading latest tag version 2022.10.0 https://github.com/home-assistant/supervisor/releases/tag/2022.10.0
I get installed version 2022.10.dev0702 instead of 2022.10.0

**Comment by mdegat01** [comment] 2022-10-11 14:51
Right because that is latest. Releases when cut become betas. Betas become stable when [this file](https://github.com/home-assistant/version/blob/master/stable.json) is updated.

Every commit triggers a new dev release. So latest is always going to track dev.

**Comment by kthxboosty** [comment] 2022-10-11 20:59
I think the confusion is about the tags of the docker images. The tags are not used the same for all repositories. Example:

* For https://hub.docker.com/r/homeassistant/home-assistant/tags `latest` points to the latest stable, and `dev` points to latest dev version.
* For https://hub.docker.com/r/homeassistant/amd64-hassio-supervisor/tags however, there is no `dev` tag, only `latest`, which does not always point to the latest stable version. So if you want to get the latest stable version from this repository, there is no tag for that.

**Comment by frenck** [comment] 2022-10-11 21:04
The Docker supervisor tags are not meant to be consumed manually, as this is a managed system. The latest tag on Docker for the supervisor is therefore not relevant, nor actively used.

**Comment by cociweb** [comment] 2022-10-17 11:19
> Please note, that in the Docker world, a general misconception is that `latest` is stable

I think there is a misunderstanding from the develeopers vs users point of view about the tags in the github/docker world. The non-developers would like to use (mainly in automation update processes) the latest stable release: what ever it is called: `stable`, `latest`, `hollycow` - practically, a static tag (or branch name) is very useful (alongside the unique tag, in this case: 2022.10.0). But it is very important to strongly distingish from the latest dev branch/image: `dev`, `not-stable` `hollydog`, +  `any-other-dínamic-tag`. 
So in case of a stable release build it is always practically recommended to build it at least with 4 tags...

**Comment by frenck** [comment] 2022-10-17 11:21
> I think there is a misunderstanding from the develeopers vs users point of view 

I don't think so. Non of these tags are even usable for an end-user. As these are not containers that can or should be consumed directly at all. So I'm missing the whole point that is being made in this issue to being with.

**Comment by kthxboosty** [comment] 2022-10-17 14:18
> As these are not containers that **can** or should be consumed directly at all.

Well, technically nothing will prevent a user from doing a `docker run [...] homeassistant/amd64-hassio-supervisor`. There's no Docker hub overview/notes that tell you otherwise. Of course, if you read all of the manuals and readmes, you will probably at some point encounter a line that sais you shouldn't do that.

But what I think is confusing from the point of users, is this:

<img width="394" alt="Screenshot 2022-10-11 at 23 20 17" src="https://user-images.githubusercontent.com/4265101/196199463-802e5406-37e6-4ebd-b6df-65f172a82d8e.png">

These GitHub labels are used in various places, and once you have seen this, you are only a fraction away from thinking that this tag is also used the same way for the docker container.

Except for adding a note to the place where people are most likely discover separate containers, I don't think there's much you can do to prevent this from happening.

**Comment by frenck** [comment] 2022-10-17 14:40
> Well, technically nothing will prevent a user from doing a docker run [...] homeassistant/amd64-hassio-supervisor.

That is not a supported use case and not a consideration.

> These GitHub labels are used in various places, and once you have seen this, you are only a fraction away from thinking that this tag is also used the same way for the docker container.

GitHub labels have nothing to do with Docker.

Yet again, nothing here is for manual consumption, nor is there any use case to process any Docker label/tag manually.

**Comment by kthxboosty** [comment] 2022-10-17 15:13
I'm aware - my point in both cases is: users may simply not know this and make assumptions.
And if you are fed red herrings here and there (Github labels vs. Docker tags with the same name), it is an easy mistake to make.

**Comment by cociweb** [comment] 2022-10-17 19:37
moreover, the supervised installer refers to the latest tag.
![image](https://user-images.githubusercontent.com/1935413/196266804-b8889dde-cc2d-4d19-badd-f7ed43ee3acc.png)

**Comment by frenck** [comment] 2022-10-17 20:05
> moreover, the supervised installer refers to the latest tag.

That is an internal tag on the system, not related to remote.

**Comment by frenck** [comment] 2022-10-17 20:10
> it will be ideal if we have a :stable one instead of latest dev.

Why? What would it bring? You can't use it...

**Comment by mariushosting** [comment] 2022-10-17 20:11
I will prepare some screenshot, to give you an idea. Please give me a moment.

**Comment by frenck** [comment] 2022-10-17 20:13
Just to point out: At this point, the only arguments made are about: "How it works in some Docker environments", while we use Docker, it isn't managed using Docker and those concepts are not used/do not apply here.

So, unless, a proper use case can be provided that makes something like this absolutely useful or required; I will close this issue (as this is not really an issue, but more like a feature request missing a use case at this point).

../Frenck

**Comment by mariushosting** [comment] 2022-10-17 21:15
Here is the problem in my case. I have installed The Supervisor using the latest tag then Homeassistant tell me I don't have the latest image but the dev one. 
![1homeassistant](https://user-images.githubusercontent.com/37554361/196284914-5092a0df-d05f-4d9f-80fe-2aff5eca9d51.png)

**Comment by frenck** [comment] 2022-10-17 21:36
>  I have installed The Supervisor using the latest tag then Homeassistant tells me I don't have the latest image, but the dev one

How did you get that?

**Comment by mariushosting** [comment] 2022-10-17 21:39
https://mariushosting.com/how-to-install-home-assistant-supervisor-on-your-synology-nas/

For now I have changed the code in the script at STEP 6 to point to version :2022.10.0 instead of :latest because the :latest tells me I have installed the dev one not the "latest".

**Comment by frenck** [comment] 2022-10-17 21:47
> [mariushosting.com/how-to-install-home-assistant-supervisor-on-your-synology-nas](https://mariushosting.com/how-to-install-home-assistant-supervisor-on-your-synology-nas/)

That is not a correct and/or supported method/way of running it. It is, therefore beyond the scope of the Home assistant project (as specified in the Home Assistant architectural decisions records). We don't recommend running it in such a way and do not guarantee it will keep running either.

Issues caused by running an unsupported method are yours and yours alone.

For information and instructions on installing Home Assistant in a supported way, please consult our documentation here: <https://www.home-assistant.io/installation>

Going to close this issue, as its source cause is not supported by our project.

../Frenck

**Closed by frenck** 2022-10-17 21:47 UTC
Labels: bug, unsupported
