### ISSUE TITLE
`supervisor_version` not stored properly in backup.json

### ISSUE THREAD

**Issue by bdr99** [home-assistant/supervisor#4069] opened 2022-12-26 19:54 UTC
### Describe the issue you are experiencing

When I create a backup using the backups feature, the `supervisor_version` property in the backup.json file from the backup tar archive is not set correctly.

Based on this code:

https://github.com/home-assistant/supervisor/blob/c193c91fe7ad16165a91c200b746e913a0fa7b37/supervisor/backups/backup.py#L179-L185

I would expect the first few lines of backup.json to look like this:
```json
{
  "version": 2,
  "slug": "3cb7ce75",
  "name": "test",
  "date": "2022-12-26T19:37:55.998989+00:00",
  "type": "full",
  "supervisor_version": "2022.11.2",
```

But instead, this is what I see in backup.json:
```json
{
  "version": 2,
  "slug": "3cb7ce75",
  "name": "test",
  "date": "2022-12-26T19:37:55.998989+00:00",
  "type": "full",
  "2022.11.2": "2022.11.2",
```

It seems that somehow, it is using the actual supervisor version number as the key, instead of the string `"supervisor_version"`.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1. Create a backup using the backups feature.
2. Download the backup.
3. Extract the tar archive and look at the backup.json.

### Anything in the Supervisor logs that might be useful for us?

```txt
N/A
```

## System Information

version | core-2022.12.8
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.7
os_name | Linux
os_version | 5.15.80
arch | x86_64
timezone | America/New_York
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4992
Installed Version | 1.29.0
Stage | running
Available Repositories | 1196
Downloaded Repositories | 12

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.4
-- | --
update_channel | stable
supervisor_version | supervisor-2022.11.2
agent_version | 1.4.1
docker_version | 20.10.19
disk_total | 30.8 GB
disk_used | 6.8 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | AdGuard Home (4.7.5), SSH & Web Terminal (13.0.0), Z-Wave JS (0.1.74), Studio Code Server (5.5.0), ESPHome (beta) (2022.12.3), Samba share (10.0.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 7
views | 9
mode | yaml

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | December 26, 2022 at 12:19 AM
-- | --
current_recorder_run | December 26, 2022 at 10:54 AM
estimated_db_size | 279.54 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

### Supervisor diagnostics

[config_entry-hassio-995d9c0d5b056993a26e6d9142c59ecd.json.txt](https://github.com/home-assistant/supervisor/files/10304657/config_entry-hassio-995d9c0d5b056993a26e6d9142c59ecd.json.txt)

**Comment by mdegat01** [comment] 2023-01-11 17:49
Good catch! Super strange one. Cannot be reproduced in tests or in devcontainer because the value of the constant was actually being replaced in the built image by the github action.

It should be fixed next version of supervisor.

**Comment by bdr99** [comment] 2023-01-11 17:53
Wow, yeah that is a strange one. I spent some time debugging it myself, but I never would have guessed that the problem was with a github action. I'm glad you were able to track down the issue.

**Comment by mdegat01** [comment] 2023-01-11 17:59
Actually I'll leave this open until the github action is actually bumped as that's the fix

**Comment by mdegat01** [comment] 2023-01-11 18:01
Oh nvm this one simply uses master. So this will be resolved next version as is.

**Closed by mdegat01** 2023-01-11 18:01 UTC
Labels: bug
