### ISSUE TITLE
Latest Supervisor is crash-looping

### ISSUE THREAD

**Issue by phellarv** [home-assistant/supervisor#3718] opened 2022-07-06 16:01 UTC
### Describe the issue you are experiencing

Infinite restart loop of the Supervisor-container after reboot of server.

### What is the used version of the Supervisor?

Cannot tell - system is down

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

### What is the version of your installed operating system?

Ubuntu 22.04

### What version of Home Assistant Core is installed?

2022.6.7

### Steps to reproduce the issue

Rebooted system

### Anything in the Supervisor logs that might be useful for us?

```txt
[15:49:26] INFO: Supervisor restart after closing
[15:49:26] INFO: Watchdog restart after closing
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/udev.sh
[15:59:43] INFO: Using udev information from host
cont-init: info: /etc/cont-init.d/udev.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun supervisor (no readiness notification)
services-up: info: copying legacy longrun watchdog (no readiness notification)
s6-rc: info: service legacy-services successfully started
[15:59:43] INFO: Starting local supervisor watchdog...
22-07-06 15:59:43 INFO (MainThread) [__main__] Initializing Supervisor setup
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/src/supervisor/supervisor/__main__.py", line 41, in <module>
    coresys = loop.run_until_complete(bootstrap.initialize_coresys())
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/usr/src/supervisor/supervisor/bootstrap.py", line 63, in initialize_coresys
    coresys = CoreSys()
  File "/usr/src/supervisor/supervisor/coresys.py", line 66, in __init__
    self._docker: DockerAPI = DockerAPI()
  File "/usr/src/supervisor/supervisor/docker/__init__.py", line 106, in __init__
    self._info: DockerInfo = DockerInfo.new(self.docker.info())
  File "/usr/src/supervisor/supervisor/docker/__init__.py", line 62, in new
    data["CgroupVersion"],
KeyError: 'CgroupVersion'
22-07-06 15:59:43 ERROR (MainThread) [asyncio] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fa4f9dbaca0>
[15:59:43] WARNING: Halt Supervisor
```

**Comment by andrewjfreyer** [comment] 2022-07-06 16:04
Same error here.

**Comment by wbrocker** [comment] 2022-07-06 16:05
Same error here as well. Running the same versions as mentioned above.

**Comment by frenck** [comment] 2022-07-06 16:07
Duplicate of #3692

**Closed by frenck** 2022-07-06 16:07 UTC
Labels: bug

**Comment by Velly56** [comment] 2022-07-06 16:24
Same for me.

**Comment by phellarv** [comment] 2022-07-06 16:29
Solution from #3692 did not solve the problem. Request this to be reopened.

**Comment by mdegat01** [comment] 2022-07-06 16:33
Ubuntu is not a supported OS for Home Assistant Supervised so this isn't a bug unless it can be reproduced in a supported installation. Would suggest switching to a [supported installation method](https://www.home-assistant.io/installation/linux#install-home-assistant-supervised)

**Comment by kcrexchan** [comment] 2022-07-10 05:54
I had to force upgrading Docker. Just `sudo apt upgrade` did not upgrade Docker for me. May be because Docker was still running. This was what I did:
sudo systemctl stop docker
sudo apt install docker-ce
sudo reboot
sudo systemctl start docker

hope it helps...

**Comment by mykola-dev** [comment] 2022-07-11 18:39
guys, is it possible to disable automatic updates for the supervisor? i'm running pretty critical stuff under home assistant. and that fact it suddenly stops working doesn't add the value for the product.
