### ISSUE TITLE
Can not delete backups/snapshots after upgrading to 2021.9.1

### ISSUE THREAD

**Issue by Dayve67** [home-assistant/supervisor#3104] opened 2021-09-03 12:56 UTC
### Describe the issue you are experiencing

Get error when trying to delete backups.

https://community.home-assistant.io/t/just-upgraded-to-2021-9-1-can-not-delete-backups/335341/3

### What is the used version of the Supervisor?

2021.08.1

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

Home Assistant OS 6.2

### What version of Home Assistant Core is installed?

2021.9.1

### Steps to reproduce the issue

1.Check a current backup
2.Select delete
3.Press OK in the box
...

### Anything in the Supervisor logs that might be useful for us?

```txt
21-09-03 07:32:33 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'snapshot_exclude' is deprecated, 'backup_exclude' should be used instead. Please report this to the maintainer of deCONZ
21-09-03 07:32:33 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'snapshot_post' is deprecated, 'backup_post' should be used instead. Please report this to the maintainer of MariaDB
21-09-03 07:32:33 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'snapshot_pre' is deprecated, 'backup_pre' should be used instead. Please report this to the maintainer of MariaDB
21-09-03 07:32:33 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'snapshot_exclude' is deprecated, 'backup_exclude' should be used instead. Please report this to the maintainer of ESPHome
21-09-03 07:32:33 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'snapshot' is deprecated, 'backup' should be used instead. Please report this to the maintainer of UniFi Controller
21-09-03 07:32:33 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'snapshot_exclude' is deprecated, 'backup_exclude' should be used instead. Please report this to the maintainer of AdGuard Home
21-09-03 07:32:33 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'snapshot_exclude' is deprecated, 'backup_exclude' should be used instead. Please report this to the maintainer of deCONZ
21-09-03 07:32:33 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'snapshot_post' is deprecated, 'backup_post' should be used instead. Please report this to the maintainer of MariaDB
21-09-03 07:32:33 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'snapshot_pre' is deprecated, 'backup_pre' should be used instead. Please report this to the maintainer of MariaDB
21-09-03 07:32:33 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'snapshot_exclude' is deprecated, 'backup_exclude' should be used instead. Please report this to the maintainer of ESPHome
21-09-03 07:32:33 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'snapshot' is deprecated, 'backup' should be used instead. Please report this to the maintainer of UniFi Controller
21-09-03 07:32:33 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'snapshot_exclude' is deprecated, 'backup_exclude' should be used instead. Please report this to the maintainer of AdGuard Home

21-09-03 08:38:34 INFO (MainThread) [supervisor.backups.manager] Found 9 backup files
21-09-03 08:38:34 INFO (MainThread) [supervisor.backups.manager] Found 9 backup files
```

**Comment by ludeeus** [comment] 2021-09-03 12:58
Duplicate of https://github.com/home-assistant/supervisor/issues/3102

**Closed by ludeeus** 2021-09-03 12:58 UTC
Labels: bug
