### ISSUE TITLE
Using the new addon_config map value in an add-on config makes the Supervisor to unable to start the add-on

### ISSUE THREAD

**Issue by lmagyar** [home-assistant/supervisor#4692] opened 2023-11-10 20:40 UTC
### Describe the issue you are experiencing

Adding this to the add-on's config.yaml:
```
map:
  - addon_config:rw
```

Results in the below error when I try to start the add-on:
```
Failed to start add-on
Can't create container from <SLUG>: 400 Client Error for http+docker://localhost/v1.43/containers/create?name=<SLUG>: Bad Request ("invalid mount config for type "bind": bind source path does not exist: /mnt/data/supervisor/addon_configs/<SLUG>")
```

Creating the folder manually resolves the issue, the add-on starts normally and can access it's private `/config` folder.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

See above.

### Anything in the Supervisor logs that might be useful for us?

```txt
-
```

### System Health information

-

**Comment by frenck** [comment] 2023-11-10 20:41
duplicate of #4689, fixed in #4690

**Closed by frenck** 2023-11-10 20:41 UTC
Labels: bug
