### ISSUE TITLE
Bluetooth not available after update of supervisor 246 to 249

### ISSUE THREAD

**Issue by DavidtheMaster64** [home-assistant/supervisor#2161] opened 2020-10-22 12:49 UTC
**Home Assistant release with the issue:**
0.116.4

**Operating environment (HassOS/Generic):**
HassOS 4.14
Raspberry Pi 3B

**Supervisor logs:**
nothing special there

**Home Assistant logs:**
```2020-10-22 10:02:04 ERROR (MainThread) [homeassistant.components.bluetooth_tracker.device_tracker] Error looking up Bluetooth device
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/bluetooth/bluez.py", line 289, in _gethcisock
    sock = _bt.hci_open_dev (device_id)
_bluetooth.error: no available bluetoot devices
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/bluetooth_tracker/device_tracker.py", line 146, in perform_bluetooth_update
    device_name = await hass.async_add_executor_job(lookup_name, mac)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/bluetooth_tracker/device_tracker.py", line 108, in lookup_name
    return bluetooth.lookup_name(mac, timeout=5)
  File "/usr/local/lib/python3.8/site-packages/bluetooth/bluez.py", line 61, in lookup_name
    sock = _gethcisock ()
  File "/usr/local/lib/python3.8/site-packages/bluetooth/bluez.py", line 291, in _gethcisock
    raise BluetoothError ("error accessing bluetooth device")
bluetooth.btcommon.BluetoothError: error accessing bluetooth device
```
```
2020-10-22 10:01:43 ERROR (Thread-6) [custom_components.mitemp_bt.sensor] HCIdump thread: OS error: [Errno 19] error while attempting to bind on interface 0: No such device
```
**Description of problem:**
Yesterday I updated the supervisor from version 246 to 249. After a restart the ble device tracker, switchbot and the xiaomi bluetooth temperature sensor are not working anymore. Home assistant cannot access the bluetooth device(see logs).
Is this a bug or is there a fix for that?

Best Regards
David

**Comment by ludeeus** [comment] 2020-10-22 12:53
Duplicate of <https://github.com/home-assistant/operating-system/issues/910> will be fixed in next OS release

**Closed by ludeeus** 2020-10-22 12:53 UTC
