### ISSUE TITLE
How long to update?

### ISSUE THREAD

**Issue by chpins** [home-assistant/supervisor#4024] opened 2022-11-24 17:14 UTC
### Describe the issue you are experiencing

Hello,
I ran the update 4 hours ago to version 2022.11.0
to the latest version 2022.11.2 and it is still installing.

Usually it takes 1 minute.

Is there a problem ?

How to see what is blocking?

Thanks.

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

### Steps to reproduce the issue

1- open menu Home Assistant Supervisor Update
2- click install

### Anything in the Supervisor logs that might be useful for us?

```txt
no error
```

### System Health information

empty

### Supervisor diagnostics

None

**Comment by ludeeus** [comment] 2022-11-24 17:15
Duplicate of https://github.com/home-assistant/supervisor/issues/4003

**Closed by ludeeus** 2022-11-24 17:15 UTC
Labels: bug
