### ISSUE TITLE
Update to Supervisor 2022.08.03 breaks RaspiMatic addon

### ISSUE THREAD

**Issue by ProfDrYoMan** [home-assistant/supervisor#3786] opened 2022-08-10 19:21 UTC
### Describe the issue you are experiencing

22-08-10 21:02:04 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon RaspberryMatic CCU is unhealthy, restarting...

RaspiMatic addon gets restarted every some minutes with this log entry.

### What operating system image do you use?

ova (for Virtual Machines)

### What version of Home Assistant Operating System is installed?

8.4

### Did you upgrade the Operating System.

No

### Steps to reproduce the issue

1. Update Supervisor from 2022.07.xx to 2022.08.03, no other updates done.

### Anything in the Supervisor logs that might be useful for us?

```txt
22-08-10 21:02:04 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon RaspberryMatic CCU is unhealthy, restarting...
```

### Anything in the Host logs that might be useful for us?

```txt
22-08-10 21:02:04 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon RaspberryMatic CCU is unhealthy, restarting...
```

**Comment by jens-maus** [comment] 2022-08-11 06:39
I am currently on vacation, so cannot reproduce it myself ATM. But as mentioned in the corresponding ticket in the RaspberryMatic project (see https://github.com/jens-maus/RaspberryMatic/issues/1907#issuecomment-1211233955) the healthcheck statement hasn‘t change for a while.

So the only ones that have yet reported that issue are @ProfDrYoMan and @sotatech. So something might have changed with supervisor 2022.07.1 and newer that seem to get this healthcheck statement into reporting false for these fellows. If this related to Supervisor itself or a dependency within the RaspberryMatic addon, I cannot check myself ATM, I am afraid.

**Comment by ProfDrYoMan** [comment] 2022-08-11 08:51
As info. I am 100% sure that my supervisor was updated from something 2022.07.xx with xx > 01 to 2022.08.03.
Maybe that helps.

I am running virtual in proxmox and stable since >> 6 months.

**Comment by mdegat01** [comment] 2022-08-11 21:28
@jens-maus In 2022.08.3 Supervisor now actually uses `HEALTHCHECK` statements in watchdog. If Docker tells us that a container for an addon is unhealthy then supervisor restarts it. Previously any `HEALTHCHECK` statements in addons were essentially ignored. Watchdog didn't look at the health status of containers and we never presented that information to users.

So I guess my question would be why is the healthcheck marking the containers as unhealthy? If the result is intended to be ignored then it should be removed I would think.

**Comment by agners** [comment] 2022-08-12 08:20
So it seems this is a add-on issue which just cropped up with the new Supervisor issue. I'll close this ticket then as the problem is being tracked in https://github.com/jens-maus/RaspberryMatic/issues/1907. Thanks for your help to get the bottom of this!

**Closed by agners** 2022-08-12 08:20 UTC
Labels: bug
