### ISSUE TITLE
Notification header "Available space is less than 1GB!" is inconsistent with body text

### ISSUE THREAD

**Issue by bessarabov** [home-assistant/supervisor#2191] opened 2020-10-29 09:41 UTC
## The problem

I've just received the notification that I'm running low on disk space.
Here is the screenshot:

![Screenshot 2020-10-29 at 12 27 49](https://user-images.githubusercontent.com/47263/97550824-35740a80-19e3-11eb-8fcd-e49b70950ebb.png)

This is super great that Home Assistant shows such notification, but there is a small inconstancy with notification header and the body.

In the header it is stated that `Available space is less than 1GB!`, but in the body there is text: `Available space is 1.5GB` ( 1 is not less that 1.5)

## Environment

- Home Assistant Core release with the issue: 0.117.0
- Last working Home Assistant Core release (if known):  ???
- Operating environment (OS/Container/Supervised/Core): Home Assistant Supervised
- Integration causing this issue: ???
- Link to integration documentation on our website: ??? 

## Problem-relevant `configuration.yaml`

As far as I understand the content of yaml config does not matter for this issue.

```yaml

```

## Traceback/Error logs

I have not  seen any logs about this matter.
```txt

```

**Comment by bessarabov** [comment] 2020-10-29 17:19
There is nothing in the log about this matter. (here is the log from the page `/hassio/system`, log provider: `supervisor` 
https://gist.github.com/bessarabov/8d4592de4e519652c2476224e7aa53a0 )


![Screenshot 2020-10-29 at 20 18 43](https://user-images.githubusercontent.com/47263/97608860-f5814780-1a23-11eb-8a76-6f9e7858105e.png)

**Comment by ludeeus** [comment] 2020-10-29 17:20
There actually is ;)
The error you see there would cause this.
It has been fixed in the current codebase and will be a part of the next release :+1: 

PR that fixed it: https://github.com/home-assistant/supervisor/pull/2180

**Closed by ludeeus** 2020-10-29 17:20 UTC

**Comment by bessarabov** [comment] 2020-10-29 17:37
Thank you!

I'm really surprised that the https://github.com/home-assistant/supervisor/pull/2180 should fix my issue.
(Just to be clear — the notification is correct — the system is low on disk space, the only thing that looks like a bug is the inconsistency with the numbers in the text)

I'll check this notification again after I'll update to the version with this fix.

**Comment by ludeeus** [comment] 2020-10-29 17:40
The check is never run, so the return statement is never called.
At the end of that function is what makes this show.

It should not show until you are below 1GB and you are at 1.5

**Comment by bessarabov** [comment] 2020-10-29 17:47
Thank you for the explanation!

**Comment by HA-TB303** [comment] 2020-11-05 10:48
The last update (0.117.4) is actually the cause for this issue on my system.

![image](https://user-images.githubusercontent.com/9609805/98231516-cbb4ad00-1f5c-11eb-9037-4f86c0c0d97f.png)

**Comment by Mr-Groch** [comment] 2020-11-19 07:39
I'm also having this issue on 0.118:

![image](https://user-images.githubusercontent.com/20594810/99635707-a6d33600-2a42-11eb-8304-1e3a86a97b3f.png)

**Comment by jackccomp** [comment] 2020-12-02 00:29
Same, got the issue on 0.118.4, I was low on memory and cleared space but notification keeps popping up.

**Comment by filipvdb-docker** [comment] 2020-12-02 11:23
> Same, got the issue on 0.118.4, I was low on memory and cleared space but notification keeps popping up.

Same here. I did use the disk space to recover a acronis backup for a machine because this network drive was immediatly discovered and was less on time to do otherwise. Since then I got every x hours the notification but still 24Gb available.
