### ISSUE TITLE
Translation Error: The intl string context variable "naam" was not provided to the string "Herstart {naam}"

### ISSUE THREAD

**Issue by canedje** [home-assistant/supervisor#2682] opened 2021-03-04 20:35 UTC
### Describe the issue you are experiencing

I do recieve an error in my supervisor system chapter

### What is the used version of the Supervisor?

supervisor-2021.03.4

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

Home Assistant OS 5.12

### What version of Home Assistant Core is installed?

core-2021.3.0

### Steps to reproduce the issue

1. it is there always
2.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
# Put your logs below this line

```

![image](https://user-images.githubusercontent.com/23150947/110026486-fc50fb80-7d30-11eb-9a08-393f6f70292e.png)

## System Health

version | core-2021.3.0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.7
os_name | Linux
os_version | 5.4.99
arch | x86_64
timezone | Europe/Amsterdam

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4847
Installed Version | 1.11.3
Stage | running
Available Repositories | 749
Installed Repositories | 22

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Hass.io</summary>

host_os | Home Assistant OS 5.12
-- | --
update_channel | stable
supervisor_version | supervisor-2021.03.4
docker_version | 19.03.13
disk_total | 29.8 GB
disk_used | 6.3 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.2.0), Samba share (9.3.1), Node-RED (8.1.2), Terminal & SSH (9.0.2), Duck DNS (1.12.5), NGINX Home Assistant SSL proxy (3.0.1), Z-Wave JS (0.1.10)

</details>

<details><summary>Lovelace</summary>

dashboards | 3
-- | --
resources | 9
views | 90
mode | yaml

</details>

**Comment by ludeeus** [comment] 2021-03-04 21:04
Duplicate of https://github.com/home-assistant/frontend/issues/8550

**Closed by ludeeus** 2021-03-04 21:04 UTC
Labels: bug
