### ISSUE TITLE
Error updating ESPHome: Can't install ghcr.io/esphome/esphome-hassio:2023.4.3

### ISSUE THREAD

**Issue by cptskippy** [home-assistant/supervisor#4402] opened 2023-06-23 20:56 UTC
### Describe the issue you are experiencing

Starting after the ESPHome 2023.3.2 release, updating of the Add-On stopped working.  When I attempted to upgrade the ESPHome Add-on after ESPHome 2023.4.0 was released, it started returning an error.  I am able to uninstall/reinstall the Add-on but updating always fails.

The error in the Hosts log leads me to believe it's attempting to download a build for the wrong platform (ARMv6) and failing. I am at a loss on how to troubleshoot this further.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1. Receive notification of Update available for ESPHome
![image](https://github.com/home-assistant/supervisor/assets/5817292/1a441594-9929-4e9a-a941-d8f176a9cbcc)

2. Open Modal detailing update and click INSTALL
![image](https://github.com/home-assistant/supervisor/assets/5817292/257a6914-380f-4511-a565-622774d14d4d)

3. Receive error briefly at bottom of screen.
![image](https://github.com/home-assistant/supervisor/assets/5817292/44b16475-a060-4beb-b1da-059ac01e0742)

### Anything in the Supervisor logs that might be useful for us?

```txt
23-05-03 14:34:05 INFO (SyncWorker_2) [supervisor.docker.interface] Cleanup images: ['ghcr.io/home-assistant/raspberrypi2-homeassistant:2023.4.6']
23-05-03 14:34:50 INFO (MainThread) [supervisor.backups.manager] Creating new partial backup with slug 7efd0127
23-05-03 14:34:50 INFO (MainThread) [supervisor.backups.manager] Backing up 7efd0127 store Add-ons
23-05-03 14:34:50 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on 5c53de3b_esphome
23-05-03 14:34:50 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon 5c53de3b_esphome
23-05-03 14:34:51 INFO (MainThread) [supervisor.backups.manager] Creating partial backup with slug 7efd0127 completed
23-05-03 14:34:51 INFO (SyncWorker_0) [supervisor.docker.addon] Updating image ghcr.io/esphome/esphome-hassio:2023.4.2 to ghcr.io/esphome/esphome-hassio:2023.4.3
23-05-03 14:34:51 INFO (SyncWorker_0) [supervisor.docker.interface] Downloading docker image ghcr.io/esphome/esphome-hassio with tag 2023.4.3.
23-05-03 14:34:53 ERROR (SyncWorker_0) [supervisor.docker.interface] Can't install ghcr.io/esphome/esphome-hassio:2023.4.3: 404 Client Error for http+docker://localhost/v1.42/images/ghcr.io/esphome/esphome-hassio:2023.4.3/json: Not Found ("No such image: ghcr.io/esphome/esphome-hassio:2023.4.3")

```

## System Information

version | core-2023.6.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.4
os_name | Linux
os_version | 6.1.21-v7
arch | armv7l
timezone | America/Los_Angeles
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.32.1
Stage | running
Available Repositories | 1276
Downloaded Repositories | 6

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | February 2, 2024 at 4:00 PM
relayer_connected | true
relayer_region | us-east-1
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | false
remote_server | us-east-1-8.ui.nabu.casa
certificate_status | ready
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.3
-- | --
update_channel | stable
supervisor_version | supervisor-2023.06.2
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 28.6 GB
disk_used | 9.0 GB
healthy | true
supported | true
board | rpi2
supervisor_api | ok
version_api | ok
installed_addons | Mosquitto broker (6.2.1), Z-Wave JS UI (1.13.4), File editor (5.6.0), Samba share (10.0.2), ESPHome (2023.6.0), Advanced SSH & Web Terminal (15.0.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 4
views | 14
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | June 15, 2023 at 3:56 PM
-- | --
current_recorder_run | June 22, 2023 at 10:13 AM
estimated_db_size | 442.69 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Supervisor diagnostics

[config_entry-hassio-d50e495cb6f0125fed2e5c63db2106b6.json.txt](https://github.com/home-assistant/supervisor/files/11852940/config_entry-hassio-d50e495cb6f0125fed2e5c63db2106b6.json.txt)

### Additional information

**Home Assistant Core logs:**

```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/hassio/update.py:169
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 2:34:54 PM (2 occurrences)
Last logged: 2:35:44 PM

[1704455400] Error updating ESPHome: Can't install ghcr.io/esphome/esphome-hassio:2023.4.3: 404 Client Error for http+docker://localhost/v1.42/images/ghcr.io/esphome/esphome-hassio:2023.4.3/json: Not Found ("No such image: ghcr.io/esphome/esphome-hassio:2023.4.3")
[1521728168] Error updating ESPHome: Can't install ghcr.io/esphome/esphome-hassio:2023.4.3: 404 Client Error for http+docker://localhost/v1.42/images/ghcr.io/esphome/esphome-hassio:2023.4.3/json: Not Found ("No such image: ghcr.io/esphome/esphome-hassio:2023.4.3")
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 167, in async_install
    await async_update_addon(self.hass, slug=self._addon_slug, backup=backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 52, in _wrapper
    raise HassioAPIError(data["message"])
homeassistant.components.hassio.handler.HassioAPIError: Can't install ghcr.io/esphome/esphome-hassio:2023.4.3: 404 Client Error for http+docker://localhost/v1.42/images/ghcr.io/esphome/esphome-hassio:2023.4.3/json: Not Found ("No such image: ghcr.io/esphome/esphome-hassio:2023.4.3")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 199, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1849, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1889, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 226, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 798, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 981, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 838, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 156, in async_install
    await entity.async_install_with_progress(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 417, in async_install_with_progress
    await self.async_install(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 169, in async_install
    raise HomeAssistantError(f"Error updating {self.title}: {err}") from err
homeassistant.exceptions.HomeAssistantError: Error updating ESPHome: Can't install ghcr.io/esphome/esphome-hassio:2023.4.3: 404 Client Error for http+docker://localhost/v1.42/images/ghcr.io/esphome/esphome-hassio:2023.4.3/json: Not Found ("No such image: ghcr.io/esphome/esphome-hassio:2023.4.3")

```
**Host Logs:**

```
May 03 21:34:53 homeassistant dockerd[473]: time="2023-05-03T21:34:53.828932024Z" level=info msg="Attempting next endpoint for pull after error: no matching manifest for linux/arm/v6 in the manifest list entries"
```

Previously I had an [issue opened in core](https://github.com/home-assistant/core/issues/92433).

**Comment by peterhanssens** [comment] 2023-06-24 06:40
Other treath about de same issue (unsolved): https://community.home-assistant.io/t/unable-to-update-to-latest-esphome/541777

**Comment by pvizeli** [comment] 2023-06-27 08:44
`ha su repair` maybe fix the issue

**Comment by cptskippy** [comment] 2023-06-28 22:40
> `ha su repair` maybe fix the issue

I tried that just now before attempting to upgrade to v2023.6.3 and it did not work.

**Comment by peterhanssens** [comment] 2023-07-05 12:15
Again upgrade not working: Can't install ghcr.io/esphome/esphome-hassio:2023.6.4: 404 Client Error for http+docker://localhost/v1.42/images/ghcr.io/esphome/esphome-hassio:2023.6.4/json: Not Found ("No such image: ghcr.io/esphome/esphome-hassio:2023.6.4")

But uninstall en install again works to upgrade (Raspberry Pi 2), all other upgrades working fine.

**Comment by Floppy** [comment] 2023-07-29 11:47
Still happening for 2023.7.0:

`Can't install ghcr.io/esphome/esphome-hassio:2023.7.0: 404 Client Error for http+docker://localhost/v1.42/images/ghcr.io/esphome/esphome-hassio:2023.7.0/json: Not Found ("No such image: ghcr.io/esphome/esphome-hassio:2023.7.0")`

**Comment by peterhanssens** [comment] 2023-08-19 15:47
Still unsolved when upgrading to 2023.8.1:

Can't install ghcr.io/esphome/esphome-hassio:2023.8.1: 404 Client Error for http+docker://localhost/v1.42/images/ghcr.io/esphome/esphome-hassio:2023.8.1/json: Not Found ("No such image: ghcr.io/esphome/esphome-hassio:2023.8.1")

Raspbeery Pi 2, all other upgrades working fine. Work around: delete add-on Esphome en install it again (no setting are lost).

**Comment by peterhanssens** [comment] 2023-09-09 21:05
Still unsolved, same error when upgrading to 2023.8.2 en now also 2023.8.3. Work around: delete add-on Esphome en install it again (no setting are lost). All other upgrades work fine. Not a big problem, but just to keep this bug alive.

**Comment by 007hacky007** [comment] 2023-09-09 21:09
> Work around: delete add-on Esphome en install it again 

I'm actually doing 

1. `docker pull ghcr.io/esphome/esphome-hassio:2023.5.5` (replace with latest version number visible in the home assistant UI)
2. update from the home assistant UI then proceeds fine

But yep, the issue is still there and it is quite annoying. Someone please fix it. I believe the fix is rather easy. Someone just broke `armv7l` arch.

**Comment by 007hacky007** [comment] 2023-10-10 02:27
This has not been fixed still. Having the same issue upgrading from 2023.8.2 to 2023.9.3. 

So I’m replying with 👎 so you don’t close this unresolved issue.

**Comment by peterhanssens** [comment] 2023-10-25 07:50
Still not resolved after almost 8 months. Same error when updating to version esphome-hassio:2023.10.3 (homeassistant: core-2023.10.5, supervisor-2023.10.0). All other updates work fine. Problem is already 8 months old, was first mentioned one 1 march 2022 [here](https://community.home-assistant.io/t/unable-to-update-to-latest-esphome/541777) and then [here](https://github.com/home-assistant/core/issues/92433).

**Comment by buteomont** [comment] 2023-11-13 02:51
I am getting the same error except I can't update anything, including supervisor and core.

**Comment by buteomont** [comment] 2023-11-17 14:41
Setting the DNS in Settings -> System-> Network to 8.8.8.8 fixed it for me.

**Comment by Buggykiter** [comment] 2023-11-17 16:35
8.8.8.8 did not fix it in my configuration, still the same error

 
 

Gesendet: Freitag, 17. November 2023 um 15:41 Uhr
Von: "David Powell" ***@***.***>
An: "home-assistant/supervisor" ***@***.***>
Cc: "Buggykiter" ***@***.***>, "Comment" ***@***.***>
Betreff: Re: [home-assistant/supervisor] Error updating ESPHome: Can't install ghcr.io/esphome/esphome-hassio:2023.4.3 (Issue #4402)


 

Setting the DNS in Settings -> System-> Network to 8.8.8.8 fixed it for me.

**Comment by peterhanssens** [comment] 2023-11-17 17:09
The problem of "buteomont" was different. He couldn't do any updates, apparently it was a DNS problem for him. Our problem is different. All other updates work. A non-existent update package is called when updating esphome. I think our error only occurs with ARMv7l (like with raspberry pi2).

**Comment by Buggykiter** [comment] 2023-11-17 17:29
@ peterhanssens

In my case homeassistant is running on an old HP notebook with Windows 10 in Oracle VM Virtualbox. Everything is up to date, Home assistant OS 11.1 and Home assistant Core 2023.11.1. Other updates worked fine, but ESPHome 11.0 and 11.1 can´t be updated.

 
 

Gesendet: Freitag, 17. November 2023 um 18:09 Uhr
Von: "peterhanssens" ***@***.***>
An: "home-assistant/supervisor" ***@***.***>
Cc: "Buggykiter" ***@***.***>, "Comment" ***@***.***>
Betreff: Re: [home-assistant/supervisor] Error updating ESPHome: Can't install ghcr.io/esphome/esphome-hassio:2023.4.3 (Issue #4402)


 

The problem of "buteomont" was different. He couldn't do any updates, apparently it was a DNS problem for him. Our problem is different. All other updates work. A non-existent update package is called when updating esphome. I think our error only occurs with ARMv7l (like with raspberry pi2).

**Comment by peterhanssens** [comment] 2023-11-18 12:01
@Buggykiter Your computer is running Windows 10, but the VM where Home-Assistant is installed will contain a Linux version. You seem to have the same problem: all updates work except Esphome. In order to update, I remove the Esphome add-on and then add it back until someone fixes the bug. All settings are saved. It can also be done via a pull command (but for this you must first install a terminal add-on).

**Comment by 007hacky007** [comment] 2023-12-18 12:07
Oh my. Not again. This issue is still there. Bad bot! Bad Github action. 

Bad maintainers - for ignoring issue which is affecting all armv6 users for so long...

**Comment by Buggykiter** [comment] 2023-12-18 12:53
Problem still exists with ESPHome 2023.11.6

**Comment by agners** [comment] 2023-12-20 19:06
So this only happens with ESPHome? Glancing at the ESPHome description file at https://github.com/esphome/home-assistant-addon/blob/2023.11.6/esphome/config.yaml it seem that a single (Docker multi-platform) image is used (there is no `{arch}` variable in `image: ghcr.io/esphome/esphome-hassio`). That is not the case with the Core add-on, I am guessing that is somehow related :thinking: 

I've just tried that on a `rpi3` HAOS image (32-bit), and I also can't reproduce it. Since this seems to appear mostly on Raspberry Pi 2, it must be something which is limited to it. Raspberry Pi 2 (at least some revisions) use Cortex-A7. I wonder if that makes some architecture auto-detection to trigger different results :thinking: 

Has someone access to a shell with Docker? If so, can you run `docker info`? I wonder mostly about the architecture it reports (on my Raspberry 3 32-bit it reports `Architecture: armv7l`).

The full output:

<details>

```
# docker info
Client:
 Version:    24.0.7
 Context:    default
 Debug Mode: false

Server:
 Containers: 14
  Running: 13
  Paused: 0
  Stopped: 1
 Images: 18
 Server Version: 24.0.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: journald
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 
 runc version: 
 init version: 
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.1.58-haos-raspi
 Operating System: Home Assistant OS 11.2
 OSType: linux
 Architecture: armv7l
 CPUs: 4
 Total Memory: 921.3MiB
 Name: ha-shelf1-rpi3
 ID: SMBW:DZIE:PT6N:KCLY:JDJT:FBMV:7O2P:TMKF:SINW:VSD7:M5BW:MLXA
 Docker Root Dir: /mnt/data/docker
 Debug Mode: false
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

</details>

**Comment by asboldyrev** [comment] 2023-12-21 06:02
> So this only happens with ESPHome? Glancing at the ESPHome description file at https://github.com/esphome/home-assistant-addon/blob/2023.11.6/esphome/config.yaml it seem that a single (Docker multi-platform) image is used (there is no `{arch}` variable in `image: ghcr.io/esphome/esphome-hassio`). That is not the case with the Core add-on, I am guessing that is somehow related 🤔
> 
> I've just tried that on a `rpi3` HAOS image (32-bit), and I also can't reproduce it. Since this seems to appear mostly on Raspberry Pi 2, it must be something which is limited to it. Raspberry Pi 2 (at least some revisions) use Cortex-A7. I wonder if that makes some architecture auto-detection to trigger different results 🤔
> 
> Has someone access to a shell with Docker? If so, can you run `docker info`? I wonder mostly about the architecture it reports (on my Raspberry 3 32-bit it reports `Architecture: armv7l`).
> 
> The full output:

I'm not sure about the version of my Raspberry Pi (HA says it's a Raspberry Pi 2), but I have the same result:
<details><summary>Details</summary>
<code>
Client:
 Version:    24.0.7
 Context:    default
 Debug Mode: false

Server:
 Containers: 13
  Running: 13
  Paused: 0
  Stopped: 0
 Images: 14
 Server Version: 24.0.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: journald
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 
 runc version: 
 init version: 
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.1.58-haos-raspi
 Operating System: Home Assistant OS 11.2
 OSType: linux
 Architecture: armv7l
 CPUs: 4
 Total Memory: 921.3MiB
 Name: homeassistant
 ID: IYCQ:ZZFL:VVED:J5L2:TSN6:ZYN6:VN6D:26TU:G3MZ:7DOE:BS27:U7K3
 Docker Root Dir: /mnt/data/docker
 Debug Mode: false
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
</code>
</details> 

And I also can't update ESPHome

**Comment by agners** [comment] 2023-12-21 07:55
@asboldyrev I don't see any reason why Docker would try to pull a `linux/arm/v6` image here :cry: 

Diving into source code, it might be that we fall into some hacked up detection here: https://github.com/containerd/containerd/blob/main/platforms/cpuinfo_linux.go#L133-L140

What is the output of `cat /proc/cpuinfo`?

In any case, I wonder why installation works here, but update not. I'll check the difference between the codepaths.

**Comment by asboldyrev** [comment] 2023-12-21 08:42
> @asboldyrev from that output, I don't see any reason why Docker would try to pull a `linux/arm/v6` image 😢
> 
> Diving into source code, it might be that we fall into some hacked up CPU variant detection here: https://github.com/containerd/containerd/blob/main/platforms/cpuinfo_linux.go#L133-L140
> 
> What is the output of `cat /proc/cpuinfo`?
> 
> In any case, I wonder why installation works here, but update not. I'll check the difference between the codepaths.

`/proc/cpuinfo` output:
```
processor	: 0
model name	: ARMv7 Processor rev 5 (v7l)
BogoMIPS	: 57.60
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xc07
CPU revision	: 5

processor	: 1
model name	: ARMv7 Processor rev 5 (v7l)
BogoMIPS	: 57.60
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xc07
CPU revision	: 5

processor	: 2
model name	: ARMv7 Processor rev 5 (v7l)
BogoMIPS	: 57.60
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xc07
CPU revision	: 5

processor	: 3
model name	: ARMv7 Processor rev 5 (v7l)
BogoMIPS	: 57.60
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xc07
CPU revision	: 5

Hardware	: BCM2835
Revision	: a01041
Serial		: 0000000053ca4e7b
Model		: Raspberry Pi 2 Model B Rev 1.1
```

**Comment by asboldyrev** [comment] 2023-12-21 09:12
> Still doesn't make sense to me. What is `uname -a` showing?

```
Linux a0d7b954-ssh 6.1.58-haos-raspi #1 SMP PREEMPT Mon Dec  4 15:44:34 UTC 2023 armv7l Linux
```

**Comment by agners** [comment] 2023-12-21 10:02
Ok, this is definitely not Docker default issue.

It seems the Supervisor is falling back to the Supervisor architecture itself: https://github.com/home-assistant/supervisor/blob/2023.12.0/supervisor/docker/interface.py#L231

However, for Raspberry Pi 2 this *should* be armv7. But it seems that the OS is using the Supervisor image is declared as `armhf` (see https://github.com/home-assistant/operating-system/blob/11.2/buildroot-external/board/raspberrypi/rpi2/meta#L11), which is translated to `linux/arm/v6` in Docker multi-arch.

So there are two issue here:
1. The Supervior should always pass the architecture from the add-on, even on update (the architecture is determined to be the best match for the current platform according to compatibility, this works correctly on installation). This will be addressed with https://github.com/home-assistant/supervisor/pull/4786
2. The Home Assistant Operating System should install the `armv7` variant of the Supervisor.

As for 2.) since we declare compatibility for `armv7` and `armhf` [for Raspberry Pi 2 in Supervisor](https://github.com/home-assistant/supervisor/blob/2023.12.0/supervisor/data/arch.json#L3) this change will still allow to install the same images. The only difference will be that locally built images will default to armv7 from then on-wards.

**Comment by Buggykiter** [comment] 2023-12-21 11:46
Hi, you discussing it is related to raspberry Pi2 or arm. This is not the case. I am running Home Assistant on a HP EliteBook 8440p
with Intel Core i5-520M. Installed is Windows 10 and Oracle VM Virtual Box 7.0 with haos_ova-11.1.vdi.
I realized the problem first time with ESPHome 11.0 update. Later also with an cloudflared 4.2.10. update. But the cloudflare problem disappeared somehow.
Apart from this my Home Assistant installation is running fine.

**Comment by Buggykiter** [comment] 2023-12-21 14:29
@agners 
Today I received ESPhome 2023.12.0 update and out of the sudden this worked fine. Seems, the problem is gone without removing the add-on. So, whoever contributerd to 12.0, thanks a lot

**Comment by 007hacky007** [comment] 2023-12-21 14:32
Still broken on raspberry pi 2 though which this thread as about.

čt 21. 12. 2023 v 15:30 odesílatel Buggykiter ***@***.***>
napsal:

**Closed** 2023-12-21 21:52 UTC
Labels: bug

**Comment by ssummer** [comment] 2024-01-15 21:00
This is (in ESPHome 2023.12.6 update) now (finally) working for me on raspberry pi 2.

**Comment by 007hacky007** [comment] 2024-01-15 21:07
Update from 2023.12.3 to 2023.12.6 on HA Core version 2024.1.2 still does not work for me. Still the same error. 

In which version exactly it got patched and should work?

**Comment by ssummer** [comment] 2024-01-15 21:30
FYI if it matters, I was fully up to date before the ESPHome 2023.12.6 update (ie I upgraded from 2023.12.5):
Core: 2024.1.3
Supervisor: 2023.12.0
Operating System: 11.4

**Comment by peterhanssens** [comment] 2024-01-16 06:50
> FYI if it matters, I was fully up to date before the ESPHome 2023.12.6 update (ie I upgraded from 2023.12.5): Core: 2024.1.3 Supervisor: 2023.12.0 Operating System: 11.4

I can confirm the latest esphome update works fine finally. Thanks @angers and @mdegat01.

**Comment by agners** [comment] 2024-01-16 09:37
@007hacky007 the fix is in Supervisor 2023.12.1 which is at this point in the beta channel.

@peterhanssens I am assuming you have the beta channel enabled then?

**Comment by agners** [comment] 2024-01-16 09:41
Oh I actually forgot, there was also a fix in HAOS which fixes the same problem (https://github.com/home-assistant/operating-system/pull/3012). So essentially, if either of this is true, the ESPHome update should work again on Raspberry Pi 2:

- Supervisor 2023.12.1 (on beta channnel)
- Home Assistant OS 11.3 or newer

**Comment by 007hacky007** [comment] 2024-01-16 15:23
@agners thank you! 

After updating HAOS from 11.2 to 11.4, my update from ESPHome 2023.12.3 to 2023.12.6 proceeded successfully right from the HA UI. 

Seems like the issue is finally fixed! 🎉
