### ISSUE TITLE
Strange errors

### ISSUE THREAD

**Issue by Toolhead** [home-assistant/supervisor#2920] opened 2021-05-29 18:29 UTC
### Describe the issue you are experiencing

Not experiencing problems, but recurring error in the log, see copy down below.

21-05-29 18:24:02 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-712225' coro=<Scheduler._run_task.<locals>._wrap_task() done, defined at /usr/src/supervisor/supervisor/misc/scheduler.py:58> exception=TypeError('an integer is required (got type str)')>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/misc/scheduler.py", line 62, in _wrap_task
    await task.coro_callback()
  File "/usr/src/supervisor/supervisor/misc/tasks.py", line 416, in _watchdog_addon_application
    if addon.in_progress or await addon.watchdog_application():
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 479, in watchdog_application
    return await self.sys_run_in_executor(check_port, self.ip_address, port)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/supervisor/supervisor/utils/__init__.py", line 43, in check_port
    result = sock.connect_ex((str(address), port))
TypeError: an integer is required (got type str)

### What is the used version of the Supervisor?

2021.04.3

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

### What is the version of your installed operating system?

5.13

### What version of Home Assistant Core is installed?

2121.5.5

### Steps to reproduce the issue

1.
2.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
21-05-29 18:24:02 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-712225' coro=<Scheduler._run_task.<locals>._wrap_task() done, defined at /usr/src/supervisor/supervisor/misc/scheduler.py:58> exception=TypeError('an integer is required (got type str)')>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/misc/scheduler.py", line 62, in _wrap_task
    await task.coro_callback()
  File "/usr/src/supervisor/supervisor/misc/tasks.py", line 416, in _watchdog_addon_application
    if addon.in_progress or await addon.watchdog_application():
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 479, in watchdog_application
    return await self.sys_run_in_executor(check_port, self.ip_address, port)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/supervisor/supervisor/utils/__init__.py", line 43, in check_port
    result = sock.connect_ex((str(address), port))
TypeError: an integer is required (got type str)
```

**Comment by martymarty004** [comment] 2021-05-30 13:55
Duplicate of #2906 
Fixed in #2903 ([2021.05.1](https://github.com/home-assistant/supervisor/releases/tag/2021.05.1))

**Closed** 2021-05-30 13:58 UTC
Labels: bug
