### ISSUE TITLE
Unable to load the panel source: /api/hassio/app/entrypoint.js

### ISSUE THREAD

**Issue by SalkinDK** [home-assistant/supervisor#1442] opened 2020-01-20 13:39 UTC
**Home Assistant release with the issue:**
 

version | 0.104.2
-- | --

**Operating environment (HassOS/Generic):**
 HassOS Proxmox VM

**Supervisor logs:**

`hassio su logs
20-01-20 10:26:11 INFO (MainThread) [hassio.updater] Fetch update data from https://version.home-assistant.io/stable.json
20-01-20 10:28:19 INFO (MainThread) [hassio.auth] Auth request from core_mosquitto for mqtt
20-01-20 10:28:19 INFO (MainThread) [hassio.homeassistant] Updated Home Assistant API token
20-01-20 10:28:19 INFO (MainThread) [hassio.auth] Success login from mqtt
20-01-20 10:45:04 INFO (MainThread) [hassio.auth] Auth request from core_mosquitto for mqtt
20-01-20 10:45:04 INFO (MainThread) [hassio.auth] Success login from mqtt
20-01-20 10:50:40 INFO (MainThread) [hassio.auth] Auth request from core_mosquitto for mqtt
20-01-20 10:50:41 INFO (MainThread) [hassio.auth] Success login from mqtt
20-01-20 11:00:00 INFO (MainThread) [hassio.homeassistant] Updated Home Assistant API token
20-01-20 11:25:00 INFO (MainThread) [hassio.auth] Auth request from core_mosquitto for mqtt
20-01-20 11:25:00 INFO (MainThread) [hassio.auth] Success login from mqtt
20-01-20 11:39:31 INFO (MainThread) [hassio.host.info] Update local host information
20-01-20 11:39:31 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/hostname1
20-01-20 11:39:31 INFO (MainThread) [hassio.host.services] Update service information
20-01-20 11:39:31 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.systemd1.Manager.ListUnits on /org/freedesktop/systemd1
20-01-20 11:39:31 INFO (MainThread) [hassio.host.network] Update local network DNS information
20-01-20 11:39:31 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/NetworkManager/DnsManager
20-01-20 12:21:40 INFO (MainThread) [hassio.auth] Auth request from core_mosquitto for mqtt
20-01-20 12:21:40 INFO (MainThread) [hassio.homeassistant] Updated Home Assistant API token
20-01-20 12:21:40 INFO (MainThread) [hassio.auth] Success login from mqtt
20-01-20 12:26:11 INFO (MainThread) [hassio.updater] Fetch update data from https://version.home-assistant.io/stable.json
20-01-20 12:26:11 INFO (MainThread) [hassio.store.git] Update add-on https://github.com/hassio-addons/repository repository
20-01-20 12:26:11 INFO (MainThread) [hassio.store.git] Update add-on https://github.com/danielwelch/hassio-zigbee2mqtt repository
20-01-20 12:26:11 INFO (MainThread) [hassio.store.git] Update add-on https://github.com/home-assistant/hassio-addons repository
20-01-20 12:26:11 INFO (MainThread) [hassio.store.git] Update add-on https://github.com/yllibed/hassio repository
20-01-20 12:26:11 INFO (MainThread) [hassio.store.git] Update add-on https://github.com/esphome/hassio repository
20-01-20 12:26:11 INFO (MainThread) [hassio.store.git] Update add-on https://github.com/danielwelch/hassio-addons repository
20-01-20 12:26:12 INFO (MainThread) [hassio.store] Load add-ons from store: 71 all - 0 new - 0 remove
20-01-20 13:18:20 INFO (MainThread) [hassio.auth] Auth request from core_mosquitto for mqtt
20-01-20 13:18:20 INFO (MainThread) [hassio.homeassistant] Updated Home Assistant API token
20-01-20 13:18:21 INFO (MainThread) [hassio.auth] Success login from mqtt
20-01-20 13:33:59 INFO (MainThread) [hassio.auth] Auth request from a0d7b954_nodered for Niklas
20-01-20 13:34:00 INFO (MainThread) [hassio.auth] Success login from Niklas
20-01-20 13:37:00 INFO (MainThread) [hassio.api.security] /supervisor/logs access from core_ssh
`

Seeing this in the Homeassistant logs

`Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/real_ip.py", line 39, in real_ip_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 135, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 123, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/hassio/http.py", line 56, in _handle
    return await self._command_proxy(path, request)
  File "/usr/src/homeassistant/homeassistant/components/hassio/http.py", line 81, in _command_proxy
    timeout=read_timeout,
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 357, in _request
    raise RuntimeError('Session is closed')
RuntimeError: Session is closed`

**Description of problem:**
After some time i cant access the hass.io tab. i cant take snapshots from node-red etc.
Has been running fine until update of hassos and supervisor.
Tried all kinds of browser clearing the browsers etc.
Does the same on the ios app

Works again for some time if i reboot

<img width="371" alt="Skærmbillede 2020-01-19 kl  20 00 58" src="https://user-images.githubusercontent.com/16081029/72730865-448f7780-3b8a-11ea-8d94-0a084bde3363.png">

Getting this error in node-red.
`"Call-service API error. Error Message: Session is closed"`

**Comment by pvizeli** [comment] 2020-01-28 09:40
The issue is, that one of your integration/component close the core connection pool.

**Comment by frenck** [comment] 2020-01-28 10:07
Could you provide a list of integrations you are using?

**Comment by SalkinDK** [comment] 2020-01-28 12:05
@pvizeli ok, any way i can see what integration/component i causing it?
I ssh into my instance to look around and found out the keyboard language was wrong, i tried setting it and rebooted. After that it has been stable for a couple of days. maybe it is just a coincidence

@frenck is there a place to easily find all integrations and components?
In integrations i have the following loaded some of them more than once.
- apple tv (the beta one from postlund)
- ssl_certificate_expiry
- ESPHome
- HACS
- HomeKit Accessory
- Mobile App
- MQTT
- Sonos
- Transmission

**Comment by pvizeli** [comment] 2020-01-29 11:18
@SalkinDK there is a component they closed the web session what ends up in these issues.

**Comment by raresserban** [comment] 2020-03-06 08:44
I have the same issue, running Home Assistant with HassIO on Raspberry PI. Everything was fine for several releases, then I upgraded from 0.106.2 to 0.106.4 and now that 0.106.5 is out, I noticed that I can no longer update HA without having access to the Supervisor tab...
Is there any way I can update my instance manually, maybe directly calling the API endpoint that the button from the UI called?
Or do I need to get the SSH addon and run some commands?I really don't want to tinker with the installation too much, it worked fine until now and I didn't do anything custom with my installation.

**Comment by Falsen** [comment] 2020-03-08 13:29
@raresserban I have the same setup and the same just happened with me. No idea how to fix this. I have no SSH access...

**Comment by phunkybeam** [comment] 2020-03-08 18:35
I have the same problem and also no SSH access. I have the following integrations running:

- alarm_control_panel
- alexa_media
- api
- auth
- automation
- binary_sensor
- cast
- climate
- cloud
- config
- coronavirus
- default_config
- device_automation
- device_tracker
- fritzbox
- fritzbox_tools
- frontend
- group
- hacs
- hassio
- history
- homeassistant
- http
- input_boolean
- input_number
- kodi
- light
- logbook
- logger
- lovelace
- map
- media_player
- met
- mobile_app
- mqtt
- notify
- onboarding
- panel_custom
- panel_iframe
- persistent_notification
- person
- recorder
- samsungtv
- scene
- script
- search
- sensor
- shelly
- speedtestdotnet
- ssdp
- stream
- stt
- sun
- switch
- system_health
- system_log
- tts
- tuya
- updater
- upnp
- weather
- webhook
- websocket_api
- wunderlist
- zeroconf
- zone

**Comment by phunkybeam** [comment] 2020-03-08 18:48
All good again, it was probably HACS after an update and a HardReset it runs again.

**Comment by raresserban** [comment] 2020-03-08 19:26
@Falsen So I wanted to re-install mine and then revert to a backup, so I shut down my Pi and just as I was about to etch the image on the sd card, I remembered I also need the secrets file, so I fired the Pi again and after a longish startup the problem fixed itself.

**Comment by frenck** [comment] 2020-03-09 09:54
Yeo, as this problem is caused by integration not handling the session well (mostly custom integration), I'll go ahead and close this issue up.

There is nothing we can do about this from the Supervisor end.

**Closed by frenck** 2020-03-09 09:54 UTC

**Comment by sblantipodi** [comment] 2020-05-08 12:24
@frenck I have the same issue, I'm using only "official integration" what is the right channel to report this issue?

Thanks
