### ISSUE TITLE
Keep getting upgrade notifications to a downgrade.

### ISSUE THREAD

**Issue by foltz61** [home-assistant/supervisor#2829] opened 2021-04-20 23:21 UTC
### The problem

For the last few days I've gotten notices to upgrade from core-2021.4.4 to core-2021.4.6. Then after upgrading I get notices to upgrade from core-2021.4.6 to core-2021.4.4. If I follow that I get the upgrade to core-2021.4.6 notice.

### What is version of Home Assistant Core has the issue?

core-2021.4.6

### What was the last working version of Home Assistant Core?

core-2021.4.4

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

Core

### Anything in the logs that might be useful for us?

```txt
Nope
```

**Comment by ludeeus** [comment] 2021-04-21 08:53
Duplicate of #2800

**Closed by ludeeus** 2021-04-21 08:53 UTC
