### ISSUE TITLE
Openweathermap error

### ISSUE THREAD

**Issue by davide-rhw** [home-assistant/supervisor#1678] opened 2020-04-23 15:41 UTC
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 324, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 476, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/openweathermap/weather.py", line 231, in update
    self._owm.update_forecast()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 240, in wrapper
    result = method(*args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/components/openweathermap/weather.py", line 272, in update_forecast
    self.latitude, self.longitude
  File "/usr/local/lib/python3.7/site-packages/pyowm/weatherapi25/owm25.py", line 602, in three_hours_forecast_at_coords
    forecast = self._parsers['forecast'].parse_JSON(json_data)
  File "/usr/local/lib/python3.7/site-packages/pyowm/weatherapi25/parsers/forecastparser.py", line 66, in parse_JSON
    for item in d['list']]
  File "/usr/local/lib/python3.7/site-packages/pyowm/weatherapi25/parsers/forecastparser.py", line 66, in <listcomp>
    for item in d['list']]
  File "/usr/local/lib/python3.7/site-packages/pyowm/weatherapi25/weather.py", line 583, in weather_from_dictionary
    visibility_distance, dewpoint, humidex, heat_index)
  File "/usr/local/lib/python3.7/site-packages/pyowm/weatherapi25/weather.py", line 74, in __init__
    raise ValueError("'clouds' must be greater than 0")
ValueError: 'clouds' must be greater than 0

**Comment by fabaff** [comment] 2020-04-23 15:46
Duplicate of https://github.com/home-assistant/core/issues/34543

**Closed by fabaff** 2020-04-23 15:46 UTC
