### ISSUE TITLE
Supervisor 249: Resolution Center Fails - Persistent Notification for Low Disk Space is wrong

### ISSUE THREAD

**Issue by Ndrinta** [home-assistant/supervisor#2204] opened 2020-10-31 16:09 UTC
My Home Assistant does a new thing now, after updating to 249. :sweat_smile:
He sends me these persistent notifications, a few times a day, even though there is no reason for.
A few hours ago I got the first notification and I was really getting out of space but since then I cleaned the disk from some outdated backups and I went back to 3GB of free space. The Supervisor clearly doesn’t care and it keeps sending me these notifications (roughly every hour). This must be some sort of bug… Has anyone here experienced it and maybe fixed it somehow?
Any help will be appreciated :slightly_smiling_face:
![Screenshot_20201031-084450_3](https://user-images.githubusercontent.com/4704172/97783988-43688d80-1b93-11eb-8d84-5c363515ab9b.png)

Reporte also in [HA Community Forum](https://community.home-assistant.io/t/supervisor-249-resolution-center-fails-persistent-notification-for-low-disk-space-is-wrong/240717)

**Comment by ludeeus** [comment] 2020-10-31 16:25
Duplicate of https://github.com/home-assistant/supervisor/issues/2191
Fixed in the current beta version

**Closed by ludeeus** 2020-10-31 16:25 UTC
